sudo: require
language: cpp
compiler: gcc

os: linux
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq g++-8

#install: 
#  - sudo apt-get install -qq g++-8

script: 
  - cmake
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1af5a35c-cce4-4611-878a-7f0e78841353
