# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ed/tr29124_test/polynomial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ed/tr29124_test/polynomial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ed/tr29124_test/polynomial/CMakeFiles /home/ed/tr29124_test/polynomial/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ed/tr29124_test/polynomial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_quadratic_step

# Build rule for target.
test_quadratic_step: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_quadratic_step
.PHONY : test_quadratic_step

# fast build rule for target.
test_quadratic_step/fast:
	$(MAKE) -f CMakeFiles/test_quadratic_step.dir/build.make CMakeFiles/test_quadratic_step.dir/build
.PHONY : test_quadratic_step/fast

#=============================================================================
# Target rules for targets named test_laguerre_step

# Build rule for target.
test_laguerre_step: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_laguerre_step
.PHONY : test_laguerre_step

# fast build rule for target.
test_laguerre_step/fast:
	$(MAKE) -f CMakeFiles/test_laguerre_step.dir/build.make CMakeFiles/test_laguerre_step.dir/build
.PHONY : test_laguerre_step/fast

#=============================================================================
# Target rules for targets named test_static_polynomial

# Build rule for target.
test_static_polynomial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_static_polynomial
.PHONY : test_static_polynomial

# fast build rule for target.
test_static_polynomial/fast:
	$(MAKE) -f CMakeFiles/test_static_polynomial.dir/build.make CMakeFiles/test_static_polynomial.dir/build
.PHONY : test_static_polynomial/fast

#=============================================================================
# Target rules for targets named test_solution

# Build rule for target.
test_solution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_solution
.PHONY : test_solution

# fast build rule for target.
test_solution/fast:
	$(MAKE) -f CMakeFiles/test_solution.dir/build.make CMakeFiles/test_solution.dir/build
.PHONY : test_solution/fast

#=============================================================================
# Target rules for targets named test_solvers

# Build rule for target.
test_solvers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_solvers
.PHONY : test_solvers

# fast build rule for target.
test_solvers/fast:
	$(MAKE) -f CMakeFiles/test_solvers.dir/build.make CMakeFiles/test_solvers.dir/build
.PHONY : test_solvers/fast

#=============================================================================
# Target rules for targets named test_bairstow

# Build rule for target.
test_bairstow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bairstow
.PHONY : test_bairstow

# fast build rule for target.
test_bairstow/fast:
	$(MAKE) -f CMakeFiles/test_bairstow.dir/build.make CMakeFiles/test_bairstow.dir/build
.PHONY : test_bairstow/fast

#=============================================================================
# Target rules for targets named test_polynomial

# Build rule for target.
test_polynomial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_polynomial
.PHONY : test_polynomial

# fast build rule for target.
test_polynomial/fast:
	$(MAKE) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/build
.PHONY : test_polynomial/fast

#=============================================================================
# Target rules for targets named test_polynomial_root

# Build rule for target.
test_polynomial_root: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_polynomial_root
.PHONY : test_polynomial_root

# fast build rule for target.
test_polynomial_root/fast:
	$(MAKE) -f CMakeFiles/test_polynomial_root.dir/build.make CMakeFiles/test_polynomial_root.dir/build
.PHONY : test_polynomial_root/fast

#=============================================================================
# Target rules for targets named test_jenkins_traub

# Build rule for target.
test_jenkins_traub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_jenkins_traub
.PHONY : test_jenkins_traub

# fast build rule for target.
test_jenkins_traub/fast:
	$(MAKE) -f CMakeFiles/test_jenkins_traub.dir/build.make CMakeFiles/test_jenkins_traub.dir/build
.PHONY : test_jenkins_traub/fast

#=============================================================================
# Target rules for targets named test_horner

# Build rule for target.
test_horner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_horner
.PHONY : test_horner

# fast build rule for target.
test_horner/fast:
	$(MAKE) -f CMakeFiles/test_horner.dir/build.make CMakeFiles/test_horner.dir/build
.PHONY : test_horner/fast

#=============================================================================
# Target rules for targets named test_rational_polynomial

# Build rule for target.
test_rational_polynomial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rational_polynomial
.PHONY : test_rational_polynomial

# fast build rule for target.
test_rational_polynomial/fast:
	$(MAKE) -f CMakeFiles/test_rational_polynomial.dir/build.make CMakeFiles/test_rational_polynomial.dir/build
.PHONY : test_rational_polynomial/fast

test_bairstow.o: test_bairstow.cpp.o

.PHONY : test_bairstow.o

# target to build an object file
test_bairstow.cpp.o:
	$(MAKE) -f CMakeFiles/test_bairstow.dir/build.make CMakeFiles/test_bairstow.dir/test_bairstow.cpp.o
.PHONY : test_bairstow.cpp.o

test_bairstow.i: test_bairstow.cpp.i

.PHONY : test_bairstow.i

# target to preprocess a source file
test_bairstow.cpp.i:
	$(MAKE) -f CMakeFiles/test_bairstow.dir/build.make CMakeFiles/test_bairstow.dir/test_bairstow.cpp.i
.PHONY : test_bairstow.cpp.i

test_bairstow.s: test_bairstow.cpp.s

.PHONY : test_bairstow.s

# target to generate assembly for a file
test_bairstow.cpp.s:
	$(MAKE) -f CMakeFiles/test_bairstow.dir/build.make CMakeFiles/test_bairstow.dir/test_bairstow.cpp.s
.PHONY : test_bairstow.cpp.s

test_horner.o: test_horner.cpp.o

.PHONY : test_horner.o

# target to build an object file
test_horner.cpp.o:
	$(MAKE) -f CMakeFiles/test_horner.dir/build.make CMakeFiles/test_horner.dir/test_horner.cpp.o
.PHONY : test_horner.cpp.o

test_horner.i: test_horner.cpp.i

.PHONY : test_horner.i

# target to preprocess a source file
test_horner.cpp.i:
	$(MAKE) -f CMakeFiles/test_horner.dir/build.make CMakeFiles/test_horner.dir/test_horner.cpp.i
.PHONY : test_horner.cpp.i

test_horner.s: test_horner.cpp.s

.PHONY : test_horner.s

# target to generate assembly for a file
test_horner.cpp.s:
	$(MAKE) -f CMakeFiles/test_horner.dir/build.make CMakeFiles/test_horner.dir/test_horner.cpp.s
.PHONY : test_horner.cpp.s

test_jenkins_traub.o: test_jenkins_traub.cpp.o

.PHONY : test_jenkins_traub.o

# target to build an object file
test_jenkins_traub.cpp.o:
	$(MAKE) -f CMakeFiles/test_jenkins_traub.dir/build.make CMakeFiles/test_jenkins_traub.dir/test_jenkins_traub.cpp.o
.PHONY : test_jenkins_traub.cpp.o

test_jenkins_traub.i: test_jenkins_traub.cpp.i

.PHONY : test_jenkins_traub.i

# target to preprocess a source file
test_jenkins_traub.cpp.i:
	$(MAKE) -f CMakeFiles/test_jenkins_traub.dir/build.make CMakeFiles/test_jenkins_traub.dir/test_jenkins_traub.cpp.i
.PHONY : test_jenkins_traub.cpp.i

test_jenkins_traub.s: test_jenkins_traub.cpp.s

.PHONY : test_jenkins_traub.s

# target to generate assembly for a file
test_jenkins_traub.cpp.s:
	$(MAKE) -f CMakeFiles/test_jenkins_traub.dir/build.make CMakeFiles/test_jenkins_traub.dir/test_jenkins_traub.cpp.s
.PHONY : test_jenkins_traub.cpp.s

test_laguerre_step.o: test_laguerre_step.cpp.o

.PHONY : test_laguerre_step.o

# target to build an object file
test_laguerre_step.cpp.o:
	$(MAKE) -f CMakeFiles/test_laguerre_step.dir/build.make CMakeFiles/test_laguerre_step.dir/test_laguerre_step.cpp.o
.PHONY : test_laguerre_step.cpp.o

test_laguerre_step.i: test_laguerre_step.cpp.i

.PHONY : test_laguerre_step.i

# target to preprocess a source file
test_laguerre_step.cpp.i:
	$(MAKE) -f CMakeFiles/test_laguerre_step.dir/build.make CMakeFiles/test_laguerre_step.dir/test_laguerre_step.cpp.i
.PHONY : test_laguerre_step.cpp.i

test_laguerre_step.s: test_laguerre_step.cpp.s

.PHONY : test_laguerre_step.s

# target to generate assembly for a file
test_laguerre_step.cpp.s:
	$(MAKE) -f CMakeFiles/test_laguerre_step.dir/build.make CMakeFiles/test_laguerre_step.dir/test_laguerre_step.cpp.s
.PHONY : test_laguerre_step.cpp.s

test_polynomial.o: test_polynomial.cpp.o

.PHONY : test_polynomial.o

# target to build an object file
test_polynomial.cpp.o:
	$(MAKE) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/test_polynomial.cpp.o
.PHONY : test_polynomial.cpp.o

test_polynomial.i: test_polynomial.cpp.i

.PHONY : test_polynomial.i

# target to preprocess a source file
test_polynomial.cpp.i:
	$(MAKE) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/test_polynomial.cpp.i
.PHONY : test_polynomial.cpp.i

test_polynomial.s: test_polynomial.cpp.s

.PHONY : test_polynomial.s

# target to generate assembly for a file
test_polynomial.cpp.s:
	$(MAKE) -f CMakeFiles/test_polynomial.dir/build.make CMakeFiles/test_polynomial.dir/test_polynomial.cpp.s
.PHONY : test_polynomial.cpp.s

test_polynomial_root.o: test_polynomial_root.cpp.o

.PHONY : test_polynomial_root.o

# target to build an object file
test_polynomial_root.cpp.o:
	$(MAKE) -f CMakeFiles/test_polynomial_root.dir/build.make CMakeFiles/test_polynomial_root.dir/test_polynomial_root.cpp.o
.PHONY : test_polynomial_root.cpp.o

test_polynomial_root.i: test_polynomial_root.cpp.i

.PHONY : test_polynomial_root.i

# target to preprocess a source file
test_polynomial_root.cpp.i:
	$(MAKE) -f CMakeFiles/test_polynomial_root.dir/build.make CMakeFiles/test_polynomial_root.dir/test_polynomial_root.cpp.i
.PHONY : test_polynomial_root.cpp.i

test_polynomial_root.s: test_polynomial_root.cpp.s

.PHONY : test_polynomial_root.s

# target to generate assembly for a file
test_polynomial_root.cpp.s:
	$(MAKE) -f CMakeFiles/test_polynomial_root.dir/build.make CMakeFiles/test_polynomial_root.dir/test_polynomial_root.cpp.s
.PHONY : test_polynomial_root.cpp.s

test_quadratic_step.o: test_quadratic_step.cpp.o

.PHONY : test_quadratic_step.o

# target to build an object file
test_quadratic_step.cpp.o:
	$(MAKE) -f CMakeFiles/test_quadratic_step.dir/build.make CMakeFiles/test_quadratic_step.dir/test_quadratic_step.cpp.o
.PHONY : test_quadratic_step.cpp.o

test_quadratic_step.i: test_quadratic_step.cpp.i

.PHONY : test_quadratic_step.i

# target to preprocess a source file
test_quadratic_step.cpp.i:
	$(MAKE) -f CMakeFiles/test_quadratic_step.dir/build.make CMakeFiles/test_quadratic_step.dir/test_quadratic_step.cpp.i
.PHONY : test_quadratic_step.cpp.i

test_quadratic_step.s: test_quadratic_step.cpp.s

.PHONY : test_quadratic_step.s

# target to generate assembly for a file
test_quadratic_step.cpp.s:
	$(MAKE) -f CMakeFiles/test_quadratic_step.dir/build.make CMakeFiles/test_quadratic_step.dir/test_quadratic_step.cpp.s
.PHONY : test_quadratic_step.cpp.s

test_rational_polynomial.o: test_rational_polynomial.cpp.o

.PHONY : test_rational_polynomial.o

# target to build an object file
test_rational_polynomial.cpp.o:
	$(MAKE) -f CMakeFiles/test_rational_polynomial.dir/build.make CMakeFiles/test_rational_polynomial.dir/test_rational_polynomial.cpp.o
.PHONY : test_rational_polynomial.cpp.o

test_rational_polynomial.i: test_rational_polynomial.cpp.i

.PHONY : test_rational_polynomial.i

# target to preprocess a source file
test_rational_polynomial.cpp.i:
	$(MAKE) -f CMakeFiles/test_rational_polynomial.dir/build.make CMakeFiles/test_rational_polynomial.dir/test_rational_polynomial.cpp.i
.PHONY : test_rational_polynomial.cpp.i

test_rational_polynomial.s: test_rational_polynomial.cpp.s

.PHONY : test_rational_polynomial.s

# target to generate assembly for a file
test_rational_polynomial.cpp.s:
	$(MAKE) -f CMakeFiles/test_rational_polynomial.dir/build.make CMakeFiles/test_rational_polynomial.dir/test_rational_polynomial.cpp.s
.PHONY : test_rational_polynomial.cpp.s

test_solution.o: test_solution.cpp.o

.PHONY : test_solution.o

# target to build an object file
test_solution.cpp.o:
	$(MAKE) -f CMakeFiles/test_solution.dir/build.make CMakeFiles/test_solution.dir/test_solution.cpp.o
.PHONY : test_solution.cpp.o

test_solution.i: test_solution.cpp.i

.PHONY : test_solution.i

# target to preprocess a source file
test_solution.cpp.i:
	$(MAKE) -f CMakeFiles/test_solution.dir/build.make CMakeFiles/test_solution.dir/test_solution.cpp.i
.PHONY : test_solution.cpp.i

test_solution.s: test_solution.cpp.s

.PHONY : test_solution.s

# target to generate assembly for a file
test_solution.cpp.s:
	$(MAKE) -f CMakeFiles/test_solution.dir/build.make CMakeFiles/test_solution.dir/test_solution.cpp.s
.PHONY : test_solution.cpp.s

test_solvers.o: test_solvers.cpp.o

.PHONY : test_solvers.o

# target to build an object file
test_solvers.cpp.o:
	$(MAKE) -f CMakeFiles/test_solvers.dir/build.make CMakeFiles/test_solvers.dir/test_solvers.cpp.o
.PHONY : test_solvers.cpp.o

test_solvers.i: test_solvers.cpp.i

.PHONY : test_solvers.i

# target to preprocess a source file
test_solvers.cpp.i:
	$(MAKE) -f CMakeFiles/test_solvers.dir/build.make CMakeFiles/test_solvers.dir/test_solvers.cpp.i
.PHONY : test_solvers.cpp.i

test_solvers.s: test_solvers.cpp.s

.PHONY : test_solvers.s

# target to generate assembly for a file
test_solvers.cpp.s:
	$(MAKE) -f CMakeFiles/test_solvers.dir/build.make CMakeFiles/test_solvers.dir/test_solvers.cpp.s
.PHONY : test_solvers.cpp.s

test_static_polynomial.o: test_static_polynomial.cpp.o

.PHONY : test_static_polynomial.o

# target to build an object file
test_static_polynomial.cpp.o:
	$(MAKE) -f CMakeFiles/test_static_polynomial.dir/build.make CMakeFiles/test_static_polynomial.dir/test_static_polynomial.cpp.o
.PHONY : test_static_polynomial.cpp.o

test_static_polynomial.i: test_static_polynomial.cpp.i

.PHONY : test_static_polynomial.i

# target to preprocess a source file
test_static_polynomial.cpp.i:
	$(MAKE) -f CMakeFiles/test_static_polynomial.dir/build.make CMakeFiles/test_static_polynomial.dir/test_static_polynomial.cpp.i
.PHONY : test_static_polynomial.cpp.i

test_static_polynomial.s: test_static_polynomial.cpp.s

.PHONY : test_static_polynomial.s

# target to generate assembly for a file
test_static_polynomial.cpp.s:
	$(MAKE) -f CMakeFiles/test_static_polynomial.dir/build.make CMakeFiles/test_static_polynomial.dir/test_static_polynomial.cpp.s
.PHONY : test_static_polynomial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... test_quadratic_step"
	@echo "... test_laguerre_step"
	@echo "... test_static_polynomial"
	@echo "... test_solution"
	@echo "... test_solvers"
	@echo "... test_bairstow"
	@echo "... test_polynomial"
	@echo "... test_polynomial_root"
	@echo "... test_jenkins_traub"
	@echo "... test_horner"
	@echo "... test_rational_polynomial"
	@echo "... test_bairstow.o"
	@echo "... test_bairstow.i"
	@echo "... test_bairstow.s"
	@echo "... test_horner.o"
	@echo "... test_horner.i"
	@echo "... test_horner.s"
	@echo "... test_jenkins_traub.o"
	@echo "... test_jenkins_traub.i"
	@echo "... test_jenkins_traub.s"
	@echo "... test_laguerre_step.o"
	@echo "... test_laguerre_step.i"
	@echo "... test_laguerre_step.s"
	@echo "... test_polynomial.o"
	@echo "... test_polynomial.i"
	@echo "... test_polynomial.s"
	@echo "... test_polynomial_root.o"
	@echo "... test_polynomial_root.i"
	@echo "... test_polynomial_root.s"
	@echo "... test_quadratic_step.o"
	@echo "... test_quadratic_step.i"
	@echo "... test_quadratic_step.s"
	@echo "... test_rational_polynomial.o"
	@echo "... test_rational_polynomial.i"
	@echo "... test_rational_polynomial.s"
	@echo "... test_solution.o"
	@echo "... test_solution.i"
	@echo "... test_solution.s"
	@echo "... test_solvers.o"
	@echo "... test_solvers.i"
	@echo "... test_solvers.s"
	@echo "... test_static_polynomial.o"
	@echo "... test_static_polynomial.i"
	@echo "... test_static_polynomial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

