__gnu_cxx::_Polynomial< _Tp > Class Template Reference
A dense polynomial class with a contiguous array of coefficients. The coefficients are lowest-order first:
 P(x) = a_0 + a_1 x + ... + a_n x^n 
.
#include <polynomial.h>
Public Types
using const_iterator = typename std::vector< value_type >::const_iterator
using const_pointer = typename std::vector< value_type >::const_pointer
using const_reference = typename std::vector< value_type >::const_reference
using const_reverse_iterator = typename std::vector< value_type >::const_reverse_iterator
using difference_type = typename std::vector< value_type >::difference_type
using iterator = typename std::vector< value_type >::iterator
using pointer = typename std::vector< value_type >::pointer
using real_type = __real_type_t< _Tp >
using reference = typename std::vector< value_type >::reference
using reverse_iterator = typename std::vector< value_type >::reverse_iterator
using size_type = typename std::vector< value_type >::size_type
using value_type = typename std::vector< _Tp >::value_type
Public Member Functions
_Polynomial ()
_Polynomial (const _Polynomial &)=default
_Polynomial (_Polynomial &&) noexcept=default
template<typename _Up >
_Polynomial (const _Polynomial< _Up > &__poly)
_Polynomial (value_type __a, size_type __degree=0)
_Polynomial (std::initializer_list< value_type > __ila)
template<typename InIter , typename = std::_RequireInputIter<InIter>>
_Polynomial (const InIter &__abegin, const InIter &__aend)
template<typename InIter , typename = std::_RequireInputIter<InIter>>
_Polynomial (const InIter &__xbegin, const InIter &__xend, const InIter &__ybegin)
template<typename Gen >
_Polynomial (Gen __gen, size_type __degree)
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
value_type coefficient (size_type __i) const
void coefficient (size_type __i, value_type __val)
const std::vector< value_type > coefficients () const noexcept
std::vector< value_type > coefficients () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
const value_type * data () const noexcept
value_type * data () noexcept
_Polynomial & deflate (real_type __max_abs_coef)
_Polynomial & deflate (const _Polynomial< value_type > &__poly, real_type __max_abs_coef)
size_type degree () const noexcept
void degree (size_type __degree)
_Polynomial derivative () const
iterator end () noexcept
const_iterator end () const noexcept
template<typename _Polynomial< _Tp >::size_type N>
void eval (typename _Polynomial< _Tp >::value_type __x, std::array< _Polynomial< _Tp >::value_type, N > &__arr)
template<typename OutIter>
void eval (typename _Polynomial< _Tp >::value_type __x, OutIter __b, OutIter __e)
template<size_type N>
void eval (value_type __x, std::array< value_type, N > &__arr)
template<typename OutIter >
void eval (value_type __x, OutIter __b, OutIter __e)
template<typename _Tp >
_Polynomial< _Tp >::value_type eval_even (typename _Polynomial< _Tp >::value_type __x) const
value_type eval_even (value_type __x) const
template<typename _Up >
auto eval_even (const std::complex< _Up > &__z) const -> std::enable_if_t<!__has_imag_v< _Tp >, std::complex< std::decay_t< decltype(typename _Polynomial< _Tp >::value_type
template<typename _Tp >
_Polynomial< _Tp >::value_type eval_odd (typename _Polynomial< _Tp >::value_type __x) const
value_type eval_odd (value_type __x) const
template<typename _Up >
auto eval_odd (const std::complex< _Up > &__z) const -> std::enable_if_t<!__has_imag_v< _Tp >, std::complex< std::decay_t< decltype(typename _Polynomial< _Tp >::value_type
_Polynomial integral (value_type __c=value_type{}) const
template<typename _Up >
_Polynomial & operator%= (const _Up &)
template<typename _Up >
_Polynomial & operator%= (const _Polynomial< _Up > &__poly)
template<typename _Up >
auto operator() (const std::complex< _Up > &__z) const -> std::enable_if_t<!__has_imag_v< _Tp >, std::complex< std::decay_t< decltype(typename _Polynomial< _Tp >::value_type
value_type operator() (value_type __x) const
template<typename _Up >
auto operator() (_Up __x) const -> decltype(value_type
template<typename InIter , typename OutIter , typename = std::_RequireInputIter<InIter>>
OutIter operator() (const InIter &__xbegin, const InIter &__xend, OutIter &__pbegin) const
template<typename _Up >
_Polynomial< _Tp > & operator*= (const _Polynomial< _Up > &__poly)
template<typename _Up >
_Polynomial & operator*= (const _Up &__c)
template<typename _Up >
_Polynomial & operator*= (const _Polynomial< _Up > &__poly)
_Polynomial operator+ () const noexcept
template<typename _Up >
_Polynomial & operator+= (const _Up &__x)
template<typename _Up >
_Polynomial & operator+= (const _Polynomial< _Up > &__poly)
_Polynomial operator- () const
template<typename _Up >
_Polynomial & operator-= (const _Up &__x)
template<typename _Up >
_Polynomial & operator-= (const _Polynomial< _Up > &__poly)
template<typename _Up >
_Polynomial & operator/= (const _Up &__c)
template<typename _Up >
_Polynomial & operator/= (const _Polynomial< _Up > &__poly)
_Polynomial & operator= (const value_type &__x)
_Polynomial & operator= (const _Polynomial &)=default
template<typename _Up >
_Polynomial & operator= (const _Polynomial< _Up > &__poly)
_Polynomial & operator= (std::initializer_list< value_type > __ila)
value_type operator[] (size_type __i) const noexcept
reference operator[] (size_type __i) noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
size_type size () const noexcept
void swap (_Polynomial &__poly) noexcept
Public Attributes
* _Up
Friends
template<typename _Tp1 >
bool operator== (const _Polynomial< _Tp1 > &__pa, const _Polynomial< _Tp1 > &__pb)
template<typename CharT , typename Traits , typename _Tp1 >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &, _Polynomial< _Tp1 > &)
Detailed Description
template<typename _Tp>
class __gnu_cxx::_Polynomial< _Tp >
A dense polynomial class with a contiguous array of coefficients. The coefficients are lowest-order first:
 P(x) = a_0 + a_1 x + ... + a_n x^n 
.
Definition at line 130 of file polynomial.h.
Member Typedef Documentation
const_iterator
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::const_iterator = typename std::vector<value_type>::const_iterator
Definition at line 167 of file polynomial.h.
const_pointer
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::const_pointer = typename std::vector<value_type>::const_pointer
Definition at line 165 of file polynomial.h.
const_reference
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::const_reference = typename std::vector<value_type>::const_reference
Definition at line 163 of file polynomial.h.
const_reverse_iterator
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::const_reverse_iterator = typename std::vector<value_type>::const_reverse_iterator
Definition at line 171 of file polynomial.h.
difference_type
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::difference_type = typename std::vector<value_type>::difference_type
Definition at line 173 of file polynomial.h.
iterator
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::iterator = typename std::vector<value_type>::iterator
Definition at line 166 of file polynomial.h.
pointer
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::pointer = typename std::vector<value_type>::pointer
Definition at line 164 of file polynomial.h.
real_type
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::real_type = __real_type_t<_Tp>
Definition at line 174 of file polynomial.h.
reference
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::reference = typename std::vector<value_type>::reference
Definition at line 162 of file polynomial.h.
reverse_iterator
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::reverse_iterator = typename std::vector<value_type>::reverse_iterator
Definition at line 169 of file polynomial.h.
size_type
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::size_type = typename std::vector<value_type>::size_type
Definition at line 172 of file polynomial.h.
value_type
template<typename _Tp>
using __gnu_cxx::_Polynomial< _Tp >::value_type = typename std::vector<_Tp>::value_type
Typedefs.
Definition at line 161 of file polynomial.h.
Constructor & Destructor Documentation
_Polynomial() [1/9]
template<typename _Tp>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial () [inline]
Create a zero degree polynomial with coefficient value zero.
Definition at line 179 of file polynomial.h.
      : _M_coeff(1)
      { }
_Polynomial() [2/9]
template<typename _Tp>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (const _Polynomial< _Tp > &) [default]
Copy ctor.
_Polynomial() [3/9]
template<typename _Tp>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (_Polynomial< _Tp > &&) [default], [noexcept]
Move ctor.
_Polynomial() [4/9]
template<typename _Tp>
template<typename _Up >
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (const _Polynomial< _Up > & __poly) [inline]
Definition at line 194 of file polynomial.h.
        : _M_coeff{}
        {
          for (const auto __c : __poly)
            this->_M_coeff.push_back(static_cast<value_type>(__c));
          this->_M_set_scale();
        }
_Polynomial() [5/9]
template<typename _Tp>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (value_type __a, size_type __degree = 0) [inline], [explicit]
Create a monomial.
Definition at line 206 of file polynomial.h.
      : _M_coeff(__degree + 1)
      { this->_M_coeff[__degree] = __a; }
_Polynomial() [6/9]
template<typename _Tp>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (std::initializer_list< value_type > __ila) [inline]
Create a polynomial from an initializer list of coefficients.
Definition at line 213 of file polynomial.h.
      : _M_coeff(__ila)
      { this->_M_set_scale(); }
_Polynomial() [7/9]
template<typename _Tp>
template<typename InIter , typename = std::_RequireInputIter<InIter>>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (const InIter & __abegin, const InIter & __aend) [inline]
Create a polynomial from an input iterator range of coefficients.
Definition at line 222 of file polynomial.h.
        : _M_coeff(__abegin, __aend)
        { this->_M_set_scale(); }
_Polynomial() [8/9]
template<typename _Tp>
template<typename InIter , typename = std::_RequireInputIter<InIter>>
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (const InIter & __xbegin, const InIter & __xend, const InIter & __ybegin) [inline]
Use Lagrange interpolation to construct a polynomial passing through the data points. The degree will be one less than the number of points.
Definition at line 232 of file polynomial.h.
        : _M_coeff()
        {
          std::vector<_Polynomial<value_type>> __numer;
          std::vector<_Polynomial<value_type>> __denom;
          for (auto __xi = __xbegin; __xi != __xend; ++__xi)
            {
              for (auto __xj = __xi + 1; __xj != __xend; ++__xj)
                __denom.push_back(value_type(*__xj) - value_type(*__xi));
              __numer.push_back({-value_type(*__xi), value_type{1}});
            }
          this->_M_set_scale();
        }
_Polynomial() [9/9]
template<typename _Tp>
template<typename Gen >
__gnu_cxx::_Polynomial< _Tp >::_Polynomial (Gen __gen, size_type __degree) [inline]
Create a polynomial from a generator and a maximum degree.
Definition at line 251 of file polynomial.h.
        : _M_coeff()
        {
          this->_M_coeff.reserve(__degree + 1);
          for (size_type __k = 0; __k <= __degree; ++__k)
            this->_M_coeff.push_back(__gen(__k));
          this->_M_set_scale();
        }
Member Function Documentation
begin() [1/2]
template<typename _Tp>
iterator __gnu_cxx::_Polynomial< _Tp >::begin () [inline], [noexcept]
Return an iterator to the beginning of the coefficient sequence.
Definition at line 707 of file polynomial.h.
      { return this->_M_coeff.begin(); }
begin() [2/2]
template<typename _Tp>
const_iterator __gnu_cxx::_Polynomial< _Tp >::begin () const [inline], [noexcept]
Return a const iterator the beginning of the coefficient sequence.
Definition at line 722 of file polynomial.h.
      { return this->_M_coeff.begin(); }
cbegin()
template<typename _Tp>
const_iterator __gnu_cxx::_Polynomial< _Tp >::cbegin () const [inline], [noexcept]
Return a const iterator the beginning of the coefficient sequence.
Definition at line 738 of file polynomial.h.
      { return this->_M_coeff.cbegin(); }
cend()
template<typename _Tp>
const_iterator __gnu_cxx::_Polynomial< _Tp >::cend () const [inline], [noexcept]
Return a const iterator to one past the end of the coefficient sequence.
Definition at line 746 of file polynomial.h.
      { return this->_M_coeff.cend(); }
coefficient() [1/2]
template<typename _Tp>
value_type __gnu_cxx::_Polynomial< _Tp >::coefficient (size_type __i) const [inline]
Return the ith coefficient with range checking.
Definition at line 651 of file polynomial.h.
Referenced by __gnu_cxx::divmod(), and __gnu_cxx::operator<<().
      { return this->_M_coeff.at(__i); }
coefficient() [2/2]
template<typename _Tp>
void __gnu_cxx::_Polynomial< _Tp >::coefficient (size_type __i, value_type __val) [inline]
Set coefficient i to val with range checking.
Definition at line 658 of file polynomial.h.
      { this->_M_coeff.at(__i) = __val; }
coefficients() [1/2]
template<typename _Tp>
const std::vector<value_type> __gnu_cxx::_Polynomial< _Tp >::coefficients () const [inline], [noexcept]
Return a const vector of coefficients.
Definition at line 679 of file polynomial.h.
      { return this->_M_coeff; }
coefficients() [2/2]
template<typename _Tp>
std::vector<value_type> __gnu_cxx::_Polynomial< _Tp >::coefficients () [inline], [noexcept]
Return a vector of coefficients.
Definition at line 686 of file polynomial.h.
      { return this->_M_coeff; }
crbegin()
template<typename _Tp>
const_reverse_iterator __gnu_cxx::_Polynomial< _Tp >::crbegin () const [inline], [noexcept]
Definition at line 766 of file polynomial.h.
      { return this->_M_coeff.crbegin(); }
crend()
template<typename _Tp>
const_reverse_iterator __gnu_cxx::_Polynomial< _Tp >::crend () const [inline], [noexcept]
Definition at line 770 of file polynomial.h.
      { return this->_M_coeff.crend(); }
data() [1/2]
template<typename _Tp>
const value_type* __gnu_cxx::_Polynomial< _Tp >::data () const [inline], [noexcept]
Return a const pointer to the coefficient sequence.
Definition at line 693 of file polynomial.h.
      { return this->_M_coeff.data(); }
data() [2/2]
template<typename _Tp>
value_type* __gnu_cxx::_Polynomial< _Tp >::data () [inline], [noexcept]
Return a pointer to the coefficient sequence.
Definition at line 700 of file polynomial.h.
      { return this->_M_coeff.data(); }
deflate() [1/2]
template<typename _Tp>
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::deflate (real_type __max_abs_coef) [inline]
Remove zero max-order coefficients.
Definition at line 786 of file polynomial.h.
Referenced by __gnu_cxx::_Polynomial< value_type >::deflate().
      {
        size_type __n = this->degree();
        for (size_type __i = this->degree(); __i > 0; --__i)
          if (std::abs(this->_M_coeff[__i]) < __max_abs_coef)
            --__n;
          else
            break;
        this->degree(__n);
        return *this;
      }
deflate() [2/2]
template<typename _Tp>
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::deflate (const _Polynomial< value_type > & __poly, real_type __max_abs_coef) [inline]
Divide the polynomial by an input polynomia and remove zero max-order coefficients.
Definition at line 803 of file polynomial.h.
      {
        _Polynomial<value_type> __quo, __rem;
        divmod(*this, __poly, __quo, __rem);
        // Remainder should be null.
        size_type __n = __rem.degree();
        for (size_type __i = __rem.degree(); __i > 0; --__i)
          if (std::abs(__rem[__i]) < __max_abs_coef)
            --__n;
          else
            break;
        if (__n == 0)
          *this = __quo.deflate(__max_abs_coef);
        else
          throw std::runtime_error("deflate: ");
        return *this;
      }
degree() [1/2]
template<typename _Tp>
size_type __gnu_cxx::_Polynomial< _Tp >::degree () const [inline], [noexcept]
Return the degree or the power of the largest coefficient.
Definition at line 630 of file polynomial.h.
Referenced by __gnu_cxx::_Polynomial< value_type >::deflate(), __gnu_cxx::divmod(), __gnu_cxx::_Polynomial< value_type >::operator*=(), __gnu_cxx::_Polynomial< value_type >::operator+=(), and __gnu_cxx::_Polynomial< value_type >::operator-=().
      { return this->_M_coeff.size() - 1; }
degree() [2/2]
template<typename _Tp>
void __gnu_cxx::_Polynomial< _Tp >::degree (size_type __degree) [inline]
Set the degree or the power of the largest coefficient.
Definition at line 637 of file polynomial.h.
      { this->_M_coeff.resize(__degree + 1UL); }
derivative()
template<typename _Tp>
_Polynomial __gnu_cxx::_Polynomial< _Tp >::derivative () const [inline]
Return the derivative polynomial.
Definition at line 431 of file polynomial.h.
      {
        _Polynomial __res(value_type{},
                          this->degree() > 0UL ? this->degree() - 1 : 0UL);
        for (size_type __n = this->degree(), __i = 1; __i <= __n; ++__i)
          __res._M_coeff[__i - 1] = __i * this->_M_coeff[__i];
        return __res;
      }
end() [1/2]
template<typename _Tp>
iterator __gnu_cxx::_Polynomial< _Tp >::end () [inline], [noexcept]
Return an iterator to one past the end of the coefficient sequence.
Definition at line 714 of file polynomial.h.
      { return this->_M_coeff.end(); }
end() [2/2]
template<typename _Tp>
const_iterator __gnu_cxx::_Polynomial< _Tp >::end () const [inline], [noexcept]
Return a const iterator to one past the end of the coefficient sequence.
Definition at line 730 of file polynomial.h.
      { return this->_M_coeff.end(); }
eval() [1/4]
template<typename _Tp>
template<typename _Polynomial< _Tp >::size_type N>
void __gnu_cxx::_Polynomial< _Tp >::eval (typename _Polynomial< _Tp >::value_type __x, std::array< _Polynomial< _Tp >::value_type, N > & __arr)
Definition at line 187 of file polynomial.tcc.
      {
        if (__arr.size() > 0)
          {
            __arr.fill(value_type{});
            const size_type __sz = _M_coeff.size();
            __arr[0] = this->coefficient(__sz - 1);
            for (int __i = __sz - 2; __i >= 0; --__i)
              {
                int __nn = std::min(__arr.size() - 1, __sz - 1 - __i);
                for (int __j = __nn; __j >= 1; --__j)
                  __arr[__j] = std::fma(__arr[__j], __x, __arr[__j - 1]);
                __arr[0] = std::fma(__arr[0], __x, this->coefficient(__i));
              }
            // Now put in the factorials.
            value_type __fact = value_type(1);
            for (size_type __n = __arr.size(), __i = 2; __i < __n; ++__i)
              {
                __fact *= value_type(__i);
                __arr[__i] *= __fact;
              }
          }
      }
eval() [2/4]
template<typename _Tp>
template<typename OutIter>
void __gnu_cxx::_Polynomial< _Tp >::eval (typename _Polynomial< _Tp >::value_type __x, OutIter __b, OutIter __e)
Evaluate the polynomial and its derivatives at the point x. The values are placed in the output range starting with the polynomial value and continuing through higher derivatives.
Definition at line 220 of file polynomial.tcc.
      {
        if(__b != __e)
          {
            std::fill(__b, __e, value_type{});
            const size_type __sz = _M_coeff.size();
            *__b = _M_coeff[__sz - 1];
            for (int __i = __sz - 2; __i >= 0; --__i)
              {
                for (auto __it = std::reverse_iterator<OutIter>(__e);
                     __it != std::reverse_iterator<OutIter>(__b) - 1; ++__it)
                  *__it = std::fma(*__it, __x, *(__it + 1));
                *__b = std::fma(*__b, __x, _M_coeff[__i]);
              }
            // Now put in the factorials.
            int __i = 0;
            value_type __fact = value_type(++__i);
            for (auto __it = __b + 1; __it != __e; ++__it)
              {
                __fact *= value_type(__i);
                *__it *= __fact;
                ++__i;
              }
          }
      }
eval() [3/4]
template<typename _Tp>
template<size_type N>
void __gnu_cxx::_Polynomial< _Tp >::eval (value_type __x, std::array< value_type, N > & __arr)
eval() [4/4]
template<typename _Tp>
template<typename OutIter >
void __gnu_cxx::_Polynomial< _Tp >::eval (value_type __x, OutIter __b, OutIter __e)
Evaluate the polynomial and its derivatives at the point x. The values are placed in the output range starting with the polynomial value and continuing through higher derivatives.
eval_even() [1/3]
template<typename _Tp>
template<typename _Tp >
_Polynomial<_Tp>::value_type __gnu_cxx::_Polynomial< _Tp >::eval_even (typename _Polynomial< _Tp >::value_type __x) const
Evaluate the even part of the polynomial at the input point.
Definition at line 252 of file polynomial.tcc.
    {
      if (this->degree() > 0)
        {
          const auto __odd = this->degree() % 2;
          const auto __xx = __x * __x;
          auto __poly(this->coefficient(this->degree() - __odd));
          for (int __i = this->degree() - __odd - 2; __i >= 0; __i -= 2)
            __poly = std::fma(__xx, __poly, this->coefficient(__i));
          return __poly;
        }
      else
        return value_type{};
    }
eval_even() [2/3]
template<typename _Tp>
value_type __gnu_cxx::_Polynomial< _Tp >::eval_even (value_type __x) const
Evaluate the even part of the polynomial at the input point.
Referenced by __gnu_cxx::_Polynomial< value_type >::eval_odd().
eval_even() [3/3]
template<typename _Tp>
template<typename _Up >
auto __gnu_cxx::_Polynomial< _Tp >::eval_even (const std::complex< _Up > & __z) const -> std::enable_if_t<!__has_imag_v<_Tp>,
			    std::complex<std::decay_t<
		decltype(typename _Polynomial<_Tp>::value_type [inline]
Evaluate the even part of the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 403 of file polynomial.h.
                                                            {} * _Up{})>>>;
eval_odd() [1/3]
template<typename _Tp>
template<typename _Tp >
_Polynomial<_Tp>::value_type __gnu_cxx::_Polynomial< _Tp >::eval_odd (typename _Polynomial< _Tp >::value_type __x) const
Evaluate the odd part of the polynomial at the input point.
Definition at line 272 of file polynomial.tcc.
    {
      if (this->degree() > 0)
        {
          const auto __even = (this->degree() % 2 == 0 ? 1 : 0);
          const auto __xx = __x * __x;
          auto __poly(this->coefficient(this->degree() - __even));
          for (int __i = this->degree() - __even - 2; __i >= 0; __i -= 2)
            __poly = std::fma(__xx, __poly, this->coefficient(__i));
          return __x * __poly;
        }
      else
        return value_type{};
    }
eval_odd() [2/3]
template<typename _Tp>
value_type __gnu_cxx::_Polynomial< _Tp >::eval_odd (value_type __x) const
Evaluate the odd part of the polynomial at the input point.
Referenced by __gnu_cxx::_Polynomial< value_type >::eval_odd().
eval_odd() [3/3]
template<typename _Tp>
template<typename _Up >
auto __gnu_cxx::_Polynomial< _Tp >::eval_odd (const std::complex< _Up > & __z) const -> std::enable_if_t<!__has_imag_v<_Tp>,
			std::complex<std::decay_t<
		decltype(typename _Polynomial<_Tp>::value_type [inline]
Evaluate the odd part of the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 422 of file polynomial.h.
                                                            {} * _Up{})>>>;
integral()
template<typename _Tp>
_Polynomial __gnu_cxx::_Polynomial< _Tp >::integral (value_type __c = value_type{}) const [inline]
Return the integral polynomial with given integration constant.
Definition at line 444 of file polynomial.h.
                                          {}) const
      {
        _Polynomial __res(value_type{}, this->degree() + 1);
        __res._M_coeff[0] = __c;
        for (size_type __n = this->degree(), __i = 0; __i <= __n; ++__i)
          __res._M_coeff[__i + 1] = this->_M_coeff[__i] / value_type(__i + 1);
        return __res;
      }
operator%=() [1/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator%= (const _Up &) [inline]
Take the modulus of the polynomial relative to a scalar. The result is always a zero polunomial.
Definition at line 559 of file polynomial.h.
        {
          this->degree(0UL); // Resize.
          this->_M_coeff[0] = value_type{};
          return *this;
        }
operator%=() [2/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator%= (const _Polynomial< _Up > & __poly) [inline]
Take the modulus of (modulate?) the polynomial relative to another polynomial.
Definition at line 618 of file polynomial.h.
        {
          _Polynomial<value_type >__quo, __rem;
          divmod(*this, __poly, __quo, __rem);
          *this = __rem;
          return *this;
        }
operator()() [1/4]
template<typename _Tp>
template<typename _Up >
auto __gnu_cxx::_Polynomial< _Tp >::operator() (const std::complex< _Up > & __z) const -> std::enable_if_t<!__has_imag_v<_Tp>,
			  std::complex<std::decay_t<
		decltype(typename _Polynomial<_Tp>::value_type
OTOH, What does it mean to get roots of integer polynomials - the roots will often be real or even complex.
What does it even mean to get roots of polynomial polynomials. I think you'd want to pick a parameter for the inner coefficient polynomials.
Wait! This has nothing to do with the coefficient type. It's the evaluation type that determines this. It may be sane to make real_type be double if it comes in as integral.
OTOOH, scaling down an integer polynomial will either screw up the polynomial or it will make a polynomial of a different type.
This scaling thing can only apply to real or complex polynomials.
template<typename _Tp> std::enable_if_t<std::is_integral_v<_Tp>> _Polynomial<_Tp>::_M_set_scale() { }
template<typename _Tp> std::enable_if_t<std::is_floating_point_v<_Tp>> void _Polynomial<_Tp>::_M_set_scale() { constexpr real_type _S_eps = std::numeric_limits<real_type>::epsilon(); constexpr real_type _S_base = real_type{std::numeric_limits<real_type>::radix}; constexpr real_type _S_tiny = _S_eps * _S_eps * _S_eps; // ~ 1.0e-50; constexpr real_type _S_huge = std::numeric_limits<real_type>::max(); constexpr real_type _S_low = _S_tiny / _S_eps;
Find largest and smallest moduli of coefficients. auto __a_max = real_type{0}; auto __a_min = _S_huge; for (int __i = 0; __i <= this->degree(); ++__i) { const auto __x = get_scale(this->_M_coeff[__i]); if (__x > __a_max) __a_max = __x; if (__x != real_type{0} && __x < __a_min) __a_min = __x; } Scale if there are large or very tiny coefficients. Computes a scale factor to multiply the coefficients of the polynomial. The scaling is done to avoid overflow and to avoid undetected underflow interfering with the convergence criterion. The factor is a power of the base. auto __scale = _S_low / __a_min; bool __rescale = true; if (__scale > real_type{1} && _S_huge / __scale < __a_max) __rescale = false; if (__scale <= real_type{1} && __a_max < real_type{10}) __rescale = false;
this->_M_scale = real_type{1}; if (__rescale) { Scale polynomial. if (__scale == real_type{0}) __scale = _S_tiny; const auto __lg = std::ilogb(__scale); this->_M_scale = std::pow(_S_base, __lg); if (this->_M_scale != real_type{1}) for (int __i = 0; __i <= this->degree(); ++__i) this->_M_coeff[__i] *= this->_M_scale; } } Scaling specialization for polynomial coefficient polynomials. template<typename _Tp> void _Polynomial<_Polynomial<_Tp>>::_M_set_scale() { for (int __i = 0; __i <= this->degree(); ++__i) this->_M_coeff[__i]._M_set_scale(); } Evaluate the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 162 of file polynomial.tcc.
                                                            {} * _Up{})>>>
operator()() [2/4]
template<typename _Tp>
value_type __gnu_cxx::_Polynomial< _Tp >::operator() (value_type __x) const [inline]
Evaluate the polynomial at the input point.
Definition at line 271 of file polynomial.h.
      {
        if (this->degree() > 0)
          {
            if (std::abs(__x) <= real_type{1})
              {
                value_type __poly(this->coefficient(this->
      degree()));
                for (int __i = this->degree() - 1; __i >= 0; --__i)
                  __poly = __poly * __x + this->coefficient(__i);
                return __poly;
              }
            else
              {
                const auto __rx = real_type{1} / __x;
                value_type __poly(this->coefficient(0));
                for (int __i = 1; __i <= this->degree(); ++__i)
                  __poly = __poly * __rx + this->coefficient(__i);
                for (int __i = 1; __i <= this->degree(); ++__i)
                  __poly *= __x;
                return __poly;
              }
          }
        else
          return this->coefficient(0);
      }
operator()() [3/4]
template<typename _Tp>
template<typename _Up >
auto __gnu_cxx::_Polynomial< _Tp >::operator() (_Up __x) const -> decltype(value_type [inline]
Evaluate the polynomial at the input point.
Definition at line 302 of file polynomial.h.
                              {} * _Up{})
operator()() [4/4]
template<typename _Tp>
template<typename InIter , typename OutIter , typename = std::_RequireInputIter<InIter>>
OutIter __gnu_cxx::_Polynomial< _Tp >::operator() (const InIter & __xbegin, const InIter & __xend, OutIter & __pbegin) const [inline]
Evaluate the polynomial at a range of input points. The output is written to the output iterator which must be large enough to contain the results. The next available output iterator is returned.
Definition at line 356 of file polynomial.h.
        {
          for (; __xbegin != __xend; ++__xbegin)
            __pbegin++ = (*this)(__xbegin++);
          return __pbegin;
        }
operator*=() [1/3]
template<typename _Tp>
template<typename _Up >
_Polynomial<_Tp>& __gnu_cxx::_Polynomial< _Tp >::operator*= (const _Polynomial< _Up > & __poly)
Multiply the polynomial by another polynomial.
Definition at line 374 of file polynomial.tcc.
      {
        // Test for zero size polys and do special processing?
        const size_type __m = this->degree();
        const size_type __n = __poly.degree();
        std::vector<value_type> __new_coeff(__m + __n + 1);
        for (size_type __i = 0; __i <= __m; ++__i)
          for (size_type __j = 0; __j <= __n; ++__j)
            __new_coeff[__i + __j] += this->_M_coeff[__i]
                                * static_cast<value_type>(__poly._M_coeff[__j]);
        this->_M_coeff = __new_coeff;
        return *this;
      }
operator*=() [2/3]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator*= (const _Up & __c) [inline]
Multiply the polynomial by a scalar.
Definition at line 534 of file polynomial.h.
        {
          for (size_type __i = 0; __i < this->_M_coeff.size(); ++__i)
            this->_M_coeff[__i] *= static_cast<value_type>(__c);
          return *this;
        }
operator*=() [3/3]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator*= (const _Polynomial< _Up > & __poly)
Multiply the polynomial by another polynomial.
operator+()
template<typename _Tp>
_Polynomial __gnu_cxx::_Polynomial< _Tp >::operator+ () const [inline], [noexcept]
Unary plus.
Definition at line 457 of file polynomial.h.
      { return *this; }
operator+=() [1/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator+= (const _Up & __x) [inline]
Add a scalar to the polynomial.
Definition at line 512 of file polynomial.h.
        {
          this->_M_coeff[0] += static_cast<value_type>(__x);
          return *this;
        }
operator+=() [2/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator+= (const _Polynomial< _Up > & __poly) [inline]
Add another polynomial to the polynomial.
Definition at line 571 of file polynomial.h.
        {
          this->degree(std::max(this->degree(), __poly.degree()));
          for (size_type __n = __poly.degree(), __i = 0; __i <= __n; ++__i)
            this->_M_coeff[__i] += static_cast<value_type>(__poly._M_coeff[__i]);
          return *this;
        }
operator-()
template<typename _Tp>
_Polynomial __gnu_cxx::_Polynomial< _Tp >::operator- () const [inline]
Unary minus.
Definition at line 464 of file polynomial.h.
      { return _Polynomial(*this) *= value_type(-1); }
operator-=() [1/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator-= (const _Up & __x) [inline]
Subtract a scalar from the polynomial.
Definition at line 523 of file polynomial.h.
        {
          this->_M_coeff[0] -= static_cast<value_type>(__x);
          return *this;
        }
operator-=() [2/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator-= (const _Polynomial< _Up > & __poly) [inline]
Subtract another polynomial from the polynomial.
Definition at line 584 of file polynomial.h.
        {
          // Resize if necessary.
          this->degree(std::max(this->degree(), __poly.degree()));
          for (size_type __n = __poly.degree(), __i = 0; __i <= __n; ++__i)
            this->_M_coeff[__i] -= static_cast<value_type>(__poly._M_coeff[__i]);
          return *this;
        }
operator/=() [1/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator/= (const _Up & __c) [inline]
Divide the polynomial by a scalar.
Definition at line 546 of file polynomial.h.
        {
          for (size_type __i = 0; __i < this->_M_coeff.size(); ++__i)
            this->_M_coeff[__i] /= static_cast<value_type>(__c);
          return *this;
        }
operator/=() [2/2]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator/= (const _Polynomial< _Up > & __poly) [inline]
Divide the polynomial by another polynomial.
Definition at line 605 of file polynomial.h.
        {
          _Polynomial<value_type >__quo, __rem;
          divmod(*this, __poly, __quo, __rem);
          *this = __quo;
          return *this;
        }
operator=() [1/4]
template<typename _Tp>
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator= (const value_type & __x) [inline]
Assign from a scalar. The result is a zero degree polynomial equal to the scalar.
Definition at line 472 of file polynomial.h.
      {
        this->_M_coeff = {__x};
        return *this;
      }
operator=() [2/4]
template<typename _Tp>
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator= (const _Polynomial< _Tp > &) [default]
Copy assignment.
operator=() [3/4]
template<typename _Tp>
template<typename _Up >
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator= (const _Polynomial< _Up > & __poly) [inline]
Definition at line 486 of file polynomial.h.
        {
          if (&__poly != this)
            {
              this->_M_coeff.clear();
              for (const auto __c : __poly)
                this->_M_coeff.push_back(static_cast<value_type>(__c));
              return *this;
            }
        }
operator=() [4/4]
template<typename _Tp>
_Polynomial& __gnu_cxx::_Polynomial< _Tp >::operator= (std::initializer_list< value_type > __ila) [inline]
Assign from an initialiser list.
Definition at line 501 of file polynomial.h.
      {
        this->_M_coeff = __ila;
        return *this;
      }
operator[]() [1/2]
template<typename _Tp>
value_type __gnu_cxx::_Polynomial< _Tp >::operator[] (size_type __i) const [inline], [noexcept]
Return coefficient i.
Definition at line 665 of file polynomial.h.
      { return this->_M_coeff[__i]; }
operator[]() [2/2]
template<typename _Tp>
reference __gnu_cxx::_Polynomial< _Tp >::operator[] (size_type __i) [inline], [noexcept]
Return coefficient i as an assignable quantity.
Definition at line 672 of file polynomial.h.
      { return this->_M_coeff[__i]; }
rbegin() [1/2]
template<typename _Tp>
reverse_iterator __gnu_cxx::_Polynomial< _Tp >::rbegin () [inline], [noexcept]
Definition at line 750 of file polynomial.h.
      { return this->_M_coeff.rbegin(); }
rbegin() [2/2]
template<typename _Tp>
const_reverse_iterator __gnu_cxx::_Polynomial< _Tp >::rbegin () const [inline], [noexcept]
Definition at line 758 of file polynomial.h.
      { return this->_M_coeff.rbegin(); }
rend() [1/2]
template<typename _Tp>
reverse_iterator __gnu_cxx::_Polynomial< _Tp >::rend () [inline], [noexcept]
Definition at line 754 of file polynomial.h.
      { return this->_M_coeff.rend(); }
rend() [2/2]
template<typename _Tp>
const_reverse_iterator __gnu_cxx::_Polynomial< _Tp >::rend () const [inline], [noexcept]
Definition at line 762 of file polynomial.h.
      { return this->_M_coeff.rend(); }
size()
template<typename _Tp>
size_type __gnu_cxx::_Polynomial< _Tp >::size () const [inline], [noexcept]
Return the size of the coefficient sequence.
Definition at line 644 of file polynomial.h.
Referenced by __gnu_cxx::operator>>().
      { return this->_M_coeff.size(); }
swap()
template<typename _Tp>
void __gnu_cxx::_Polynomial< _Tp >::swap (_Polynomial< _Tp > & __poly) [inline], [noexcept]
Swap the polynomial with another polynomial.
Definition at line 264 of file polynomial.h.
      { this->_M_coeff.swap(__poly._M_coeff); }
Friends And Related Function Documentation
operator==
template<typename _Tp>
template<typename _Tp1 >
bool operator== (const _Polynomial< _Tp1 > & __pa, const _Polynomial< _Tp1 > & __pb) [friend]
operator>>
template<typename _Tp>
template<typename CharT , typename Traits , typename _Tp1 >
std::basic_istream<CharT, Traits>& operator>> (std::basic_istream< CharT, Traits > & , _Polynomial< _Tp1 > &) [friend]
Member Data Documentation
_Up
template<typename _Tp>
* __gnu_cxx::_Polynomial< _Tp >::_Up
Definition at line 303 of file polynomial.h.
The documentation for this class was generated from the following files:
include/ext/polynomial.h
include/ext/polynomial.tcc