emsr::RationalPolynomial< Tp > Class Template Reference
#include <rational_polynomial.h>
Public Types
using difference_type = typename polynomial_type::difference_type
using polynomial_type = Polynomial< Tp >
using size_type = typename polynomial_type::size_type
using value_type = typename polynomial_type::value_type
Public Member Functions
RationalPolynomial ()
RationalPolynomial (const Polynomial< Tp > &num)
RationalPolynomial (const Polynomial< Tp > &num, const Polynomial< Tp > &den)
RationalPolynomial (const RationalPolynomial &)=default
RationalPolynomial (RationalPolynomial &&)=default
Polynomial< value_type > & denom ()
const Polynomial< value_type > & denom () const
Polynomial< value_type > & numer ()
const Polynomial< value_type > & numer () const
value_type operator() (value_type x) const
RationalPolynomial & operator*= (const RationalPolynomial &x)
RationalPolynomial operator+ () const
RationalPolynomial & operator+= (const RationalPolynomial &x)
RationalPolynomial operator- () const
RationalPolynomial & operator-= (const RationalPolynomial &x)
RationalPolynomial & operator/= (const RationalPolynomial &x)
RationalPolynomial & operator= (const RationalPolynomial &)=default
RationalPolynomial & operator= (RationalPolynomial &&)=default
Detailed Description
template<typename Tp>
class emsr::RationalPolynomial< Tp >
Definition at line 50 of file rational_polynomial.h.
Member Typedef Documentation
difference_type
template<typename Tp >
using emsr::RationalPolynomial< Tp >::difference_type = typename polynomial_type::difference_type
Definition at line 70 of file rational_polynomial.h.
polynomial_type
template<typename Tp >
using emsr::RationalPolynomial< Tp >::polynomial_type = Polynomial<Tp>
Typedefs.
Definition at line 56 of file rational_polynomial.h.
size_type
template<typename Tp >
using emsr::RationalPolynomial< Tp >::size_type = typename polynomial_type::size_type
Definition at line 69 of file rational_polynomial.h.
value_type
template<typename Tp >
using emsr::RationalPolynomial< Tp >::value_type = typename polynomial_type::value_type
Definition at line 57 of file rational_polynomial.h.
Constructor & Destructor Documentation
RationalPolynomial() [1/5]
template<typename Tp >
emsr::RationalPolynomial< Tp >::RationalPolynomial () [inline]
Create a zero degree polynomial with value zero.
Definition at line 75 of file rational_polynomial.h.
      : m_num(), m_den()
      { }
Referenced by emsr::RationalPolynomial< Tp >::operator-().
RationalPolynomial() [2/5]
template<typename Tp >
emsr::RationalPolynomial< Tp >::RationalPolynomial (const RationalPolynomial< Tp > &) [default]
Copy ctor.
RationalPolynomial() [3/5]
template<typename Tp >
emsr::RationalPolynomial< Tp >::RationalPolynomial (RationalPolynomial< Tp > &&) [default]
Move ctor.
RationalPolynomial() [4/5]
template<typename Tp >
emsr::RationalPolynomial< Tp >::RationalPolynomial (const Polynomial< Tp > & num, const Polynomial< Tp > & den) [inline]
Definition at line 89 of file rational_polynomial.h.
      : m_num(num), m_den(den)
      { }
RationalPolynomial() [5/5]
template<typename Tp >
emsr::RationalPolynomial< Tp >::RationalPolynomial (const Polynomial< Tp > & num) [inline], [explicit]
Definition at line 94 of file rational_polynomial.h.
      : m_num(num), m_den(Polynomial<Tp>(Tp{1}))
      { }
Member Function Documentation
denom() [1/2]
template<typename Tp >
Polynomial<value_type>& emsr::RationalPolynomial< Tp >::denom () [inline]
Definition at line 188 of file rational_polynomial.h.
      { return this->m_den; }
denom() [2/2]
template<typename Tp >
const Polynomial<value_type>& emsr::RationalPolynomial< Tp >::denom () const [inline]
Definition at line 184 of file rational_polynomial.h.
      { return this->m_den; }
Referenced by emsr::RationalPolynomial< Tp >::operator*=(), emsr::RationalPolynomial< Tp >::operator+=(), emsr::RationalPolynomial< Tp >::operator-=(), emsr::RationalPolynomial< Tp >::operator/=(), and emsr::operator>>().
numer() [1/2]
template<typename Tp >
Polynomial<value_type>& emsr::RationalPolynomial< Tp >::numer () [inline]
Definition at line 180 of file rational_polynomial.h.
      { return this->m_num; }
numer() [2/2]
template<typename Tp >
const Polynomial<value_type>& emsr::RationalPolynomial< Tp >::numer () const [inline]
Definition at line 176 of file rational_polynomial.h.
      { return this->m_num; }
Referenced by emsr::RationalPolynomial< Tp >::operator*=(), emsr::RationalPolynomial< Tp >::operator+=(), emsr::RationalPolynomial< Tp >::operator-=(), emsr::RationalPolynomial< Tp >::operator/=(), and emsr::operator>>().
operator()()
template<typename Tp >
value_type emsr::RationalPolynomial< Tp >::operator() (value_type x) const [inline]
Evaluate the polynomial at the input point.
Definition at line 102 of file rational_polynomial.h.
      { return this->m_num(x) / this->m_den(x); }
operator*=()
template<typename Tp >
RationalPolynomial& emsr::RationalPolynomial< Tp >::operator*= (const RationalPolynomial< Tp > & x) [inline]
Multiply this rational polynomial by a rational polynomial.
Definition at line 157 of file rational_polynomial.h.
      {
        this->numer() *= x.numer();
        this->denom() *= x.denom();
        return *this;
      }
References emsr::RationalPolynomial< Tp >::denom(), and emsr::RationalPolynomial< Tp >::numer().
operator+()
template<typename Tp >
RationalPolynomial emsr::RationalPolynomial< Tp >::operator+ () const [inline]
Unary plus.
Definition at line 109 of file rational_polynomial.h.
      { return *this; }
operator+=()
template<typename Tp >
RationalPolynomial& emsr::RationalPolynomial< Tp >::operator+= (const RationalPolynomial< Tp > & x) [inline]
Add a rational polynomial to this rational polynomial.
Definition at line 135 of file rational_polynomial.h.
      {
        this->numer() = this->numer() * x.denom() + this->denom() * x.numer();
        this->denom() *= x.denom();
        return *this;
      }
References emsr::RationalPolynomial< Tp >::denom(), and emsr::RationalPolynomial< Tp >::numer().
operator-()
template<typename Tp >
RationalPolynomial emsr::RationalPolynomial< Tp >::operator- () const [inline]
Unary minus.
Definition at line 116 of file rational_polynomial.h.
      { return RationalPolynomial(*this) *= value_type(-1); }
References emsr::RationalPolynomial< Tp >::RationalPolynomial().
operator-=()
template<typename Tp >
RationalPolynomial& emsr::RationalPolynomial< Tp >::operator-= (const RationalPolynomial< Tp > & x) [inline]
Subtract a rational polynomial from this rational polynomial.
Definition at line 146 of file rational_polynomial.h.
      {
        this->numer() = this->numer() * x.denom() - this->denom() * x.numer();
        this->denom() *= x.denom();
        return *this;
      }
References emsr::RationalPolynomial< Tp >::denom(), and emsr::RationalPolynomial< Tp >::numer().
operator/=()
template<typename Tp >
RationalPolynomial& emsr::RationalPolynomial< Tp >::operator/= (const RationalPolynomial< Tp > & x) [inline]
Divide this rational polynomial by a rational polynomial.
Definition at line 168 of file rational_polynomial.h.
      {
        this->numer() *= x.denom();
        this->denom() *= x.numer();
        return *this;
      }
References emsr::RationalPolynomial< Tp >::denom(), and emsr::RationalPolynomial< Tp >::numer().
operator=() [1/2]
template<typename Tp >
RationalPolynomial& emsr::RationalPolynomial< Tp >::operator= (const RationalPolynomial< Tp > &) [default]
Copy assignment.
operator=() [2/2]
template<typename Tp >
RationalPolynomial& emsr::RationalPolynomial< Tp >::operator= (RationalPolynomial< Tp > &&) [default]
Move assignment.
The documentation for this class was generated from the following file:
include/emsr/rational_polynomial.h