__gnu_cxx::_RationalPolynomial< _Tp > Class Template Reference
#include <rational_polynomial.h>
Public Types
using difference_type = typename polynomial_type::difference_type
using polynomial_type = _Polynomial< _Tp >
using size_type = typename polynomial_type::size_type
using value_type = typename polynomial_type::value_type
Public Member Functions
_RationalPolynomial ()
_RationalPolynomial (const _RationalPolynomial &)=default
_RationalPolynomial (_RationalPolynomial &&)=default
_RationalPolynomial (const _Polynomial< _Tp > &__num, const _Polynomial< _Tp > &__den)
_RationalPolynomial (const _Polynomial< _Tp > &__num)
const _Polynomial< value_type > & denom () const
_Polynomial< value_type > & denom ()
const _Polynomial< value_type > & numer () const
_Polynomial< value_type > & numer ()
value_type operator() (value_type __x) const
_RationalPolynomial & operator*= (const _RationalPolynomial &__x)
_RationalPolynomial operator+ () const
_RationalPolynomial & operator+= (const _RationalPolynomial &__x)
_RationalPolynomial operator- () const
_RationalPolynomial & operator-= (const _RationalPolynomial &__x)
_RationalPolynomial & operator/= (const _RationalPolynomial &__x)
_RationalPolynomial & operator= (const _RationalPolynomial &)=default
_RationalPolynomial & operator= (_RationalPolynomial &&)=default
Detailed Description
template<typename _Tp>
class __gnu_cxx::_RationalPolynomial< _Tp >
Definition at line 60 of file rational_polynomial.h.
Member Typedef Documentation
difference_type
template<typename _Tp>
using __gnu_cxx::_RationalPolynomial< _Tp >::difference_type = typename polynomial_type::difference_type
Definition at line 80 of file rational_polynomial.h.
polynomial_type
template<typename _Tp>
using __gnu_cxx::_RationalPolynomial< _Tp >::polynomial_type = _Polynomial<_Tp>
Typedefs.
Definition at line 66 of file rational_polynomial.h.
size_type
template<typename _Tp>
using __gnu_cxx::_RationalPolynomial< _Tp >::size_type = typename polynomial_type::size_type
Definition at line 79 of file rational_polynomial.h.
value_type
template<typename _Tp>
using __gnu_cxx::_RationalPolynomial< _Tp >::value_type = typename polynomial_type::value_type
Definition at line 67 of file rational_polynomial.h.
Constructor & Destructor Documentation
_RationalPolynomial() [1/5]
template<typename _Tp>
__gnu_cxx::_RationalPolynomial< _Tp >::_RationalPolynomial () [inline]
Create a zero degree polynomial with value zero.
Definition at line 85 of file rational_polynomial.h.
Referenced by __gnu_cxx::_RationalPolynomial< _Tp >::operator-().
      : _M_num(), _M_den()
      { }
_RationalPolynomial() [2/5]
template<typename _Tp>
__gnu_cxx::_RationalPolynomial< _Tp >::_RationalPolynomial (const _RationalPolynomial< _Tp > &) [default]
Copy ctor.
_RationalPolynomial() [3/5]
template<typename _Tp>
__gnu_cxx::_RationalPolynomial< _Tp >::_RationalPolynomial (_RationalPolynomial< _Tp > &&) [default]
Move ctor.
_RationalPolynomial() [4/5]
template<typename _Tp>
__gnu_cxx::_RationalPolynomial< _Tp >::_RationalPolynomial (const _Polynomial< _Tp > & __num, const _Polynomial< _Tp > & __den) [inline]
Definition at line 99 of file rational_polynomial.h.
      : _M_num(__num), _M_den(__den)
      { }
_RationalPolynomial() [5/5]
template<typename _Tp>
__gnu_cxx::_RationalPolynomial< _Tp >::_RationalPolynomial (const _Polynomial< _Tp > & __num) [inline], [explicit]
Definition at line 104 of file rational_polynomial.h.
      : _M_num(__num), _M_den(_Polynomial<_Tp>(_Tp{1}))
      { }
Member Function Documentation
denom() [1/2]
template<typename _Tp>
const _Polynomial<value_type>& __gnu_cxx::_RationalPolynomial< _Tp >::denom () const [inline]
Definition at line 194 of file rational_polynomial.h.
Referenced by __gnu_cxx::_RationalPolynomial< _Tp >::operator*=(), __gnu_cxx::_RationalPolynomial< _Tp >::operator+=(), __gnu_cxx::_RationalPolynomial< _Tp >::operator-=(), __gnu_cxx::_RationalPolynomial< _Tp >::operator/=(), and __gnu_cxx::operator>>().
      { return this->_M_den; }
denom() [2/2]
template<typename _Tp>
_Polynomial<value_type>& __gnu_cxx::_RationalPolynomial< _Tp >::denom () [inline]
Definition at line 198 of file rational_polynomial.h.
      { return this->_M_den; }
numer() [1/2]
template<typename _Tp>
const _Polynomial<value_type>& __gnu_cxx::_RationalPolynomial< _Tp >::numer () const [inline]
Definition at line 186 of file rational_polynomial.h.
Referenced by __gnu_cxx::_RationalPolynomial< _Tp >::operator*=(), __gnu_cxx::_RationalPolynomial< _Tp >::operator+=(), __gnu_cxx::_RationalPolynomial< _Tp >::operator-=(), __gnu_cxx::_RationalPolynomial< _Tp >::operator/=(), __gnu_cxx::operator<<(), and __gnu_cxx::operator>>().
      { return this->_M_num; }
numer() [2/2]
template<typename _Tp>
_Polynomial<value_type>& __gnu_cxx::_RationalPolynomial< _Tp >::numer () [inline]
Definition at line 190 of file rational_polynomial.h.
      { return this->_M_num; }
operator()()
template<typename _Tp>
value_type __gnu_cxx::_RationalPolynomial< _Tp >::operator() (value_type __x) const [inline]
Evaluate the polynomial at the input point.
Definition at line 112 of file rational_polynomial.h.
      { return this->_M_num(__x) / this->_M_den(__x); }
operator*=()
template<typename _Tp>
_RationalPolynomial& __gnu_cxx::_RationalPolynomial< _Tp >::operator*= (const _RationalPolynomial< _Tp > & __x) [inline]
Multiply this rational polynomial by a rational polynomial.
Definition at line 167 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::denom(), and __gnu_cxx::_RationalPolynomial< _Tp >::numer().
      {
        this->numer() *= __x.numer();
        this->denom() *= __x.denom();
        return *this;
      }
operator+()
template<typename _Tp>
_RationalPolynomial __gnu_cxx::_RationalPolynomial< _Tp >::operator+ () const [inline]
Unary plus.
Definition at line 119 of file rational_polynomial.h.
      { return *this; }
operator+=()
template<typename _Tp>
_RationalPolynomial& __gnu_cxx::_RationalPolynomial< _Tp >::operator+= (const _RationalPolynomial< _Tp > & __x) [inline]
Add a rational polynomial to this rational polynomial.
Definition at line 145 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::denom(), and __gnu_cxx::_RationalPolynomial< _Tp >::numer().
      {
        this->numer() = this->numer() * __x.denom() + this->denom() * __x.numer();
        this->denom() *= __x.denom();
        return *this;
      }
operator-()
template<typename _Tp>
_RationalPolynomial __gnu_cxx::_RationalPolynomial< _Tp >::operator- () const [inline]
Unary minus.
Definition at line 126 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::_RationalPolynomial(), and __gnu_cxx::_RationalPolynomial< _Tp >::operator=().
      { return _RationalPolynomial(*this) *= value_type(-1); }
operator-=()
template<typename _Tp>
_RationalPolynomial& __gnu_cxx::_RationalPolynomial< _Tp >::operator-= (const _RationalPolynomial< _Tp > & __x) [inline]
Subtract a rational polynomial from this rational polynomial.
Definition at line 156 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::denom(), and __gnu_cxx::_RationalPolynomial< _Tp >::numer().
      {
        this->numer() = this->numer() * __x.denom() - this->denom() * __x.numer();
        this->denom() *= __x.denom();
        return *this;
      }
operator/=()
template<typename _Tp>
_RationalPolynomial& __gnu_cxx::_RationalPolynomial< _Tp >::operator/= (const _RationalPolynomial< _Tp > & __x) [inline]
Divide this rational polynomial by a rational polynomial.
Definition at line 178 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::denom(), and __gnu_cxx::_RationalPolynomial< _Tp >::numer().
      {
        this->numer() *= __x.denom();
        this->denom() *= __x.numer();
        return *this;
      }
operator=() [1/2]
template<typename _Tp>
_RationalPolynomial& __gnu_cxx::_RationalPolynomial< _Tp >::operator= (const _RationalPolynomial< _Tp > &) [default]
Copy assignment.
Referenced by __gnu_cxx::_RationalPolynomial< _Tp >::operator-().
operator=() [2/2]
template<typename _Tp>
_RationalPolynomial& __gnu_cxx::_RationalPolynomial< _Tp >::operator= (_RationalPolynomial< _Tp > &&) [default]
Move assignment.
The documentation for this class was generated from the following file:
include/ext/rational_polynomial.h