emsr::Polynomial< Tp > Class Template Reference
A dense polynomial class with a contiguous array of coefficients. The coefficients are lowest-order first:
#include <polynomial.h>
Public Types
using const_iterator = typename std::vector< value_type >::const_iterator
using const_pointer = typename std::vector< value_type >::const_pointer
using const_reference = typename std::vector< value_type >::const_reference
using const_reverse_iterator = typename std::vector< value_type >::const_reverse_iterator
using difference_type = typename std::vector< value_type >::difference_type
using iterator = typename std::vector< value_type >::iterator
using pointer = typename std::vector< value_type >::pointer
using real_type = real_type_t< Tp >
using reference = typename std::vector< value_type >::reference
using reverse_iterator = typename std::vector< value_type >::reverse_iterator
using size_type = typename std::vector< value_type >::size_type
using value_type = typename std::vector< Tp >::value_type
Public Member Functions
Polynomial ()
template<typename InIter , typename = std::_RequireInputIter<InIter>>
Polynomial (const InIter &abegin, const InIter &aend)
template<typename InIter , typename = std::_RequireInputIter<InIter>>
Polynomial (const InIter &xbegin, const InIter &xend, const InIter &ybegin)
Polynomial (const Polynomial &)=default
template<typename Up >
Polynomial (const Polynomial< Up > &poly)
template<typename Gen >
Polynomial (Gen gen, size_type degree)
Polynomial (Polynomial &&) noexcept=default
Polynomial (std::initializer_list< value_type > ila)
Polynomial (value_type a, size_type degree=0)
const_iterator begin () const noexcept
iterator begin () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
value_type coefficient (size_type i) const
void coefficient (size_type i, value_type val)
const std::vector< value_type > coefficients () const noexcept
std::vector< value_type > coefficients () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
const value_type * data () const noexcept
value_type * data () noexcept
Polynomial & deflate (const Polynomial< value_type > &poly, real_type max_abs_coef)
Polynomial & deflate (real_type max_abs_coef)
size_type degree () const noexcept
void degree (size_type degree)
Polynomial derivative () const
const_iterator end () const noexcept
iterator end () noexcept
template<typename OutIter >
void eval (typename Polynomial< Tp >::value_type x, OutIter b, OutIter e)
template<typename Polynomial< Tp >::size_type N>
void eval (typename Polynomial< Tp >::value_type x, std::array< Polynomial< Tp >::value_type, N > &arr)
template<typename OutIter >
void eval (value_type x, OutIter b, OutIter e)
template<size_type N>
void eval (value_type x, std::array< value_type, N > &arr)
template<typename Up >
auto eval_even (const std::complex< Up > &z) const -> std::enable_if_t<!has_imag_v< Tp >, std::complex< std::decay_t< decltype(typename Polynomial< Tp >::value_type{} *Up{})>>>
template<typename Tp >
Polynomial< Tp >::value_type eval_even (typename Polynomial< Tp >::value_type x) const
value_type eval_even (value_type x) const
template<typename Up >
auto eval_odd (const std::complex< Up > &z) const -> std::enable_if_t<!has_imag_v< Tp >, std::complex< std::decay_t< decltype(typename Polynomial< Tp >::value_type{} *Up{})>>>
template<typename Tp >
Polynomial< Tp >::value_type eval_odd (typename Polynomial< Tp >::value_type x) const
value_type eval_odd (value_type x) const
Polynomial integral (value_type c=value_type{}) const
template<typename Up >
Polynomial & operator%= (const Polynomial< Up > &poly)
template<typename Up >
Polynomial & operator%= (const Up &)
template<typename InIter , typename OutIter , typename = std::_RequireInputIter<InIter>>
OutIter operator() (const InIter &xbegin, const InIter &xend, OutIter &pbegin) const
template<typename Up >
auto operator() (const std::complex< Up > &z) const -> std::enable_if_t<!has_imag_v< Tp >, std::complex< std::decay_t< decltype(typename Polynomial< Tp >::value_type{} *Up{})>>>
template<typename Up >
auto operator() (Up x) const -> decltype(value_type{} *Up{})
value_type operator() (value_type x) const
template<typename Up >
Polynomial & operator*= (const Polynomial< Up > &poly)
template<typename Up >
Polynomial< Tp > & operator*= (const Polynomial< Up > &poly)
template<typename Up >
Polynomial & operator*= (const Up &c)
Polynomial operator+ () const noexcept
template<typename Up >
Polynomial & operator+= (const Polynomial< Up > &poly)
template<typename Up >
Polynomial & operator+= (const Up &x)
Polynomial operator- () const
template<typename Up >
Polynomial & operator-= (const Polynomial< Up > &poly)
template<typename Up >
Polynomial & operator-= (const Up &x)
template<typename Up >
Polynomial & operator/= (const Polynomial< Up > &poly)
template<typename Up >
Polynomial & operator/= (const Up &c)
Polynomial & operator= (const Polynomial &)=default
template<typename Up >
Polynomial & operator= (const Polynomial< Up > &poly)
Polynomial & operator= (const value_type &x)
Polynomial & operator= (std::initializer_list< value_type > ila)
value_type operator[] (size_type i) const noexcept
reference operator[] (size_type i) noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rend () const noexcept
reverse_iterator rend () noexcept
void shift (value_type shift)
size_type size () const noexcept
void swap (Polynomial &poly) noexcept
Public Attributes
template<typename Up >
decltype(Up{} *value_type{} derivative)(Up c) const
template<typename Up >
decltype(Up{} *value_type{} integral)(Up a, Up b) const
Friends
template<typename Tp1 >
bool operator== (const Polynomial< Tp1 > &pa, const Polynomial< Tp1 > &pb)
template<typename CharT , typename Traits , typename Tp1 >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &, Polynomial< Tp1 > &)
Detailed Description
template<typename Tp>
class emsr::Polynomial< Tp >
A dense polynomial class with a contiguous array of coefficients. The coefficients are lowest-order first:
 P(x) = a_0 + a_1 x + ... + a_n x^n 
Definition at line 136 of file polynomial.h.
Member Typedef Documentation
const_iterator
template<typename Tp >
using emsr::Polynomial< Tp >::const_iterator = typename std::vector<value_type>::const_iterator
Definition at line 148 of file polynomial.h.
const_pointer
template<typename Tp >
using emsr::Polynomial< Tp >::const_pointer = typename std::vector<value_type>::const_pointer
Definition at line 146 of file polynomial.h.
const_reference
template<typename Tp >
using emsr::Polynomial< Tp >::const_reference = typename std::vector<value_type>::const_reference
Definition at line 144 of file polynomial.h.
const_reverse_iterator
template<typename Tp >
using emsr::Polynomial< Tp >::const_reverse_iterator = typename std::vector<value_type>::const_reverse_iterator
Definition at line 151 of file polynomial.h.
difference_type
template<typename Tp >
using emsr::Polynomial< Tp >::difference_type = typename std::vector<value_type>::difference_type
Definition at line 154 of file polynomial.h.
iterator
template<typename Tp >
using emsr::Polynomial< Tp >::iterator = typename std::vector<value_type>::iterator
Definition at line 147 of file polynomial.h.
pointer
template<typename Tp >
using emsr::Polynomial< Tp >::pointer = typename std::vector<value_type>::pointer
Definition at line 145 of file polynomial.h.
real_type
template<typename Tp >
using emsr::Polynomial< Tp >::real_type = real_type_t<Tp>
Definition at line 155 of file polynomial.h.
reference
template<typename Tp >
using emsr::Polynomial< Tp >::reference = typename std::vector<value_type>::reference
Definition at line 143 of file polynomial.h.
reverse_iterator
template<typename Tp >
using emsr::Polynomial< Tp >::reverse_iterator = typename std::vector<value_type>::reverse_iterator
Definition at line 149 of file polynomial.h.
size_type
template<typename Tp >
using emsr::Polynomial< Tp >::size_type = typename std::vector<value_type>::size_type
Definition at line 153 of file polynomial.h.
value_type
template<typename Tp >
using emsr::Polynomial< Tp >::value_type = typename std::vector<Tp>::value_type
Typedefs.
Definition at line 142 of file polynomial.h.
Constructor & Destructor Documentation
Polynomial() [1/9]
template<typename Tp >
emsr::Polynomial< Tp >::Polynomial () [inline]
Create a zero degree polynomial with coefficient value zero.
Definition at line 160 of file polynomial.h.
      : m_coeff(1)
      { }
Referenced by emsr::Polynomial< Tp >::operator-().
Polynomial() [2/9]
template<typename Tp >
emsr::Polynomial< Tp >::Polynomial (const Polynomial< Tp > &) [default]
Copy ctor.
Polynomial() [3/9]
template<typename Tp >
emsr::Polynomial< Tp >::Polynomial (Polynomial< Tp > &&) [default], [noexcept]
Move ctor.
Polynomial() [4/9]
template<typename Tp >
template<typename Up >
emsr::Polynomial< Tp >::Polynomial (const Polynomial< Up > & poly) [inline]
Definition at line 175 of file polynomial.h.
        : m_coeff{}
        {
          for (const auto c : poly)
            this->m_coeff.push_back(static_cast<value_type>(c));
          this->m_set_scale();
        }
Polynomial() [5/9]
template<typename Tp >
emsr::Polynomial< Tp >::Polynomial (value_type a, size_type degree = 0) [inline], [explicit]
Create a monomial.
Definition at line 187 of file polynomial.h.
      : m_coeff(degree + 1)
      { this->m_coeff[degree] = a; }
References emsr::Polynomial< Tp >::degree().
Polynomial() [6/9]
template<typename Tp >
emsr::Polynomial< Tp >::Polynomial (std::initializer_list< value_type > ila) [inline]
Create a polynomial from an initializer list of coefficients.
Definition at line 194 of file polynomial.h.
      : m_coeff(ila)
      { this->m_set_scale(); }
Polynomial() [7/9]
template<typename Tp >
template<typename InIter , typename = std::_RequireInputIter<InIter>>
emsr::Polynomial< Tp >::Polynomial (const InIter & abegin, const InIter & aend) [inline]
Create a polynomial from an input iterator range of coefficients.
Definition at line 203 of file polynomial.h.
        : m_coeff(abegin, aend)
        { this->m_set_scale(); }
Polynomial() [8/9]
template<typename Tp >
template<typename InIter , typename = std::_RequireInputIter<InIter>>
emsr::Polynomial< Tp >::Polynomial (const InIter & xbegin, const InIter & xend, const InIter & ybegin) [inline]
Use Lagrange interpolation to construct a polynomial passing through the data points. The degree will be one less than the number of points.
Definition at line 213 of file polynomial.h.
        : m_coeff()
        {
          std::vector<Polynomial<value_type>> numer;
          std::vector<Polynomial<value_type>> denom;
          for (auto xi = xbegin; xi != xend; ++xi)
            {
              for (auto xj = xi + 1; xj != xend; ++xj)
                denom.push_back(value_type(*xj) - value_type(*xi));
              numer.push_back({-value_type(*xi), value_type{1}});
            }
          this->m_set_scale();
        }
Polynomial() [9/9]
template<typename Tp >
template<typename Gen >
emsr::Polynomial< Tp >::Polynomial (Gen gen, size_type degree) [inline]
Create a polynomial from a generator and a maximum degree.
Definition at line 232 of file polynomial.h.
        : m_coeff()
        {
          this->m_coeff.reserve(degree + 1);
          for (size_type k = 0; k <= degree; ++k)
            this->m_coeff.push_back(gen(k));
          this->m_set_scale();
        }
References emsr::Polynomial< Tp >::degree().
Member Function Documentation
begin() [1/2]
template<typename Tp >
const_iterator emsr::Polynomial< Tp >::begin () const [inline], [noexcept]
Return a const iterator the beginning of the coefficient sequence.
Definition at line 763 of file polynomial.h.
      { return this->m_coeff.begin(); }
begin() [2/2]
template<typename Tp >
iterator emsr::Polynomial< Tp >::begin () [inline], [noexcept]
Return an iterator to the beginning of the coefficient sequence.
Definition at line 748 of file polynomial.h.
      { return this->m_coeff.begin(); }
cbegin()
template<typename Tp >
const_iterator emsr::Polynomial< Tp >::cbegin () const [inline], [noexcept]
Return a const iterator the beginning of the coefficient sequence.
Definition at line 779 of file polynomial.h.
      { return this->m_coeff.cbegin(); }
cend()
template<typename Tp >
const_iterator emsr::Polynomial< Tp >::cend () const [inline], [noexcept]
Return a const iterator to one past the end of the coefficient sequence.
Definition at line 787 of file polynomial.h.
      { return this->m_coeff.cend(); }
coefficient() [1/2]
template<typename Tp >
value_type emsr::Polynomial< Tp >::coefficient (size_type i) const [inline]
Return the ith coefficient with range checking.
Definition at line 692 of file polynomial.h.
      { return this->m_coeff.at(i); }
Referenced by emsr::divmod(), and emsr::Polynomial< Tp >::operator()().
coefficient() [2/2]
template<typename Tp >
void emsr::Polynomial< Tp >::coefficient (size_type i, value_type val) [inline]
Set coefficient i to val with range checking.
Definition at line 699 of file polynomial.h.
      { this->m_coeff.at(i) = val; }
coefficients() [1/2]
template<typename Tp >
const std::vector<value_type> emsr::Polynomial< Tp >::coefficients () const [inline], [noexcept]
Return a const vector of coefficients.
Definition at line 720 of file polynomial.h.
      { return this->m_coeff; }
coefficients() [2/2]
template<typename Tp >
std::vector<value_type> emsr::Polynomial< Tp >::coefficients () [inline], [noexcept]
Return a vector of coefficients.
Definition at line 727 of file polynomial.h.
      { return this->m_coeff; }
crbegin()
template<typename Tp >
const_reverse_iterator emsr::Polynomial< Tp >::crbegin () const [inline], [noexcept]
Definition at line 807 of file polynomial.h.
      { return this->m_coeff.crbegin(); }
crend()
template<typename Tp >
const_reverse_iterator emsr::Polynomial< Tp >::crend () const [inline], [noexcept]
Definition at line 811 of file polynomial.h.
      { return this->m_coeff.crend(); }
data() [1/2]
template<typename Tp >
const value_type* emsr::Polynomial< Tp >::data () const [inline], [noexcept]
Return a const pointer to the coefficient sequence.
Definition at line 734 of file polynomial.h.
      { return this->m_coeff.data(); }
data() [2/2]
template<typename Tp >
value_type* emsr::Polynomial< Tp >::data () [inline], [noexcept]
Return a pointer to the coefficient sequence.
Definition at line 741 of file polynomial.h.
      { return this->m_coeff.data(); }
deflate() [1/2]
template<typename Tp >
Polynomial& emsr::Polynomial< Tp >::deflate (const Polynomial< value_type > & poly, real_type max_abs_coef) [inline]
Divide the polynomial by an input polynomia and remove zero max-order coefficients.
Definition at line 844 of file polynomial.h.
      {
        Polynomial<value_type> quo, rem;
        divmod(*this, poly, quo, rem);
        // Remainder should be null.
        size_type n = rem.degree();
        for (size_type i = rem.degree(); i > 0; --i)
          if (std::abs(rem[i]) < max_abs_coef)
            --n;
          else
            break;
        if (n == 0)
          *this = quo.deflate(max_abs_coef);
        else
          throw std::runtime_error("deflate: ");
        return *this;
      }
References emsr::abs(), emsr::Polynomial< Tp >::deflate(), emsr::Polynomial< Tp >::degree(), and emsr::divmod().
deflate() [2/2]
template<typename Tp >
Polynomial& emsr::Polynomial< Tp >::deflate (real_type max_abs_coef) [inline]
Remove zero max-order coefficients.
Definition at line 827 of file polynomial.h.
      {
        size_type n = this->degree();
        for (size_type i = this->degree(); i > 0; --i)
          if (std::abs(this->m_coeff[i]) < max_abs_coef)
            --n;
          else
            break;
        this->degree(n);
        return *this;
      }
References emsr::abs(), and emsr::Polynomial< Tp >::degree().
Referenced by emsr::Polynomial< Tp >::deflate(), and emsr::QuadraticSolver< Real >::step().
degree() [1/2]
template<typename Tp >
size_type emsr::Polynomial< Tp >::degree () const [inline], [noexcept]
Return the degree or the power of the largest coefficient.
Definition at line 671 of file polynomial.h.
      { return this->m_coeff.size() - 1; }
Referenced by emsr::Polynomial< Tp >::Polynomial(), emsr::Polynomial< Tp >::deflate(), emsr::Polynomial< Tp >::degree(), emsr::Polynomial< Tp >::derivative(), emsr::divmod(), emsr::Polynomial< Tp >::operator%=(), emsr::Polynomial< Tp >::operator()(), emsr::Polynomial< Tp >::operator*=(), emsr::Polynomial< Tp >::operator+=(), emsr::Polynomial< Tp >::operator-=(), and emsr::Polynomial< Tp >::shift().
degree() [2/2]
template<typename Tp >
void emsr::Polynomial< Tp >::degree (size_type degree) [inline]
Set the degree or the power of the largest coefficient.
Definition at line 678 of file polynomial.h.
      { this->m_coeff.resize(degree + 1UL); }
References emsr::Polynomial< Tp >::degree().
derivative()
template<typename Tp >
Polynomial emsr::Polynomial< Tp >::derivative () const [inline]
Return the derivative polynomial.
Definition at line 412 of file polynomial.h.
      {
        Polynomial res(value_type{},
                          this->degree() > 0UL ? this->degree() - 1 : 0UL);
        for (size_type n = this->degree(), i = 1; i <= n; ++i)
          res.m_coeff[i - 1] = i * this->m_coeff[i];
        return res;
      }
References emsr::Polynomial< Tp >::degree().
end() [1/2]
template<typename Tp >
const_iterator emsr::Polynomial< Tp >::end () const [inline], [noexcept]
Return a const iterator to one past the end of the coefficient sequence.
Definition at line 771 of file polynomial.h.
      { return this->m_coeff.end(); }
end() [2/2]
template<typename Tp >
iterator emsr::Polynomial< Tp >::end () [inline], [noexcept]
Return an iterator to one past the end of the coefficient sequence.
Definition at line 755 of file polynomial.h.
      { return this->m_coeff.end(); }
eval() [1/4]
template<typename Tp >
template<typename OutIter >
void emsr::Polynomial< Tp >::eval (typename Polynomial< Tp >::value_type x, OutIter b, OutIter e)
Evaluate the polynomial and its derivatives at the point x. The values are placed in the output range starting with the polynomial value and continuing through higher derivatives.
Definition at line 212 of file polynomial.tcc.
      {
        if(b != e)
          {
            std::fill(b, e, value_type{});
            const size_type sz = m_coeff.size();
            *b = m_coeff[sz - 1];
            for (int i = sz - 2; i >= 0; --i)
              {
                for (auto it = std::reverse_iterator<OutIter>(e);
                     it != std::reverse_iterator<OutIter>(b) - 1; ++it)
                  *it = std::fma(*it, x, *(it + 1));
                *b = std::fma(*b, x, m_coeff[i]);
              }
            // Now put in the factorials.
            int i = 0;
            value_type fact = value_type(++i);
            for (auto it = b + 1; it != e; ++it)
              {
                fact *= value_type(i);
                *it *= fact;
                ++i;
              }
          }
      }
References emsr::fma().
eval() [2/4]
template<typename Tp >
template<typename Polynomial< Tp >::size_type N>
void emsr::Polynomial< Tp >::eval (typename Polynomial< Tp >::value_type x, std::array< Polynomial< Tp >::value_type, N > & arr)
Definition at line 179 of file polynomial.tcc.
      {
        if (arr.size() > 0)
          {
            arr.fill(value_type{});
            const size_type sz = m_coeff.size();
            arr[0] = this->coefficient(sz - 1);
            for (int i = sz - 2; i >= 0; --i)
              {
                int nn = std::min(arr.size() - 1, sz - 1 - i);
                for (int j = nn; j >= 1; --j)
                  arr[j] = std::fma(arr[j], x, arr[j - 1]);
                arr[0] = std::fma(arr[0], x, this->coefficient(i));
              }
            // Now put in the factorials.
            value_type fact = value_type(1);
            for (size_type n = arr.size(), i = 2; i < n; ++i)
              {
                fact *= value_type(i);
                arr[i] *= fact;
              }
          }
      }
References emsr::fma().
eval() [3/4]
template<typename Tp >
template<typename OutIter >
void emsr::Polynomial< Tp >::eval (value_type x, OutIter b, OutIter e)
Evaluate the polynomial and its derivatives at the point x. The values are placed in the output range starting with the polynomial value and continuing through higher derivatives.
eval() [4/4]
template<typename Tp >
template<size_type N>
void emsr::Polynomial< Tp >::eval (value_type x, std::array< value_type, N > & arr)
eval_even() [1/3]
template<typename Tp >
template<typename Up >
auto emsr::Polynomial< Tp >::eval_even (const std::complex< Up > & z) const -> std::enable_if_t<!has_imag_v<Tp>, std::complex<std::decay_t< decltype(typename Polynomial<Tp>::value_type{} * Up{})>>>
Evaluate the even part of the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 294 of file polynomial.tcc.
                                                          {} * Up{})>>>
      {
        using real_t = std::decay_t<decltype(value_type{} * Up{})>;
        using cmplx_t = std::complex<real_t>;
        if (this->degree() > 0)
          {
            const auto zz = z * z;
            const auto r = Tp{2} * std::real(zz);
            const auto s = std::norm(zz);
            auto odd = this->degree() % 2;
            size_type n = this->degree() - odd;
            auto aa = this->coefficient(n);
            auto bb = this->coefficient(n - 2);
            for (size_type j = 4; j <= n; j += 2)
              bb = std::fma(-s, std::exchange(aa, bb + r * aa),
                              this->coefficient(n - j));
            return std::fma(cmplx_t(aa), cmplx_t(zz), cmplx_t(bb));
          }
        else
          return cmplx_t{};
      };
eval_even() [2/3]
template<typename Tp >
template<typename Tp >
Polynomial<Tp>::value_type emsr::Polynomial< Tp >::eval_even (typename Polynomial< Tp >::value_type x) const
Evaluate the even part of the polynomial at the input point.
Definition at line 244 of file polynomial.tcc.
    {
      if (this->degree() > 0)
        {
          const auto odd = this->degree() % 2;
          const auto xx = x * x;
          auto poly(this->coefficient(this->degree() - odd));
          for (int i = this->degree() - odd - 2; i >= 0; i -= 2)
            poly = std::fma(xx, poly, this->coefficient(i));
          return poly;
        }
      else
        return value_type{};
    }
References emsr::fma().
eval_even() [3/3]
template<typename Tp >
value_type emsr::Polynomial< Tp >::eval_even (value_type x) const
Evaluate the even part of the polynomial at the input point.
eval_odd() [1/3]
template<typename Tp >
template<typename Up >
auto emsr::Polynomial< Tp >::eval_odd (const std::complex< Up > & z) const -> std::enable_if_t<!has_imag_v<Tp>, std::complex<std::decay_t< decltype(typename Polynomial<Tp>::value_type{} * Up{})>>>
Evaluate the odd part of the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 334 of file polynomial.tcc.
                                                          {} * Up{})>>>
      {
        using real_t = std::decay_t<decltype(value_type{} * Up{})>;
        using cmplx_t = std::complex<real_t>;
        if (this->degree() > 0)
          {
            const auto zz = z * z;
            const auto r = Tp{2} * std::real(zz);
            const auto s = std::norm(zz);
            auto even = (this->degree() % 2 == 0 ? 1 : 0);
            size_type n = this->degree() - even;
            auto aa = this->coefficient(n);
            auto bb = this->coefficient(n - 2);
            for (size_type j = 4; j <= n; j += 2)
              bb = std::fma(-s, std::exchange(aa, bb + r * aa),
                              this->coefficient(n - j));
            return z
                 * std::fma(cmplx_t(aa), cmplx_t(zz), cmplx_t(bb));
          }
        else
          return cmplx_t{};
      };
eval_odd() [2/3]
template<typename Tp >
template<typename Tp >
Polynomial<Tp>::value_type emsr::Polynomial< Tp >::eval_odd (typename Polynomial< Tp >::value_type x) const
Evaluate the odd part of the polynomial at the input point.
Definition at line 264 of file polynomial.tcc.
    {
      if (this->degree() > 0)
        {
          const auto even = (this->degree() % 2 == 0 ? 1 : 0);
          const auto xx = x * x;
          auto poly(this->coefficient(this->degree() - even));
          for (int i = this->degree() - even - 2; i >= 0; i -= 2)
            poly = std::fma(xx, poly, this->coefficient(i));
          return x * poly;
        }
      else
        return value_type{};
    }
References emsr::fma().
eval_odd() [3/3]
template<typename Tp >
value_type emsr::Polynomial< Tp >::eval_odd (value_type x) const
Evaluate the odd part of the polynomial at the input point.
integral()
template<typename Tp >
Polynomial emsr::Polynomial< Tp >::integral (value_type c = value_type{}) const [inline]
Return the integral polynomial with given integration constant.
Definition at line 440 of file polynomial.h.
                                        {}) const
      {
        Polynomial res(value_type{}, this->degree() + 1);
        res.m_coeff[0] = c;
        for (size_type n = this->degree(), i = 0; i <= n; ++i)
          res.m_coeff[i + 1] = this->m_coeff[i] / value_type(i + 1);
        return res;
      }
operator%=() [1/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator%= (const Polynomial< Up > & poly) [inline]
Take the modulus of (modulate?) the polynomial relative to another polynomial.
Definition at line 637 of file polynomial.h.
        {
          Polynomial<value_type >quo, rem;
          divmod(*this, poly, quo, rem);
          *this = rem;
          return *this;
        }
References emsr::divmod().
operator%=() [2/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator%= (const Up &) [inline]
Take the modulus of the polynomial relative to a scalar. The result is always a zero polunomial.
Definition at line 578 of file polynomial.h.
        {
          this->degree(0UL); // Resize.
          this->m_coeff[0] = value_type{};
          return *this;
        }
References emsr::Polynomial< Tp >::degree().
operator()() [1/4]
template<typename Tp >
template<typename InIter , typename OutIter , typename = std::_RequireInputIter<InIter>>
OutIter emsr::Polynomial< Tp >::operator() (const InIter & xbegin, const InIter & xend, OutIter & pbegin) const [inline]
Evaluate the polynomial at a range of input points. The output is written to the output iterator which must be large enough to contain the results. The next available output iterator is returned.
Definition at line 337 of file polynomial.h.
        {
          for (; xbegin != xend; ++xbegin)
            pbegin++ = (*this)(xbegin++);
          return pbegin;
        }
operator()() [2/4]
template<typename Tp >
template<typename Up >
auto emsr::Polynomial< Tp >::operator() (const std::complex< Up > & z) const -> std::enable_if_t<!has_imag_v<Tp>, std::complex<std::decay_t< decltype(typename Polynomial<Tp>::value_type{} * Up{})>>>
Evaluate the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
OTOH, What does it mean to get roots of integer polynomials - the roots will often be real or even complex.
What does it even mean to get roots of polynomial polynomials. I think you'd want to pick a parameter for the inner coefficient polynomials.
Wait! This has nothing to do with the coefficient type. It's the evaluation type that determines this. It may be sane to make real_type be double if it comes in as integral.
OTOOH, scaling down an integer polynomial will either screw up the polynomial or it will make a polynomial of a different type.
This scaling thing can only apply to real or complex polynomials.
template<typename Tp> std::enable_if_t<std::is_integral_v<Tp>> Polynomial<Tp>::m_set_scale() { }
template<typename Tp> std::enable_if_t<std::is_floating_point_v<Tp>> void Polynomial<Tp>::m_set_scale() { constexpr real_type s_eps = std::numeric_limits<real_type>::epsilon(); constexpr real_type s_base = real_type{std::numeric_limits<real_type>::radix}; constexpr real_type s_tiny = s_eps * s_eps * s_eps; // ~ 1.0e-50; constexpr real_type s_huge = std::numeric_limits<real_type>::max(); constexpr real_type s_low = s_tiny / s_eps;
Find largest and smallest moduli of coefficients. auto a_max = real_type{0}; auto a_min = s_huge; for (int i = 0; i <= this->degree(); ++i) { const auto x = get_scale(this->m_coeff[i]); if (x > a_max) a_max = x; if (x != real_type{0} && x < a_min) a_min = x; } Scale if there are large or very tiny coefficients. Computes a scale factor to multiply the coefficients of the polynomial. The scaling is done to avoid overflow and to avoid undetected underflow interfering with the convergence criterion. The factor is a power of the base. auto scale = s_low / a_min; bool rescale = true; if (scale > real_type{1} && s_huge / scale < a_max) rescale = false; if (scale <= real_type{1} && a_max < real_type{10}) rescale = false;
this->m_scale = real_type{1}; if (rescale) { Scale polynomial. if (scale == real_type{0}) scale = s_tiny; const auto lg = std::ilogb(scale); this->m_scale = std::pow(s_base, lg); if (this->m_scale != real_type{1}) for (int i = 0; i <= this->degree(); ++i) this->m_coeff[i] *= this->m_scale; } } Scaling specialization for polynomial coefficient polynomials. template<typename Tp> void Polynomial<Polynomial<Tp>>::m_set_scale() { for (int i = 0; i <= this->degree(); ++i) this->m_coeff[i].m_set_scale(); } Evaluate the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 154 of file polynomial.tcc.
                                                          {} * Up{})>>>
      {
        const auto r = Tp{2} * std::real(z);
        const auto s = std::norm(z);
        size_type n = this->degree();
        auto aa = this->coefficient(n);
        if (n > 0)
          {
            auto bb = this->coefficient(n - 1);
            for (size_type j = 2; j <= n; ++j)
              bb = this->coefficient(n - j)
                   - s * std::exchange(aa, bb + r * aa);
            return aa * z + bb;
          }
        else
          return aa;
      };
operator()() [3/4]
template<typename Tp >
template<typename Up >
auto emsr::Polynomial< Tp >::operator() (Up x) const -> decltype(value_type{} * Up{}) [inline]
Evaluate the polynomial at the input point.
Definition at line 283 of file polynomial.h.
                              {} * Up{})
        {
          if (this->degree() > 0)
            {
              if (std::abs(x) <= real_type{1})
                {
                  auto poly(Up{1} * this->coefficient(this->degree()));
                  for (int i = this->degree() - 1; i >= 0; --i)
                    poly = poly * x + this->coefficient(i);
                  return poly;
                }
              else
                {
                  const auto rx = real_type{1} / x;
                  auto poly(Up{1} * this->coefficient(0));
                  for (std::size_t i = 1ull; i <= this->degree(); ++i)
                    poly = poly * rx + this->coefficient(i);
                  for (std::size_t i = 1ull; i <= this->degree(); ++i)
                    poly *= x;
                  return poly;
                }
            }
          else
            return Up{1} * this->coefficient(0);
        }
operator()() [4/4]
template<typename Tp >
value_type emsr::Polynomial< Tp >::operator() (value_type x) const [inline]
Evaluate the polynomial at the input point.
Definition at line 252 of file polynomial.h.
      {
        if (this->degree() > 0)
          {
            if (std::abs(x) <= real_type{1})
              {
                value_type poly(this->coefficient(this->degree()));
                for (int i = this->degree() - 1; i >= 0; --i)
                  poly = poly * x + this->coefficient(i);
                return poly;
              }
            else
              {
                const auto rx = real_type{1} / x;
                value_type poly(this->coefficient(0));
                for (std::size_t i = 1ull; i <= this->degree(); ++i)
                  poly = poly * rx + this->coefficient(i);
                for (std::size_t i = 1ull; i <= this->degree(); ++i)
                  poly *= x;
                return poly;
              }
          }
        else
          return this->coefficient(0);
      }
References emsr::abs(), emsr::Polynomial< Tp >::coefficient(), and emsr::Polynomial< Tp >::degree().
operator*=() [1/3]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator*= (const Polynomial< Up > & poly)
Multiply the polynomial by another polynomial.
operator*=() [2/3]
template<typename Tp >
template<typename Up >
Polynomial<Tp>& emsr::Polynomial< Tp >::operator*= (const Polynomial< Up > & poly)
Multiply the polynomial by another polynomial.
Definition at line 366 of file polynomial.tcc.
      {
        // Test for zero size polys and do special processing?
        const size_type m = this->degree();
        const size_type n = poly.degree();
        std::vector<value_type> new_coeff(m + n + 1);
        for (size_type i = 0; i <= m; ++i)
          for (size_type j = 0; j <= n; ++j)
            new_coeff[i + j] += this->m_coeff[i]
                                * static_cast<value_type>(poly.m_coeff[j]);
        this->m_coeff = new_coeff;
        return *this;
      }
References emsr::Polynomial< Tp >::degree().
operator*=() [3/3]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator*= (const Up & c) [inline]
Multiply the polynomial by a scalar.
Definition at line 553 of file polynomial.h.
        {
          for (size_type i = 0; i < this->m_coeff.size(); ++i)
            this->m_coeff[i] *= static_cast<value_type>(c);
          return *this;
        }
operator+()
template<typename Tp >
Polynomial emsr::Polynomial< Tp >::operator+ () const [inline], [noexcept]
Unary plus.
Definition at line 476 of file polynomial.h.
      { return *this; }
operator+=() [1/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator+= (const Polynomial< Up > & poly) [inline]
Add another polynomial to the polynomial.
Definition at line 590 of file polynomial.h.
        {
          this->degree(std::max(this->degree(), poly.degree()));
          for (size_type n = poly.degree(), i = 0; i <= n; ++i)
            this->m_coeff[i] += static_cast<value_type>(poly.m_coeff[i]);
          return *this;
        }
References emsr::Polynomial< Tp >::degree().
operator+=() [2/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator+= (const Up & x) [inline]
Add a scalar to the polynomial.
Definition at line 531 of file polynomial.h.
        {
          this->m_coeff[0] += static_cast<value_type>(x);
          return *this;
        }
operator-()
template<typename Tp >
Polynomial emsr::Polynomial< Tp >::operator- () const [inline]
Unary minus.
Definition at line 483 of file polynomial.h.
      { return Polynomial(*this) *= value_type(-1); }
References emsr::Polynomial< Tp >::Polynomial().
operator-=() [1/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator-= (const Polynomial< Up > & poly) [inline]
Subtract another polynomial from the polynomial.
Definition at line 603 of file polynomial.h.
        {
          // Resize if necessary.
          this->degree(std::max(this->degree(), poly.degree()));
          for (size_type n = poly.degree(), i = 0; i <= n; ++i)
            this->m_coeff[i] -= static_cast<value_type>(poly.m_coeff[i]);
          return *this;
        }
References emsr::Polynomial< Tp >::degree().
operator-=() [2/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator-= (const Up & x) [inline]
Subtract a scalar from the polynomial.
Definition at line 542 of file polynomial.h.
        {
          this->m_coeff[0] -= static_cast<value_type>(x);
          return *this;
        }
operator/=() [1/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator/= (const Polynomial< Up > & poly) [inline]
Divide the polynomial by another polynomial.
Definition at line 624 of file polynomial.h.
        {
          Polynomial<value_type >quo, rem;
          divmod(*this, poly, quo, rem);
          *this = quo;
          return *this;
        }
References emsr::divmod().
operator/=() [2/2]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator/= (const Up & c) [inline]
Divide the polynomial by a scalar.
Definition at line 565 of file polynomial.h.
        {
          for (size_type i = 0; i < this->m_coeff.size(); ++i)
            this->m_coeff[i] /= static_cast<value_type>(c);
          return *this;
        }
operator=() [1/4]
template<typename Tp >
Polynomial& emsr::Polynomial< Tp >::operator= (const Polynomial< Tp > &) [default]
Copy assignment.
operator=() [2/4]
template<typename Tp >
template<typename Up >
Polynomial& emsr::Polynomial< Tp >::operator= (const Polynomial< Up > & poly) [inline]
Definition at line 505 of file polynomial.h.
        {
          if (&poly != this)
            {
              this->m_coeff.clear();
              for (const auto c : poly)
                this->m_coeff.push_back(static_cast<value_type>(c));
              return *this;
            }
        }
operator=() [3/4]
template<typename Tp >
Polynomial& emsr::Polynomial< Tp >::operator= (const value_type & x) [inline]
Assign from a scalar. The result is a zero degree polynomial equal to the scalar.
Definition at line 491 of file polynomial.h.
      {
        this->m_coeff = {x};
        return *this;
      }
operator=() [4/4]
template<typename Tp >
Polynomial& emsr::Polynomial< Tp >::operator= (std::initializer_list< value_type > ila) [inline]
Assign from an initialiser list.
Definition at line 520 of file polynomial.h.
      {
        this->m_coeff = ila;
        return *this;
      }
operator[]() [1/2]
template<typename Tp >
value_type emsr::Polynomial< Tp >::operator[] (size_type i) const [inline], [noexcept]
Return coefficient i.
Definition at line 706 of file polynomial.h.
      { return this->m_coeff[i]; }
operator[]() [2/2]
template<typename Tp >
reference emsr::Polynomial< Tp >::operator[] (size_type i) [inline], [noexcept]
Return coefficient i as an assignable quantity.
Definition at line 713 of file polynomial.h.
      { return this->m_coeff[i]; }
rbegin() [1/2]
template<typename Tp >
const_reverse_iterator emsr::Polynomial< Tp >::rbegin () const [inline], [noexcept]
Definition at line 799 of file polynomial.h.
      { return this->m_coeff.rbegin(); }
rbegin() [2/2]
template<typename Tp >
reverse_iterator emsr::Polynomial< Tp >::rbegin () [inline], [noexcept]
Definition at line 791 of file polynomial.h.
      { return this->m_coeff.rbegin(); }
rend() [1/2]
template<typename Tp >
const_reverse_iterator emsr::Polynomial< Tp >::rend () const [inline], [noexcept]
Definition at line 803 of file polynomial.h.
      { return this->m_coeff.rend(); }
rend() [2/2]
template<typename Tp >
reverse_iterator emsr::Polynomial< Tp >::rend () [inline], [noexcept]
Definition at line 795 of file polynomial.h.
      { return this->m_coeff.rend(); }
shift()
template<typename Tp >
void emsr::Polynomial< Tp >::shift (value_type shift) [inline]
Shift the polynomial using the Horner scheme. Given our polynomial
 P(x) = a_0 + a_1 x + a_2 x^2 + ... 
 Obtain a new polynomial
 Q(z) = P(x + s) = a_0 + a_1 (x + s) + a_2 (x + s)^2 + ... = b_0 + b_1 x + b_2 x^2 
Definition at line 657 of file polynomial.h.
      {
        if (shift == value_type{})
          return;
        const int n = this->degree();
        for (int j = 1; j <= n; ++j)
          for (int i = 1; i <= n - j + 1; ++i)
            this->m_coeff[n - i] += shift * this->m_coeff[n - i + 1];
      }
References emsr::Polynomial< Tp >::degree().
size()
template<typename Tp >
size_type emsr::Polynomial< Tp >::size () const [inline], [noexcept]
Return the size of the coefficient sequence.
Definition at line 685 of file polynomial.h.
      { return this->m_coeff.size(); }
Referenced by emsr::operator>>().
swap()
template<typename Tp >
void emsr::Polynomial< Tp >::swap (Polynomial< Tp > & poly) [inline], [noexcept]
Swap the polynomial with another polynomial.
Definition at line 245 of file polynomial.h.
      { this->m_coeff.swap(poly.m_coeff); }
Friends And Related Function Documentation
operator==
template<typename Tp >
template<typename Tp1 >
bool operator== (const Polynomial< Tp1 > & pa, const Polynomial< Tp1 > & pb) [friend]
operator>>
template<typename Tp >
template<typename CharT , typename Traits , typename Tp1 >
std::basic_istream<CharT, Traits>& operator>> (std::basic_istream< CharT, Traits > & , Polynomial< Tp1 > &) [friend]
Member Data Documentation
derivative
template<typename Tp >
template<typename Up >
decltype(Up{} * value_type{} emsr::Polynomial< Tp >::derivative) (Up c) const [inline]
Return the derivative of the polynomial at the given point.
Definition at line 426 of file polynomial.h.
        {
          using res_t = decltype(Up{} * value_type{});
          const int n = this->degree();
          res_t res = real_type(n) * this->m_coeff[n];
          for (int i = n - 1; i > 0; --i)
            res = c * res + real_type(i) * this->m_coeff[i];
          return res;
        }
integral
template<typename Tp >
template<typename Up >
decltype(Up{} * value_type{} emsr::Polynomial< Tp >::integral) (Up a, Up b) const [inline]
Return the integral of the polynomial with given integration limits.
Definition at line 454 of file polynomial.h.
        {
          using res_t = decltype(Up{} * value_type{});
          const int n = this->degree();
          const auto coeff = this->m_coeff[n] / real_type(n + 1);
          res_t resa = coeff * a;
          res_t resb = coeff * b;
          for (int i = n - 1; i >= 0; --i)
            {
              const auto coeff = this->m_coeff[i] / real_type(i + 1);
              resa += coeff;
              resa *= a;
              resb += coeff;
              resb *= b;
            }
          return resb - resa;
        }
The documentation for this class was generated from the following files:
include/emsr/polynomial.h
include/emsr/polynomial.tcc