__gnu_cxx::_StaticPolynomial< _Tp, _Size > Class Template Reference
#include <static_polynomial.h>
Public Types
using const_iterator = typename std::array< value_type, _Size >::const_iterator
using const_pointer = typename std::array< _Tp, _Size >::const_pointer
using const_reference = typename std::array< _Tp, _Size >::const_reference
using const_reverse_iterator = typename std::array< value_type, _Size >::const_reverse_iterator
using difference_type = typename std::array< _Tp, _Size >::difference_type
using iterator = typename std::array< value_type, _Size >::iterator
using pointer = typename std::array< _Tp, _Size >::pointer
using reference = typename std::array< _Tp, _Size >::reference
using reverse_iterator = typename std::array< value_type, _Size >::reverse_iterator
using size_type = typename std::array< _Tp, _Size >::size_type
using value_type = typename std::array< _Tp, _Size >::value_type
Public Member Functions
constexpr _StaticPolynomial ()
constexpr _StaticPolynomial (const _StaticPolynomial &)=default
constexpr _StaticPolynomial (_StaticPolynomial &&)=default
template<typename _Up >
constexpr _StaticPolynomial (const _StaticPolynomial< _Up, _Size > &__poly)
template<typename _Up >
constexpr _StaticPolynomial (const _Up(&__arr)[_Size])
constexpr _StaticPolynomial (std::initializer_list< _Tp > __il)
constexpr _StaticPolynomial (value_type __a, size_type __degree=0)
template<typename InIter , typename = std::_RequireInputIter<InIter>>
constexpr _StaticPolynomial (const InIter &__abegin, const InIter &__aend)
* _Tp2 ())
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const_iterator cend () const
constexpr value_type coefficient (size_type __i) const
constexpr void coefficient (size_type __i, value_type __val)
constexpr const std::array< value_type, _Size > coefficients () const noexcept
constexpr std::array< value_type, _Size > coefficients () noexcept
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
constexpr const value_type * data () const noexcept
constexpr value_type * data () noexcept
constexpr size_type degree () const
constexpr _StaticPolynomial< _Tp,(_Size > 1 ? _Size - 1 :1)> derivative () const
iterator end ()
const_iterator end () const
template<size_type N>
constexpr void eval (value_type __x, std::array< value_type, N > &__arr)
template<typename OutIter >
constexpr void eval (value_type __x, OutIter __b, OutIter __e)
constexpr value_type eval_even (value_type __x) const
template<typename _Tp2 >
constexpr auto eval_even (std::complex< _Tp2 > __z) const -> decltype(value_type
constexpr value_type eval_odd (value_type __x) const
template<typename _Tp2 >
constexpr auto eval_odd (std::complex< _Tp2 > __z) const -> decltype(value_type
constexpr _StaticPolynomial< _Tp, _Size+1 > integral (value_type __c=value_type{}) const
constexpr value_type operator() (value_type __x) const
template<typename _Tp2 >
constexpr auto operator() (_Tp2 __x) const -> decltype(value_type
template<typename _Tp2 >
constexpr auto operator() (std::complex< _Tp2 > __z) const -> decltype(value_type
template<typename InIter , typename OutIter , typename = std::_RequireInputIter<InIter>>
constexpr OutIter operator() (const InIter &__xbegin, const InIter &__xend, OutIter &__pbegin) const
_StaticPolynomial & operator*= (const value_type &__c)
constexpr _StaticPolynomial operator+ () const noexcept
_StaticPolynomial & operator+= (const value_type &__x)
constexpr _StaticPolynomial operator- () const
_StaticPolynomial & operator-= (const value_type &__x)
_StaticPolynomial & operator/= (const value_type &__c)
constexpr _StaticPolynomial & operator= (const _StaticPolynomial &)=default
template<typename _Up >
_StaticPolynomial & operator= (const _StaticPolynomial< _Up, _Size > &__poly)
constexpr _StaticPolynomial & operator= (std::initializer_list< value_type > __ila)
constexpr value_type operator[] (size_type __i) const
reference operator[] (size_type __i)
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
void swap (_StaticPolynomial &__poly)
Friends
template<typename _Tp1 >
bool operator== (const _StaticPolynomial< _Tp1, _Size > &__pa, const _StaticPolynomial< _Tp1, _Size > &__pb)
Detailed Description
template<typename _Tp, std::size_t _Size>
class __gnu_cxx::_StaticPolynomial< _Tp, _Size >
This is a constant size polynomial. It is really meant to just evaluate canned polynomial literals.
Definition at line 56 of file static_polynomial.h.
Member Typedef Documentation
const_iterator
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::const_iterator = typename std::array<value_type, _Size>::const_iterator
Definition at line 68 of file static_polynomial.h.
const_pointer
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::const_pointer = typename std::array<_Tp, _Size>::const_pointer
Definition at line 66 of file static_polynomial.h.
const_reference
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::const_reference = typename std::array<_Tp, _Size>::const_reference
Definition at line 64 of file static_polynomial.h.
const_reverse_iterator
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::const_reverse_iterator = typename std::array<value_type, _Size>::const_reverse_iterator
Definition at line 70 of file static_polynomial.h.
difference_type
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::difference_type = typename std::array<_Tp, _Size>::difference_type
Definition at line 72 of file static_polynomial.h.
iterator
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::iterator = typename std::array<value_type, _Size>::iterator
Definition at line 67 of file static_polynomial.h.
pointer
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::pointer = typename std::array<_Tp, _Size>::pointer
Definition at line 65 of file static_polynomial.h.
reference
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::reference = typename std::array<_Tp, _Size>::reference
Definition at line 63 of file static_polynomial.h.
reverse_iterator
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::reverse_iterator = typename std::array<value_type, _Size>::reverse_iterator
Definition at line 69 of file static_polynomial.h.
size_type
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::size_type = typename std::array<_Tp, _Size>::size_type
Definition at line 71 of file static_polynomial.h.
value_type
template<typename _Tp, std::size_t _Size>
using __gnu_cxx::_StaticPolynomial< _Tp, _Size >::value_type = typename std::array<_Tp, _Size>::value_type
Typedefs.
Definition at line 62 of file static_polynomial.h.
Constructor & Destructor Documentation
_StaticPolynomial() [1/8]
template<typename _Tp, std::size_t _Size>
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial () [inline]
Create a zero degree polynomial with value zero.
Definition at line 78 of file static_polynomial.h.
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::_StaticPolynomial(), and __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::operator-().
      : _M_coeff{}
      { }
_StaticPolynomial() [2/8]
template<typename _Tp, std::size_t _Size>
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (const _StaticPolynomial< _Tp, _Size > &) [default]
Copy ctor.
_StaticPolynomial() [3/8]
template<typename _Tp, std::size_t _Size>
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (_StaticPolynomial< _Tp, _Size > &&) [default]
_StaticPolynomial() [4/8]
template<typename _Tp, std::size_t _Size>
template<typename _Up >
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (const _StaticPolynomial< _Up, _Size > & __poly) [inline]
Definition at line 90 of file static_polynomial.h.
        : _M_coeff{}
        {
          for (auto __i = 0ULL; __i < _Size; ++__i)
            this->_M_coeff[__i] = static_cast<value_type>(__poly._M_coeff[__i]);
        }
_StaticPolynomial() [5/8]
template<typename _Tp, std::size_t _Size>
template<typename _Up >
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (const _Up(&) __arr[_Size]) [inline]
Constructor from C-type array.
Definition at line 102 of file static_polynomial.h.
        : _M_coeff{}
        {
          for (auto __i = 0ULL; __i < _Size; ++__i)
            this->_M_coeff[__i] = static_cast<value_type>(__arr[__i]);
        }
_StaticPolynomial() [6/8]
template<typename _Tp, std::size_t _Size>
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (std::initializer_list< _Tp > __il) [inline]
Constructor from initializer_list array.
Definition at line 113 of file static_polynomial.h.
      : _M_coeff{}
      {
        //static_assert(__il.size() == _Size, "");
        std::size_t __i = 0;
        for (auto&& __coeff : __il)
          this->_M_coeff[__i++] = __coeff;
      }
_StaticPolynomial() [7/8]
template<typename _Tp, std::size_t _Size>
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (value_type __a, size_type __degree = 0) [inline], [explicit]
Create a polynomial - actually a monomial - of just one term.
Definition at line 126 of file static_polynomial.h.
      : _M_coeff(__degree + 1)
      {
        static_assert(__degree < _Size, "_StaticPolynomial: degree out of range");
        this->_M_coeff[__degree] = __a;
      }
_StaticPolynomial() [8/8]
template<typename _Tp, std::size_t _Size>
template<typename InIter , typename = std::_RequireInputIter<InIter>>
constexpr __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_StaticPolynomial (const InIter & __abegin, const InIter & __aend) [inline]
Create a polynomial from an argument list of coefficients. constexpr _StaticPolynomial(value_type&& __aa0, value_type&&... __aa) : _M_coeff(std::experimental::make_array(__aa0, __aa...)) { } Create a polynomial from an input iterator range of coefficients.
Definition at line 147 of file static_polynomial.h.
        : _M_coeff(__abegin, __aend)
        { }
Member Function Documentation
_Tp2()
template<typename _Tp, std::size_t _Size>
* __gnu_cxx::_StaticPolynomial< _Tp, _Size >::_Tp2 () [inline]
Definition at line 181 of file static_polynomial.h.
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::_Tp2().
                              {} * _Tp2())
        {
          if (this->degree() > 0)
            {
              auto __poly(this->coefficient(this->degree()) *
      _Tp2(1));
              for (int __i = this->degree() - 1; __i >= 0; --__i)
                __poly = __poly * __x + this->coefficient(__i);
              return __poly;
            }
          else
            return value_type{};
        }
begin() [1/2]
template<typename _Tp, std::size_t _Size>
iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::begin () [inline]
Definition at line 582 of file static_polynomial.h.
      { return this->_M_coeff.begin(); }
begin() [2/2]
template<typename _Tp, std::size_t _Size>
const_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::begin () const [inline]
Definition at line 590 of file static_polynomial.h.
      { return this->_M_coeff.begin(); }
cbegin()
template<typename _Tp, std::size_t _Size>
const_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::cbegin () const [inline]
Definition at line 598 of file static_polynomial.h.
      { return this->_M_coeff.cbegin(); }
cend()
template<typename _Tp, std::size_t _Size>
const_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::cend () const [inline]
Definition at line 602 of file static_polynomial.h.
      { return this->_M_coeff.cend(); }
coefficient() [1/2]
template<typename _Tp, std::size_t _Size>
constexpr value_type __gnu_cxx::_StaticPolynomial< _Tp, _Size >::coefficient (size_type __i) const [inline]
Return the ith coefficient with range checking.
Definition at line 529 of file static_polynomial.h.
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::_Tp2(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::derivative(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::eval(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::eval_even(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::eval_odd(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::integral(), and __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::operator()().
      { return this->_M_coeff.at(__i); }
coefficient() [2/2]
template<typename _Tp, std::size_t _Size>
constexpr void __gnu_cxx::_StaticPolynomial< _Tp, _Size >::coefficient (size_type __i, value_type __val) [inline]
Set coefficient i to val with range checking.
Definition at line 536 of file static_polynomial.h.
      { this->_M_coeff.at(__i) = __val; }
coefficients() [1/2]
template<typename _Tp, std::size_t _Size>
constexpr const std::array<value_type, _Size> __gnu_cxx::_StaticPolynomial< _Tp, _Size >::coefficients () const [inline], [noexcept]
Return a const vector of coefficients.
Definition at line 557 of file static_polynomial.h.
      { return this->_M_coeff; }
coefficients() [2/2]
template<typename _Tp, std::size_t _Size>
constexpr std::array<value_type, _Size> __gnu_cxx::_StaticPolynomial< _Tp, _Size >::coefficients () [inline], [noexcept]
Return a vector of coefficients.
Definition at line 564 of file static_polynomial.h.
      { return this->_M_coeff; }
crbegin()
template<typename _Tp, std::size_t _Size>
const_reverse_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::crbegin () const [inline]
Definition at line 622 of file static_polynomial.h.
      { return this->_M_coeff.crbegin(); }
crend()
template<typename _Tp, std::size_t _Size>
const_reverse_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::crend () const [inline]
Definition at line 626 of file static_polynomial.h.
      { return this->_M_coeff.crend(); }
data() [1/2]
template<typename _Tp, std::size_t _Size>
constexpr const value_type* __gnu_cxx::_StaticPolynomial< _Tp, _Size >::data () const [inline], [noexcept]
Return a const pointer to the coefficient sequence.
Definition at line 571 of file static_polynomial.h.
      { return this->_M_coeff.data(); }
data() [2/2]
template<typename _Tp, std::size_t _Size>
constexpr value_type* __gnu_cxx::_StaticPolynomial< _Tp, _Size >::data () [inline], [noexcept]
Return a pointer to the coefficient sequence.
Definition at line 578 of file static_polynomial.h.
      { return this->_M_coeff.data(); }
degree()
template<typename _Tp, std::size_t _Size>
constexpr size_type __gnu_cxx::_StaticPolynomial< _Tp, _Size >::degree () const [inline]
Return the degree or the power of the largest coefficient.
Definition at line 522 of file static_polynomial.h.
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::_Tp2(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::derivative(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::eval_even(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::eval_odd(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::integral(), __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::operator()(), __gnu_cxx::operator*(), and __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::operator=().
      { return (this->_M_coeff.size() > 0 ? this->_M_coeff.size() - 1 : 0); }
derivative()
template<typename _Tp, std::size_t _Size>
constexpr _StaticPolynomial<_Tp, (_Size > 1 ? _Size - 1 : 1)> __gnu_cxx::_StaticPolynomial< _Tp, _Size >::derivative () const [inline]
Return the derivative of the polynomial.
Definition at line 410 of file static_polynomial.h.
      {
        _StaticPolynomial<_Tp, (_Size > 1 ? _Size - 1 : 1)> __res;
        for (size_type __i = 1; __i <= this->degree(); ++__i)
          __res.coefficient(__i - 1, __i * _M_coeff[__i]);
        return __res;
      }
end() [1/2]
template<typename _Tp, std::size_t _Size>
iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::end () [inline]
Definition at line 586 of file static_polynomial.h.
      { return this->_M_coeff.end(); }
end() [2/2]
template<typename _Tp, std::size_t _Size>
const_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::end () const [inline]
Definition at line 594 of file static_polynomial.h.
      { return this->_M_coeff.end(); }
eval() [1/2]
template<typename _Tp, std::size_t _Size>
template<size_type N>
constexpr void __gnu_cxx::_StaticPolynomial< _Tp, _Size >::eval (value_type __x, std::array< value_type, N > & __arr) [inline]
Definition at line 243 of file static_polynomial.h.
        {
          if (__arr.size() > 0)
            {
              __arr.fill(value_type{});
              const size_type __sz = _M_coeff.size();
              __arr[0] = this->coefficient(__sz - 1);
              for (int __i = __sz - 2; __i >= 0; --__i)
                {
                  int __nn = std::min(__arr.size() - 1, __sz - 1 - __i);
                  for (int __j = __nn; __j >= 1; --__j)
                    __arr[__j] = __arr[__j] * __x + __arr[__j - 1];
                  __arr[0] = __arr[0] * __x + this->coefficient(__i);
                }
              // Now put in the factorials.
              value_type __fact = value_type(1);
              for (size_t __i = 2; __i < __arr.size(); ++__i)
                {
                  __fact *= value_type(__i);
                  __arr[__i] *= __fact;
                }
            }
        }
eval() [2/2]
template<typename _Tp, std::size_t _Size>
template<typename OutIter >
constexpr void __gnu_cxx::_StaticPolynomial< _Tp, _Size >::eval (value_type __x, OutIter __b, OutIter __e) [inline]
Evaluate the polynomial and its derivatives at the point x. The values are placed in the output range starting with the polynomial value and continuing through higher derivatives.
Definition at line 274 of file static_polynomial.h.
        {
          if(__b != __e)
            {
              std::fill(__b, __e, value_type{});
              constexpr size_type __sz = _M_coeff.size();
              *__b = _M_coeff[__sz - 1];
              for (int __i = __sz - 2; __i >= 0; --__i)
                {
                  for (auto __it = std::reverse_iterator<OutIter>(__e);
                           __it != std::reverse_iterator<OutIter>(__b) - 1; ++__it)
                    *__it = *__it * __x + *(__it + 1);
                  *__b = *__b * __x + _M_coeff[__i];
                }
              // Now put in the factorials.
              int __i = 0;
              value_type __fact = value_type(++__i);
              for (auto __it = __b + 1; __it != __e; ++__it)
                {
                  __fact *= value_type(__i);
                  *__it *= __fact;
                  ++__i;
                }
            }
        }
eval_even() [1/2]
template<typename _Tp, std::size_t _Size>
constexpr value_type __gnu_cxx::_StaticPolynomial< _Tp, _Size >::eval_even (value_type __x) const [inline]
Evaluate the even part of the polynomial at the input point.
Definition at line 304 of file static_polynomial.h.
      {
        if (this->degree() > 0)
          {
            auto __odd = this->degree() % 2;
            value_type __poly(this->coefficient(this->
      degree() - __odd));
            for (int __i = this->degree() - __odd - 2; __i >= 0; __i -= 2)
              __poly = __poly * __x * __x + this->coefficient(__i);
            return __poly;
          }
        else
          return value_type{};
      }
eval_even() [2/2]
template<typename _Tp, std::size_t _Size>
template<typename _Tp2 >
constexpr auto __gnu_cxx::_StaticPolynomial< _Tp, _Size >::eval_even (std::complex< _Tp2 > __z) const -> decltype(value_type [inline]
Evaluate the even part of the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 350 of file static_polynomial.h.
                              {} * std::complex<_Tp2>{})
eval_odd() [1/2]
template<typename _Tp, std::size_t _Size>
constexpr value_type __gnu_cxx::_StaticPolynomial< _Tp, _Size >::eval_odd (value_type __x) const [inline]
Evaluate the odd part of the polynomial at the input point.
Definition at line 322 of file static_polynomial.h.
      {
        if (this->degree() > 0)
          {
            auto __even = (this->degree() % 2 == 0 ? 1 : 0);
            value_type __poly(this->coefficient(this->
      degree() - __even));
            for (int __i = this->degree() - __even - 2; __i >= 0; __i -= 2)
              __poly = __poly * __x * __x + this->coefficient(__i);
            return __poly * __x;
          }
        else
          return value_type{};
      }
eval_odd() [2/2]
template<typename _Tp, std::size_t _Size>
template<typename _Tp2 >
constexpr auto __gnu_cxx::_StaticPolynomial< _Tp, _Size >::eval_odd (std::complex< _Tp2 > __z) const -> decltype(value_type [inline]
Evaluate the odd part of the polynomial using a modification of Horner's rule which exploits the fact that the polynomial coefficients are all real.
The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies and 4 * n - 6 additions are saved.
Definition at line 385 of file static_polynomial.h.
                              {} * std::complex<_Tp2>{})
integral()
template<typename _Tp, std::size_t _Size>
constexpr _StaticPolynomial<_Tp, _Size + 1> __gnu_cxx::_StaticPolynomial< _Tp, _Size >::integral (value_type __c = value_type{}) const [inline]
Return the integral of the polynomial with given integration constant.
Definition at line 422 of file static_polynomial.h.
                                          {}) const
      {
        _StaticPolynomial<_Tp, _Size + 1> __res;
        __res.coefficient(0, __c);
        for (size_type __i = 0; __i <= this->degree(); ++__i)
          __res.coefficient(__i + 1, _M_coeff[__i] / value_type(__i + 1));
        return __res;
      }
operator()() [1/4]
template<typename _Tp, std::size_t _Size>
constexpr value_type __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator() (value_type __x) const [inline]
Evaluate the polynomial at the input point.
Definition at line 162 of file static_polynomial.h.
      {
        if (this->degree() > 0)
          {
            value_type __poly(this->coefficient(this->
      degree()));
            for (int __i = this->degree() - 1; __i >= 0; --__i)
              __poly = __poly * __x + this->coefficient(__i);
            return __poly;
          }
        else
          return value_type{};
      }
operator()() [2/4]
template<typename _Tp, std::size_t _Size>
template<typename _Tp2 >
constexpr auto __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator() (_Tp2 __x) const -> decltype(value_type [inline]
Evaluate the polynomial at the input point.
Definition at line 180 of file static_polynomial.h.
                              {} * _Tp2())
operator()() [3/4]
template<typename _Tp, std::size_t _Size>
template<typename _Tp2 >
constexpr auto __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator() (std::complex< _Tp2 > __z) const -> decltype(value_type [inline]
The following polynomial evaluations are done using a modified of Horner's rule which exploits the fact that the polynomial coefficients are all real. The algorithm is discussed in detail in: Knuth, D. E., The Art of Computer Programming: Seminumerical Algorithms (Vol. 2) Third Ed., Addison-Wesley, pp 486-488, 1998.
If n is the degree of the polynomial, n - 3 multiplies are saved and 4 * n - 6 additions are saved.
Definition at line 207 of file static_polynomial.h.
                              {} * std::complex<_Tp2>{})
operator()() [4/4]
template<typename _Tp, std::size_t _Size>
template<typename InIter , typename OutIter , typename = std::_RequireInputIter<InIter>>
constexpr OutIter __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator() (const InIter & __xbegin, const InIter & __xend, OutIter & __pbegin) const [inline]
Evaluate the polynomial at a range of input points. The output is written to the output iterator which must be large enough to contain the results. The next available output iterator is returned.
Definition at line 232 of file static_polynomial.h.
        {
          for (; __xbegin != __xend; ++__xbegin)
            __pbegin++ = (*this)(__xbegin++);
          return __pbegin;
        }
operator*=()
template<typename _Tp, std::size_t _Size>
_StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator*= (const value_type & __c) [inline]
Multiply the polynomial by a scalar.
Definition at line 500 of file static_polynomial.h.
      {
        for (size_type __i = 0; __i < this->_M_coeff.size(); ++__i)
          this->_M_coeff[__i] *= static_cast<value_type>(__c);
        return *this;
      }
operator+()
template<typename _Tp, std::size_t _Size>
constexpr _StaticPolynomial __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator+ () const [inline], [noexcept]
Unary plus.
Definition at line 435 of file static_polynomial.h.
      { return *this; }
operator+=()
template<typename _Tp, std::size_t _Size>
_StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator+= (const value_type & __x) [inline]
Add a scalar to the polynomial.
Definition at line 480 of file static_polynomial.h.
      {
        this->_M_coeff[0] += static_cast<value_type>(__x);
        return *this;
      }
operator-()
template<typename _Tp, std::size_t _Size>
constexpr _StaticPolynomial __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator- () const [inline]
Unary minus.
Definition at line 442 of file static_polynomial.h.
      { return _StaticPolynomial(*this) *= value_type(-1); }
operator-=()
template<typename _Tp, std::size_t _Size>
_StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator-= (const value_type & __x) [inline]
Subtract a scalar from the polynomial.
Definition at line 490 of file static_polynomial.h.
      {
        this->_M_coeff[0] -= static_cast<value_type>(__x);
        return *this;
      }
operator/=()
template<typename _Tp, std::size_t _Size>
_StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator/= (const value_type & __c) [inline]
Divide the polynomial by a scalar.
Definition at line 511 of file static_polynomial.h.
      {
        for (size_type __i = 0; __i < this->_M_coeff.size(); ++__i)
          this->_M_coeff[__i] /= static_cast<value_type>(__c);
        return *this;
      }
operator=() [1/3]
template<typename _Tp, std::size_t _Size>
constexpr _StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator= (const _StaticPolynomial< _Tp, _Size > &) [default]
Copy assignment.
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::operator-().
operator=() [2/3]
template<typename _Tp, std::size_t _Size>
template<typename _Up >
_StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator= (const _StaticPolynomial< _Up, _Size > & __poly) [inline]
Definition at line 453 of file static_polynomial.h.
        {
          if (&__poly != this)
            {
              this->_M_coeff.clear();
              for (const auto __c : __poly)
                this->_M_coeff = static_cast<value_type>(__c);
              return *this;
            }
        }
operator=() [3/3]
template<typename _Tp, std::size_t _Size>
constexpr _StaticPolynomial& __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator= (std::initializer_list< value_type > __ila) [inline]
Assign from an initialiser list.
Definition at line 468 of file static_polynomial.h.
      {
        for (size_type __i = 0;
             __i <= std::min(this->degree(), __ila.size()); ++__i)
          this->_M_coeff[__i] = __ila[__i];
        return *this;
      }
operator[]() [1/2]
template<typename _Tp, std::size_t _Size>
constexpr value_type __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator[] (size_type __i) const [inline]
Return coefficient i.
Definition at line 543 of file static_polynomial.h.
      { return this->_M_coeff[__i]; }
operator[]() [2/2]
template<typename _Tp, std::size_t _Size>
reference __gnu_cxx::_StaticPolynomial< _Tp, _Size >::operator[] (size_type __i) [inline]
Return coefficient i as an assignable quantity.
Definition at line 550 of file static_polynomial.h.
      { return this->_M_coeff[__i]; }
rbegin() [1/2]
template<typename _Tp, std::size_t _Size>
reverse_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::rbegin () [inline]
Definition at line 606 of file static_polynomial.h.
      { return this->_M_coeff.rbegin(); }
rbegin() [2/2]
template<typename _Tp, std::size_t _Size>
const_reverse_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::rbegin () const [inline]
Definition at line 614 of file static_polynomial.h.
      { return this->_M_coeff.rbegin(); }
rend() [1/2]
template<typename _Tp, std::size_t _Size>
reverse_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::rend () [inline]
Definition at line 610 of file static_polynomial.h.
      { return this->_M_coeff.rend(); }
rend() [2/2]
template<typename _Tp, std::size_t _Size>
const_reverse_iterator __gnu_cxx::_StaticPolynomial< _Tp, _Size >::rend () const [inline]
Definition at line 618 of file static_polynomial.h.
      { return this->_M_coeff.rend(); }
swap()
template<typename _Tp, std::size_t _Size>
void __gnu_cxx::_StaticPolynomial< _Tp, _Size >::swap (_StaticPolynomial< _Tp, _Size > & __poly) [inline]
Swap the polynomial with another polynomial.
Definition at line 155 of file static_polynomial.h.
      { this->_M_coeff.swap(__poly._M_coeff); }
Friends And Related Function Documentation
operator==
template<typename _Tp, std::size_t _Size>
template<typename _Tp1 >
bool operator== (const _StaticPolynomial< _Tp1, _Size > & __pa, const _StaticPolynomial< _Tp1, _Size > & __pb) [friend]
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _SizeRem >::crend().
The documentation for this class was generated from the following file:
include/ext/static_polynomial.h