__gnu_cxx Namespace Reference
Classes
struct __has_imag_t
struct __has_imag_t< T, std::void_t< decltype(std::declval< T & >().imag())> >
class _Polynomial
A dense polynomial class with a contiguous array of coefficients. The coefficients are lowest-order first:
 P(x) = a_0 + a_1 x + ... + a_n x^n 
.
class _RationalPolynomial
class _StaticPolynomial
Typedefs
template<typename _Real >
using solution_t = std::variant< std::monostate, _Real, std::complex< _Real > >
Functions
template<typename _Real , typename _Iter >
std::array< solution_t< _Real >, 3 > __cubic (const _Iter &_CC)
Finds the roots of a cubic equation of the form:
 a_3 x^3 + a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
template<typename _Real >
std::array< solution_t< _Real >, 3 > __cubic (_Real __c0, _Real __c1, _Real __c2, _Real __c3)
template<typename _Real , typename _Iter >
std::array< solution_t< _Real >, 2 > __quadratic (const _Iter &_CC)
Finds the roots of a quadratic equation of the form:
 a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
template<typename _Real >
std::array< solution_t< _Real >, 2 > __quadratic (_Real __c0, _Real __c1, _Real __c2)
template<typename _Real , typename _Iter >
std::array< solution_t< _Real >, 4 > __quartic (const _Iter &_CC)
Finds the roots a quartic equation of the form:
 a_4 x^4 + a_3 x^3 + a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
template<typename _Real >
std::array< solution_t< _Real >, 4 > __quartic (_Real __c0, _Real __c1, _Real __c2, _Real __c3, _Real __c4)
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp __refine_solution_halley (_NumTp __z, const _Iter &_CC)
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp __refine_solution_newton (_NumTp __z, const _Iter &_CC)
template<std::size_t _Dim, typename _Iter , typename _Real >
void __refine_solutions (std::array< solution_t< _Real >, _Dim - 1 > &_ZZ, const _Iter &_CC)
template<typename _Real >
constexpr _Real abs (const solution_t< _Real > &__x)
template<typename _Tp >
void divmod (const _Polynomial< _Tp > &__pa, const _Polynomial< _Tp > &__pb, _Polynomial< _Tp > &__quo, _Polynomial< _Tp > &__rem)
template<typename _Tp >
get_scale (const _Polynomial< _Tp > &__poly)
template<typename _Tp >
get_scale (const _Tp &__x)
template<typename _ArgT , typename _Coef0 >
constexpr std::conditional_t< std::is_integral< _ArgT >::value, double, _ArgT > horner (_ArgT __x, _Coef0 __c0)
template<typename _ArgT , typename _Coef0 , typename... _Coef>
constexpr std::conditional_t< std::is_integral< _ArgT >::value, double, _ArgT > horner (_ArgT __x, _Coef0 __c0, _Coef... __c)
template<typename _ArgT , typename _Coef0 >
constexpr std::conditional_t< std::is_integral< _ArgT >::value, double, _ArgT > horner_big_end (_ArgT, _Coef0 __c0)
template<typename _ArgT , typename _Coef1 , typename _Coef0 >
constexpr std::conditional_t< std::is_integral< _ArgT >::value, double, _ArgT > horner_big_end (_ArgT __x, _Coef1 __c1, _Coef0 __c0)
template<typename _ArgT , typename _CoefN , typename _CoefNm1 , typename... _Coef>
constexpr std::conditional_t< std::is_integral< _ArgT >::value, double, _ArgT > horner_big_end (_ArgT __x, _CoefN __cn, _CoefNm1 __cnm1, _Coef... __c)
template<typename _Real >
constexpr _Real imag (const solution_t< _Real > &__x)
template<typename _Real >
constexpr bool is_valid (const solution_t< _Real > &__x)
template<typename _Tp , std::size_t _NumA, std::size_t _NumB>
bool operator!= (const _StaticPolynomial< _Tp, _NumA > &__pa, const _StaticPolynomial< _Tp, _NumB > &__pb)
template<typename _Tp , std::size_t _Num>
bool operator!= (const _StaticPolynomial< _Tp, _Num > &__pa, const _StaticPolynomial< _Tp, _Num > &__pb)
template<typename _Tp >
bool operator!= (const _Polynomial< _Tp > &__pa, const _Polynomial< _Tp > &__pb)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()/_Up())> operator% (const _Polynomial< _Tp > &__poly, const _Up &__x)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()/_Up())> operator% (const _Polynomial< _Tp > &__pa, const _Polynomial< _Up > &__pb)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()/_Up())> operator% (const _Tp &__x, const _Polynomial< _Up > &__poly)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp() *_Up())> operator* (const _Polynomial< _Tp > &__poly, const _Up &__x)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp() *_Up())> operator* (const _Polynomial< _Tp > &__pa, const _Polynomial< _Up > &__pb)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp() *_Up())> operator* (const _Tp &__x, const _Polynomial< _Up > &__poly)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()+_Up())> operator+ (const _Polynomial< _Tp > &__poly, const _Up &__x)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()+_Up())> operator+ (const _Polynomial< _Tp > &__pa, const _Polynomial< _Up > &__pb)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()+_Up())> operator+ (const _Tp &__x, const _Polynomial< _Up > &__poly)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp() - _Up())> operator- (const _Polynomial< _Tp > &__poly, const _Up &__x)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp() - _Up())> operator- (const _Polynomial< _Tp > &__pa, const _Polynomial< _Up > &__pb)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp() - _Up())> operator- (const _Tp &__x, const _Polynomial< _Up > &__poly)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()/_Up())> operator/ (const _Polynomial< _Tp > &__poly, const _Up &__x)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()/_Up())> operator/ (const _Polynomial< _Tp > &__pa, const _Polynomial< _Up > &__pb)
template<typename _Tp , typename _Up >
_Polynomial< decltype(_Tp()/_Up())> operator/ (const _Tp &__x, const _Polynomial< _Up > &__poly)
template<typename CharT , typename Traits , typename _Tp >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &__os, const _RationalPolynomial< _Tp > &__poly)
template<typename CharT , typename Traits , typename _Tp >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &__os, const _Polynomial< _Tp > &__poly)
template<typename _Tp , std::size_t _NumA, std::size_t _NumB>
bool operator== (const _StaticPolynomial< _Tp, _NumA > &, const _StaticPolynomial< _Tp, _NumB > &)
template<typename _Tp , std::size_t _Num>
bool operator== (const _StaticPolynomial< _Tp, _Num > &__pa, const _StaticPolynomial< _Tp, _Num > &__pb)
template<typename _Tp >
bool operator== (const _Polynomial< _Tp > &__pa, const _Polynomial< _Tp > &__pb)
template<typename CharT , typename Traits , typename _Tp >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &__is, _RationalPolynomial< _Tp > &__poly)
template<typename CharT , typename Traits , typename _Tp >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &__is, _Polynomial< _Tp > &__poly)
template<typename _Real >
constexpr _Real real (const solution_t< _Real > &__x)
template<typename _Tp >
void swap (_Polynomial< _Tp > &__pa, _Polynomial< _Tp > &__pb) noexcept(noexcept(__pa.swap(__pb)))
template<typename _Real >
constexpr solution_t< _Real > to_complex (const solution_t< _Real > &__x)
Variables
template<typename T >
constexpr auto __has_imag_v = __has_imag_t<T>::value
* _Up
Detailed Description
detail: Do we want this to always have a size of at least one? a_0 = _Tp{}? YES. detail: Should I punt on the initial power? YES.
If high degree coefficients are zero, should I resize down? YES (or provide another word for order). How to access coefficients (bikeshed)? poly[i]; coefficient(i); operator[](int i); begin(), end()? const _Tp* coefficients(); // Access for C, Fortran. How to set individual coefficients? poly[i] = c; coefficient(i, c); coefficient(i) = c; How to handle division? operator/ and throw out remainder? operator% to return the remainder? std::pair<> div(const _Polynomial& __a, const _Polynomial& __b) or remquo. void divmod(const _Polynomial& __a, const _Polynomial& __b, _Polynomial& __q, _Polynomial& __r); Should factory methods like derivative and integral be globals? I could have members: _Polynomial& integrate(_Tp c); _Polynomial& differentiate(); Largest coefficient: Enforce coefficient of largest power be nonzero? Return an 'effective' order? Larest nonzero coefficient? Monic polynomial has largest coefficient as 1. Subclass?
Typedef Documentation
solution_t
template<typename _Real >
using __gnu_cxx::solution_t = typedef std::variant<std::monostate, _Real, std::complex<_Real> >
Definition at line 59 of file solution.h.
Function Documentation
__cubic() [1/2]
template<typename _Real , typename _Iter >
std::array< solution_t< _Real >, 3 > __gnu_cxx::__cubic (const _Iter & _CC)
Finds the roots of a cubic equation of the form:
 a_3 x^3 + a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
In the non-degenerate case there are three roots:
All three roots are real
One root is real and the other two are a complex conjugate pair
If the cubic coefficient $ a_3 $ is zero (degenerate case) the problem is referred to the quadratic solver to return, at most, two valid roots.
Parameters
in _CC Array that contains the four coefficients of the cubic equation
Definition at line 226 of file solver_low_degree.tcc.
References abs().
Referenced by __quadratic().
    {
      using std::experimental::make_array;
      std::array<solution_t<_Real>, 3> _ZZ;
      if (_CC[3] == _Real{0})
        {
          // Last root is null, remaining equation is quadratic.
          const auto _ZZ2 = __quadratic<_Real>(_CC);
          _ZZ[0] = _ZZ2[0];
          _ZZ[1] = _ZZ2[1];
        }
      else if (_CC[0] == _Real{0})
        {
          // First root is zero, remaining equation is quadratic.
          _ZZ[0] = _Real{0};
          const auto _ZZ2 = __quadratic<_Real>(make_array(_CC[1], _CC[2],
                                                          _CC[3]));
          _ZZ[1] = _ZZ2[0];
          _ZZ[2] = _ZZ2[1];
        }
      else
        {
          // Normalize cubic equation coefficients.
          std::array<_Real, 4> _AA3;
          _AA3[3] = _Real{1};
          _AA3[2] = _CC[2] / _CC[3];
          _AA3[1] = _CC[1] / _CC[3];
          _AA3[0] = _CC[0] / _CC[3];
          const auto _S_2pi = _Real{2} * __gnu_cxx::__const_pi(_CC[0]);
          const auto _PP = _AA3[2] / _Real{3};
          const auto _QQ = (_AA3[2] * _AA3[2] - _Real{3} * _AA3[1])
                         / _Real{9};
          const auto _QQp3 = _QQ * _QQ * _QQ;
          const auto _RR = (_Real{2} * _AA3[2] * _AA3[2] * _AA3[2]
                          - _Real{9} * _AA3[2] * _AA3[1]
                          + _Real{27} * _AA3[0]) / _Real{54};
          const auto _RRp2 = _RR * _RR;
          if (_QQp3 - _RRp2 > _Real{0})
            {
              // Calculate the three real roots.
              const auto __phi = std::acos(_RR / std::sqrt(_QQp3));
              const auto __fact = -_Real{2} * std::sqrt(_QQ);
              for (int __i = 0; __i < 3; ++__i)
                _ZZ[__i] = __fact * std::cos((__phi + __i * _S_2pi) / _Real{3}) - _PP;
            }
          else
            {
              // Calculate the single real root.
              const auto __fact = std::cbrt(std::abs(_RR)
                                          + std::sqrt(_RRp2 - _QQp3));
              const auto _BB = -std::copysign(__fact + _QQ / __fact, _RR);
              _ZZ[0] = _BB - _PP;
              // Find the other two roots which are complex conjugates.
              std::array<_Real, 3> _AA2;
              _AA2[2] = _Real{1};
              _AA2[1] = _BB;
              _AA2[0] = _BB * _BB - _Real{3} * _QQ;
              const auto _ZZ2 = __quadratic<_Real>(_AA2);
              _ZZ[1] = std::get<2>(_ZZ2[0]) - _PP;
              _ZZ[2] = std::get<2>(_ZZ2[1]) - _PP;
            }
        }
      return _ZZ;
    }
__cubic() [2/2]
template<typename _Real >
std::array<solution_t<_Real>, 3> __gnu_cxx::__cubic (_Real __c0, _Real __c1, _Real __c2, _Real __c3) [inline]
Definition at line 82 of file solver_low_degree.h.
References __quartic().
    {
      using std::experimental::make_array;
      return __cubic<_Real>(make_array(__c0, __c1, __c2, __c3));
    }
__quadratic() [1/2]
template<typename _Real , typename _Iter >
std::array< solution_t< _Real >, 2 > __gnu_cxx::__quadratic (const _Iter & _CC)
Finds the roots of a quadratic equation of the form:
 a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
For non-degenerate coefficients two roots are returned: Either the roots are real or the roots are a complex conjugate pair.
If the quadratic coefficient $ a_2 $ is zero (degenerate case) at most one valid root is returned. If the linear coefficient $ a_1 $ is also zero no valid root is returned.
Parameters
in _CC Array that contains the three coefficients of the quadratic equation.
Definition at line 153 of file solver_low_degree.tcc.
References abs().
    {
      std::array<solution_t<_Real>, 2> _ZZ;
      if (_CC[2] == _Real{0})
        {
          // Equation is linear (or completely degenerate).
          if (_CC[1] == _Real{0})
            return _ZZ;
          else
            {
              _ZZ[0] = -_CC[0] / _CC[1];
              return _ZZ;
            }
        }
      else if (_CC[0] == _Real{0})
        {
          _ZZ[0] = _Real{0};
          if (_CC[2] == _Real{0})
            return _ZZ;
          else
            {
              _ZZ[1] = -_CC[1] / _CC[2];
              return _ZZ;
            }
        }
      else
        {
          // The discriminant of a quadratic equation
          const auto _QQ = _CC[1] * _CC[1] - _Real{4} * _CC[2] * _CC[0];
          if (_QQ < _Real{0})
            {
              // The roots are complex conjugates.
              const auto _ReZZ = -_CC[1] / (_Real{2} * _CC[2]);
              const auto _ImZZ = std::sqrt(std::abs(_QQ)) / (_Real{2} * _CC[2]);
              _ZZ[0] = std::complex<_Real>(_ReZZ, -_ImZZ);
              _ZZ[1] = std::complex<_Real>(_ReZZ, _ImZZ);
            }
          else
            {
              // The roots are real.
              _Real __temp = -(_CC[1]
                        + std::copysign(std::sqrt(_QQ), _CC[1])) / _Real{2};
              _ZZ[0] = __temp / _CC[2];
              _ZZ[1] = _CC[0] / __temp;
            }
        }
      return _ZZ;
    }
__quadratic() [2/2]
template<typename _Real >
std::array<solution_t<_Real>, 2> __gnu_cxx::__quadratic (_Real __c0, _Real __c1, _Real __c2) [inline]
Definition at line 70 of file solver_low_degree.h.
References __cubic().
    {
      using std::experimental::make_array;
      return __quadratic<_Real>(make_array(__c0, __c1, __c2));
    }
__quartic() [1/2]
template<typename _Real , typename _Iter >
std::array< solution_t< _Real >, 4 > __gnu_cxx::__quartic (const _Iter & _CC)
Finds the roots a quartic equation of the form:
 a_4 x^4 + a_3 x^3 + a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
In the non-degenerate case there are four roots:
All four roots are real
Two roots real and two complex roots are a complex conjugate pair
Four complex roots in two complex conjugate pairs
If the qartic coefficient $ a_4 $ is zero (degenerate case) the problem is referred to the cubic solver to return, at most, three valid roots.
Parameters
in _CC Array that contains the five(5) coefficients of the quartic equation.
Definition at line 319 of file solver_low_degree.tcc.
References abs(), and swap().
Referenced by __cubic().
    {
      using std::experimental::make_array;
      std::array<solution_t<_Real>, 4> _ZZ;
      if (_CC[4] == _Real{0})
        {
          const auto _ZZ3 = __cubic<_Real>(_CC);
          _ZZ[0] = _ZZ3[0];
          _ZZ[1] = _ZZ3[1];
          _ZZ[2] = _ZZ3[2];
        }
      else if (_CC[0] == _Real{0})
        {
          _ZZ[0] = _Real{0};
          const auto _ZZ3 = __cubic<_Real>(make_array(_CC[1], _CC[2],
                                                      _CC[3], _CC[4]));
          _ZZ[1] = _ZZ3[0];
          _ZZ[2] = _ZZ3[1];
        }
      else if (_CC[3] == _Real{0} && _CC[1] == _Real{0})
        {
          // Solve the biquadratic equation.
          std::array<_Real, 3> _AA2{{_CC[0], _CC[2], _CC[4]}};
          const auto _ZZ2 = __quadratic<_Real>(_AA2);
          auto __sqrt = [](solution_t<_Real> __z) -> solution_t<_Real>
                        {
                          const auto __idx = __z.index();
                          if (__idx == 0)
                            return __z;
                          else if (__idx == 1)
                            {
                              auto __zz = std::get<1>(__z);
                              return __zz < _Real{0}
                                   ? solution_t<_Real>(std::sqrt(
      std::complex<_Real>(__zz)))
                                   : solution_t<_Real>(std::sqrt(__zz));
                            }
                          else
                            return solution_t<_Real>(std::sqrt(std::get<2>(__z)));
                        };
          _ZZ[0] = __sqrt(_ZZ2[0]);
          _ZZ[1] = __sqrt(_ZZ2[1]);
          _ZZ[2] = -_ZZ[0];
          _ZZ[3] = -_ZZ[1];
        }
      else
        {
          // Normalize quartic equation coefficients.
          std::array<_Real, 5> _AA4;
          _AA4[4] = _Real{1};
          _AA4[3] = _CC[3] / _CC[4];
          _AA4[2] = _CC[2] / _CC[4];
          _AA4[1] = _CC[1] / _CC[4];
          _AA4[0] = _CC[0] / _CC[4];
          // Calculate the coefficients of the resolvent cubic equation.
          std::array<_Real, 4> _AA3;
          _AA3[3] = _Real{1};
          _AA3[2] = -_AA4[2];
          _AA3[1] = _AA4[3] * _AA4[1] - _Real{4} * _AA4[0];
          _AA3[0] = _AA4[0] * (_Real{4} * _AA4[2] - _AA4[3] * _AA4[3])
                  - _AA4[1] * _AA4[1];
          // Find the algebraically largest real root of the cubic equation
          // Note: A cubic equation has either three real roots or one
          // real root and two complex roots that are complex
          // conjugates. If there is only a single real root then
          // subroutine cubic always returns that single real root
          // (and therefore the algebraically largest real root of
          // the cubic equation) as root[0].
          _Real _Z3max;
          auto _ZZ3 = __cubic<_Real>(_AA3);
          if (_ZZ3[1].index() == 1 && _ZZ3[2].index() == 1)
            {
              // There is some horrible bug with swap and this variant.
              // They may need to hold the same type.
              if (_ZZ3[0] < _ZZ3[1])
                //std::swap(_ZZ3[0], _ZZ3[1]);
                {
                  const auto __tmp = _ZZ3[0];
                  _ZZ3[0] = _ZZ3[1];
                  _ZZ3[1] = __tmp;
                }
              if (_ZZ3[0] < _ZZ3[2])
                //std::swap(_ZZ3[0], _ZZ3[2]);
                {
                  const auto __tmp = _ZZ3[0];
                  _ZZ3[0] = _ZZ3[2];
                  _ZZ3[2] = __tmp;
                }
              _Z3max = std::get<1>(_ZZ3[0]);
            }
          else
            _Z3max = std::get<1>(_ZZ3[0]);
          // Calculate the coefficients for the two quadratic equations
          const auto __capa = _Real{0.5L} * _AA4[3];
          const auto __capb = _Real{0.5L} * _Z3max;
          const auto __capc = std::sqrt(__capa * __capa - _AA4[2] + _Z3max);
          const auto __capd = std::sqrt(__capb * __capb - _AA4[0]);
          const auto __cp = __capa + __capc;
          const auto __cm = __capa - __capc;
          auto __dp = __capb + __capd;
          auto __dm = __capb - __capd;
          const auto __t1 = __cp * __dm + __cm * __dp;
          const auto __t2 = __cp * __dp + __cm * __dm;
          if (std::abs(__t2 - _AA4[1]) < std::abs(__t1 - _AA4[1]))
            std::swap(__dp, __dm);
          // Coefficients for the first quadratic equation and find the roots.
          std::array<_Real, 3> _AA2;
          _AA2[2] = _Real{1};
          _AA2[1] = __cp;
          _AA2[0] = __dp;
          const auto _ZZ2p = __quadratic<_Real>(_AA2);
          _ZZ[0] = _ZZ2p[0];
          _ZZ[1] = _ZZ2p[1];
          // Coefficients for the second quadratic equation and find the roots.
          _AA2[2] = _Real{1};
          _AA2[1] = __cm;
          _AA2[0] = __dm;
          const auto _ZZ2m = __quadratic<_Real>(_AA2);
          _ZZ[2] = _ZZ2m[0];
          _ZZ[3] = _ZZ2m[1];
        }
      return _ZZ;
    }
__quartic() [2/2]
template<typename _Real >
std::array<solution_t<_Real>, 4> __gnu_cxx::__quartic (_Real __c0, _Real __c1, _Real __c2, _Real __c3, _Real __c4) [inline]
Definition at line 94 of file solver_low_degree.h.
    {
      using std::experimental::make_array;
      return __quartic<_Real>(make_array(__c0, __c1, __c2, __c3, __c4));
    }
__refine_solution_halley()
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp __gnu_cxx::__refine_solution_halley (_NumTp __z, const _Iter & _CC)
Refine a solution using the Halley method:
 x_{n+1} - x_n = -\frac{2 P(x_n) P'(x_n)} {2 [P'(x_n)]^2 - P(x_n) P''(x_n)} 
 This form indicates the close relationship to the Newton method:
 x_{n+1} - x_n = -\frac{P'(x_n)} {P'(x_n) - [P(x_n) P''(x_n)]/[2P'(x_n)]} 
Definition at line 94 of file solver_low_degree.tcc.
    {
      for (int __i = 0; __i < 3; ++__i)
        {
          auto __f = _NumTp(_CC[_Dim - 1]);
          for (std::size_t __j = _Dim - 1; __j > 0; --__j)
            __f = _NumTp(_CC[__j - 1]) + __z * __f;
          auto __df = _NumTp((_Dim - 1) * _CC[_Dim - 1]);
          for (std::size_t __j = _Dim - 1; __j > 1; --__j)
            __df = _NumTp((__j - 1) * _CC[__j - 1]) + __z * __df;
          auto __d2f = _NumTp((_Dim - 2) * (_Dim - 1) * _CC[_Dim - 1]);
          for (std::size_t __j = _Dim - 1; __j > 2; --__j)
            __d2f = _NumTp((__j - 2) * (__j - 1) * _CC[__j - 1]) + __z * __d2f;
          const auto __del = _NumTp{2} * __f * __df
                           / (_NumTp{2} * __df * __df - __f * __d2f);
          __z -= __del;
        }
      return __z;
    }
__refine_solution_newton()
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp __gnu_cxx::__refine_solution_newton (_NumTp __z, const _Iter & _CC)
Refine a solution using the Newton method:
 x_{n+1} - x_n = -\frac{P(x_n)}{P'(x_n)} 
Definition at line 62 of file solver_low_degree.tcc.
    {
      for (int __i = 0; __i < 3; ++__i)
        {
          auto __f = _NumTp(_CC[_Dim - 1]);
          for (std::size_t __j = _Dim - 1; __j > 0; --__j)
            __f = _NumTp(_CC[__j - 1]) + __z * __f;
          auto __df = _NumTp((_Dim - 1) * _CC[_Dim - 1]);
          for (std::size_t __j = _Dim - 1; __j > 1; --__j)
            __df = _NumTp((__j - 1) * _CC[__j - 1]) + __z * __df;
          const auto __del = __f / __df;
          __z -= __del;
        }
      return __z;
    }
__refine_solutions()
template<std::size_t _Dim, typename _Iter , typename _Real >
void __gnu_cxx::__refine_solutions (std::array< solution_t< _Real >, _Dim - 1 > & _ZZ, const _Iter & _CC)
Definition at line 120 of file solver_low_degree.tcc.
    {
      for (std::size_t __i = 0; __i < _Dim - 1; ++__i)
        {
          if (_ZZ[__i].index() == 0)
            continue;
          else if (_ZZ[__i].index() == 1)
            _ZZ[__i] = __refine_solution_newton<_Dim>(std::get<1>(_ZZ[__i]), _CC);
          else if (_ZZ[__i].index() == 2)
            _ZZ[__i] = __refine_solution_newton<_Dim>(std::get<2>(_ZZ[__i]), _CC);
        }
    }
abs()
template<typename _Real >
constexpr _Real __gnu_cxx::abs (const solution_t< _Real > & __x)
Definition at line 116 of file solution.h.
Referenced by __cubic(), __quadratic(), __quartic(), and get_scale().
    {
      if (__x.index() == 0)
        return std::numeric_limits<_Real>::quiet_NaN();
      else if (__x.index() == 1)
        return std::abs(std::get<1>(__x));
      else
        return std::abs(std::get<2>(__x));
    }
divmod()
template<typename _Tp >
void __gnu_cxx::divmod (const _Polynomial< _Tp > & __pa, const _Polynomial< _Tp > & __pb, _Polynomial< _Tp > & __quo, _Polynomial< _Tp > & __rem)
Divide two polynomials returning the quotient and remainder.
Definition at line 351 of file polynomial.tcc.
References __gnu_cxx::_Polynomial< _Tp >::coefficient(), and __gnu_cxx::_Polynomial< _Tp >::degree().
Referenced by operator%(), __gnu_cxx::_Polynomial< value_type >::operator%=(), and __gnu_cxx::_Polynomial< value_type >::operator/=().
    {
      __rem = __pa;
      __quo = _Polynomial<_Tp>(_Tp(), __pa.degree());
      const std::size_t __na = __pa.degree();
      const std::size_t __nb = __pb.degree();
      if (__nb <= __na)
        {
          for (int __k = __na - __nb; __k >= 0; --__k)
            {
              __quo.coefficient(__k, __rem.coefficient(__nb + __k)
                                   / __pb.coefficient(__nb));
              for (int __j = __nb + __k - 1; __j >= __k; --__j)
                __rem.coefficient(__j, __rem.coefficient(__j)
                                     - __quo.coefficient(__k)
                                     * __pb.coefficient(__j - __k));
            }
          for (int __j = __nb; __j <= __na; ++__j)
            __rem.coefficient(__j, _Tp());
        }
    }
get_scale() [1/2]
template<typename _Tp >
__gnu_cxx::get_scale (const _Polynomial< _Tp > & __poly)
Return the scale for a polynomial.
Definition at line 728 of file polynomial.h.
    { return __poly._M_get_scale(); }
get_scale() [2/2]
template<typename _Tp >
__gnu_cxx::get_scale (const _Tp & __x)
Return the scale for a number.
Definition at line 735 of file polynomial.h.
References abs().
    { return std::abs(__x); }
horner() [1/2]
template<typename _ArgT , typename _Coef0 >
constexpr std::conditional_t<std::is_integral<_ArgT>::value, double, _ArgT> __gnu_cxx::horner (_ArgT __x, _Coef0 __c0)
Perform compile-time evaluation of a constant zero-order polynomial.
Definition at line 52 of file horner.h.
Referenced by horner().
  {
    using __arg_t = std::conditional_t<std::is_integral<_ArgT>::value,
                                        double, _ArgT>;
    return __arg_t{__c0};
  }
horner() [2/2]
template<typename _ArgT , typename _Coef0 , typename... _Coef>
constexpr std::conditional_t<std::is_integral<_ArgT>::value, double, _ArgT> __gnu_cxx::horner (_ArgT __x, _Coef0 __c0, _Coef... __c)
Perform compile-time evaluation of a constant polynomial. The polynomial coefficients are lowest-order first.
Definition at line 65 of file horner.h.
References horner().
  {
    using __arg_t = std::conditional_t<std::is_integral<_ArgT>::value,
                                        double, _ArgT>;
    return __arg_t{__c0} + __x * horner(__x, __c...);
  }
horner_big_end() [1/3]
template<typename _ArgT , typename _Coef0 >
constexpr std::conditional_t<std::is_integral<_ArgT>::value, double, _ArgT> __gnu_cxx::horner_big_end (_ArgT , _Coef0 __c0)
Perform compile-time evaluation of a constant zero-order polynomial. The polynomial coefficients are highest-order first.
Definition at line 79 of file horner.h.
Referenced by horner_big_end().
  {
    using __arg_t = std::conditional_t<std::is_integral<_ArgT>::value,
                                        double, _ArgT>;
    return __arg_t{__c0};
  }
horner_big_end() [2/3]
template<typename _ArgT , typename _Coef1 , typename _Coef0 >
constexpr std::conditional_t<std::is_integral<_ArgT>::value, double, _ArgT> __gnu_cxx::horner_big_end (_ArgT __x, _Coef1 __c1, _Coef0 __c0)
Perform compile-time evaluation of a constant first-order polynomial. The polynomial coefficients are highest-order first.
Definition at line 92 of file horner.h.
References horner_big_end().
  {
    using __arg_t = std::conditional_t<std::is_integral<_ArgT>::value,
                                        double, _ArgT>;
    return horner_big_end(__x, __x * __arg_t{__c1} + __arg_t{__c0});
  }
horner_big_end() [3/3]
template<typename _ArgT , typename _CoefN , typename _CoefNm1 , typename... _Coef>
constexpr std::conditional_t<std::is_integral<_ArgT>::value, double, _ArgT> __gnu_cxx::horner_big_end (_ArgT __x, _CoefN __cn, _CoefNm1 __cnm1, _Coef... __c)
Perform compile-time evaluation of a constant polynomial. The polynomial coefficients are highest-order first.
Definition at line 105 of file horner.h.
References horner_big_end().
  {
    using __arg_t = std::conditional_t<std::is_integral<_ArgT>::value,
                                        double, _ArgT>;
    return horner_big_end(__x, __x * __arg_t{__cn} + __arg_t{__cnm1}, __c...);
  }
imag()
template<typename _Real >
constexpr _Real __gnu_cxx::imag (const solution_t< _Real > & __x)
Definition at line 104 of file solution.h.
Referenced by std::operator<().
    {
      if (__x.index() == 0)
        return std::numeric_limits<_Real>::quiet_NaN();
      else if (__x.index() == 1)
        return _Real{0};
      else
        return std::imag(std::get<2>(__x));
    }
is_valid()
template<typename _Real >
constexpr bool __gnu_cxx::is_valid (const solution_t< _Real > & __x)
Definition at line 63 of file solution.h.
    { return __x.index() != 0; }
operator!=() [1/3]
template<typename _Tp , std::size_t _NumA, std::size_t _NumB>
bool __gnu_cxx::operator!= (const _StaticPolynomial< _Tp, _NumA > & __pa, const _StaticPolynomial< _Tp, _NumB > & __pb) [inline]
Return false if two polynomials are equal.
Definition at line 558 of file static_polynomial.h.
    { return true; }
operator!=() [2/3]
template<typename _Tp , std::size_t _Num>
bool __gnu_cxx::operator!= (const _StaticPolynomial< _Tp, _Num > & __pa, const _StaticPolynomial< _Tp, _Num > & __pb) [inline]
Return false if two polynomials are equal.
Definition at line 567 of file static_polynomial.h.
    { return !(__pa == __pb); }
operator!=() [3/3]
template<typename _Tp >
bool __gnu_cxx::operator!= (const _Polynomial< _Tp > & __pa, const _Polynomial< _Tp > & __pb) [inline]
Return false if two polynomials are equal.
Definition at line 898 of file polynomial.h.
    { return !(__pa == __pb); }
operator%() [1/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() / _Up())> __gnu_cxx::operator% (const _Polynomial< _Tp > & __poly, const _Up & __x) [inline]
Definition at line 775 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() / _Up())>(__poly) %= __x; }
operator%() [2/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() / _Up())> __gnu_cxx::operator% (const _Polynomial< _Tp > & __pa, const _Polynomial< _Up > & __pb) [inline]
Return the modulus or remainder of one polynomial relative to another one.
Definition at line 815 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() / _Up())>(__pa) %= __pb; }
operator%() [3/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() / _Up())> __gnu_cxx::operator% (const _Tp & __x, const _Polynomial< _Up > & __poly) [inline]
Return the modulus or remainder of one polynomial relative to another one.
Definition at line 855 of file polynomial.h.
References _Up, divmod(), and operator>>().
    { return _Polynomial<decltype(_Tp() / _Up())>(__x) %= __poly; }
operator*() [1/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() * _Up())> __gnu_cxx::operator* (const _Polynomial< _Tp > & __poly, const _Up & __x) [inline]
Return the product of a polynomial with a scalar.
Definition at line 759 of file polynomial.h.
References _Up.
Referenced by std::operator*().
    { return _Polynomial<decltype(_Tp() * _Up())>(__poly) *= __x; }
operator*() [2/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() * _Up())> __gnu_cxx::operator* (const _Polynomial< _Tp > & __pa, const _Polynomial< _Up > & __pb) [inline]
Return the product of two polynomials.
Definition at line 799 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() * _Up())>(__pa) *= __pb; }
operator*() [3/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() * _Up())> __gnu_cxx::operator* (const _Tp & __x, const _Polynomial< _Up > & __poly) [inline]
Definition at line 839 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() * _Up())>(__x) *= __poly; }
operator+() [1/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() + _Up())> __gnu_cxx::operator+ (const _Polynomial< _Tp > & __poly, const _Up & __x) [inline]
Return the sum of a polynomial with a scalar.
Definition at line 743 of file polynomial.h.
References _Up.
Referenced by std::operator+().
    { return _Polynomial<decltype(_Tp() + _Up())>(__poly) += __x; }
operator+() [2/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() + _Up())> __gnu_cxx::operator+ (const _Polynomial< _Tp > & __pa, const _Polynomial< _Up > & __pb) [inline]
Return the sum of two polynomials.
Definition at line 783 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() + _Up())>(__pa) += __pb; }
operator+() [3/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() + _Up())> __gnu_cxx::operator+ (const _Tp & __x, const _Polynomial< _Up > & __poly) [inline]
Definition at line 823 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() + _Up())>(__x) += __poly; }
operator-() [1/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() - _Up())> __gnu_cxx::operator- (const _Polynomial< _Tp > & __poly, const _Up & __x) [inline]
Return the difference of a polynomial with a scalar.
Definition at line 751 of file polynomial.h.
References _Up.
Referenced by std::operator-().
    { return _Polynomial<decltype(_Tp() - _Up())>(__poly) -= __x; }
operator-() [2/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() - _Up())> __gnu_cxx::operator- (const _Polynomial< _Tp > & __pa, const _Polynomial< _Up > & __pb) [inline]
Return the difference of two polynomials.
Definition at line 791 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() - _Up())>(__pa) -= __pb; }
operator-() [3/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() - _Up())> __gnu_cxx::operator- (const _Tp & __x, const _Polynomial< _Up > & __poly) [inline]
Definition at line 831 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() - _Up())>(__x) -= __poly; }
operator/() [1/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() / _Up())> __gnu_cxx::operator/ (const _Polynomial< _Tp > & __poly, const _Up & __x) [inline]
Return the quotient of a polynomial with a scalar.
Definition at line 767 of file polynomial.h.
References _Up.
Referenced by std::operator/().
    { return _Polynomial<decltype(_Tp() / _Up())>(__poly) /= __x; }
operator/() [2/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() / _Up())> __gnu_cxx::operator/ (const _Polynomial< _Tp > & __pa, const _Polynomial< _Up > & __pb) [inline]
Return the quotient of two polynomials.
Definition at line 807 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() / _Up())>(__pa) /= __pb; }
operator/() [3/3]
template<typename _Tp , typename _Up >
_Polynomial<decltype(_Tp() / _Up())> __gnu_cxx::operator/ (const _Tp & __x, const _Polynomial< _Up > & __poly) [inline]
Return the quotient of two polynomials.
Definition at line 847 of file polynomial.h.
References _Up.
    { return _Polynomial<decltype(_Tp() / _Up())>(__x) /= __poly; }
operator<<() [1/2]
template<typename CharT , typename Traits , typename _Tp >
std::basic_ostream<CharT, Traits>& __gnu_cxx::operator<< (std::basic_ostream< CharT, Traits > & __os, const _RationalPolynomial< _Tp > & __poly)
Write a polynomial to a stream. The format is a parenthesized comma-delimited list of coefficients.
Definition at line 198 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::numer().
    {
      __os << __poly.numer() << "/" << __poly.denom();
      return __os;
    }
operator<<() [2/2]
template<typename CharT , typename Traits , typename _Tp >
std::basic_ostream< CharT, Traits > & __gnu_cxx::operator<< (std::basic_ostream< CharT, Traits > & __os, const _Polynomial< _Tp > & __poly)
Write a polynomial to a stream. The format is a parenthesized comma-delimited list of coefficients.
Definition at line 380 of file polynomial.tcc.
References __gnu_cxx::_Polynomial< _Tp >::coefficient().
    {
      int __old_prec = __os.precision(std::numeric_limits<_Tp>::max_digits10);
      __os << "(";
      for (size_t __i = 0; __i < __poly.degree(); ++__i)
        __os << __poly.coefficient(__i) << ",";
      __os << __poly.coefficient(__poly.degree());
      __os << ")";
      __os.precision(__old_prec);
      return __os;
    }
operator==() [1/3]
template<typename _Tp , std::size_t _NumA, std::size_t _NumB>
bool __gnu_cxx::operator== (const _StaticPolynomial< _Tp, _NumA > & , const _StaticPolynomial< _Tp, _NumB > &) [inline]
Return true if two polynomials are equal.
Definition at line 543 of file static_polynomial.h.
    { return false; }
operator==() [2/3]
template<typename _Tp , std::size_t _Num>
bool __gnu_cxx::operator== (const _StaticPolynomial< _Tp, _Num > & __pa, const _StaticPolynomial< _Tp, _Num > & __pb) [inline]
Definition at line 549 of file static_polynomial.h.
    { return __pa._M_coeff == __pb._M_coeff; }
operator==() [3/3]
template<typename _Tp >
bool __gnu_cxx::operator== (const _Polynomial< _Tp > & __pa, const _Polynomial< _Tp > & __pb) [inline]
Return true if two polynomials are equal.
Definition at line 890 of file polynomial.h.
    { return __pa._M_coeff == __pb._M_coeff; }
operator>>() [1/2]
template<typename CharT , typename Traits , typename _Tp >
std::basic_istream<CharT, Traits>& __gnu_cxx::operator>> (std::basic_istream< CharT, Traits > & __is, _RationalPolynomial< _Tp > & __poly)
Read a polynomial from a stream. The input format can be a plain scalar (zero degree polynomial) or a parenthesized comma-delimited list of coefficients.
Definition at line 211 of file rational_polynomial.h.
References __gnu_cxx::_RationalPolynomial< _Tp >::denom(), and __gnu_cxx::_RationalPolynomial< _Tp >::numer().
    {
      _Polynomial<_Tp> __numer, __denom;
      __is >> __numer;
      if (!__is.fail())
        {
          CharT __ch;
          __is >> __ch;
          if (__ch != '/')
            __is.setstate(std::ios_base::failbit);
          else
            {
              __is >> __denom;
              if (!__is.fail())
                {
                  __poly.numer() = __numer;
                  __poly.denom() = __denom;
                }
            }
        }
      return __is;
    }
operator>>() [2/2]
template<typename CharT , typename Traits , typename _Tp >
std::basic_istream< CharT, Traits > & __gnu_cxx::operator>> (std::basic_istream< CharT, Traits > & __is, _Polynomial< _Tp > & __poly)
Read a polynomial from a stream. The input format can be a plain scalar (zero degree polynomial) or a parenthesized comma-delimited list of coefficients.
Definition at line 400 of file polynomial.tcc.
Referenced by __gnu_cxx::_Polynomial< value_type >::crend(), and operator%().
    {
      _Tp __x;
      CharT __ch;
      __is >> __ch;
      if (__ch == '(')
        {
          do
            {
              __is >> __x >> __ch;
              __poly._M_coeff.push_back(__x);
            }
          while (__ch == ',');
          if (__ch != ')')
            __is.setstate(std::ios_base::failbit);
        }
      else
        {
          __is.putback(__ch);
          __is >> __x;
          __poly = __x;
        }
      return __is;
    }
real()
template<typename _Real >
constexpr _Real __gnu_cxx::real (const solution_t< _Real > & __x)
Definition at line 92 of file solution.h.
Referenced by __gnu_cxx::_StaticPolynomial< _Tp, _Num >::eval_even(), __gnu_cxx::_StaticPolynomial< _Tp, _Num >::eval_odd(), __gnu_cxx::_Polynomial< value_type >::operator()(), __gnu_cxx::_StaticPolynomial< _Tp, _Num >::operator()(), and std::operator<().
    {
      if (__x.index() == 0)
        return std::numeric_limits<_Real>::quiet_NaN();
      else if (__x.index() == 1)
        return std::get<1>(__x);
      else
        return std::real(std::get<2>(__x));
    }
swap()
template<typename _Tp >
void __gnu_cxx::swap (_Polynomial< _Tp > & __pa, _Polynomial< _Tp > & __pb) [inline], [noexcept]
See _Polynomial::swap().
Definition at line 906 of file polynomial.h.
References __gnu_cxx::_Polynomial< _Tp >::swap().
Referenced by __quartic().
    { __pa.swap(__pb); }
to_complex()
template<typename _Real >
constexpr solution_t<_Real> __gnu_cxx::to_complex (const solution_t< _Real > & __x)
Return the solution as a complex number or NaN.
Definition at line 131 of file solution.h.
    {
      if (__x.index() == 0)
        return solution_t<_Real>();
      else if (__x.index() == 1)
        return solution_t<_Real>(std::complex<_Real>(std::get<1>(__x)));
      else
        return __x;
    }
Variable Documentation
__has_imag_v
template<typename T >
constexpr auto __gnu_cxx::__has_imag_v = __has_imag_t<T>::value
Definition at line 104 of file polynomial.h.
_Up
* __gnu_cxx::_Up
Initial value:
{})>>>
      {
        using __real_t = std::decay_t<decltype(value_type{} * _Up{})>;
        using __cmplx_t = std::complex<__real_t>;
        if (this->degree() > 0)
          {
            const auto __zz = __z * __z;
            const auto __r = _Tp{2} * std::real(__zz);
            const auto __s = std::norm(__zz);
            auto __odd = this->degree() % 2;
            size_type __n = this->degree() - __odd;
            auto __aa = this->coefficient(__n);
            auto __bb = this->coefficient(__n - 2);
            for (size_type __j = 4; __j <= __n; __j += 2)
              __bb = std::fma(-__s, __exchange(__aa, __bb + __r * __aa),
                              this->coefficient(__n - __j));
            return std::fma(__cmplx_t(__aa), __cmplx_t(__zz), __cmplx_t(__bb));
          }
        else
          return __cmplx_t{};
      }
Definition at line 263 of file polynomial.tcc.
Referenced by __gnu_cxx::_Polynomial< value_type >::eval_even(), __gnu_cxx::_Polynomial< value_type >::eval_odd(), operator%(), operator*(), operator+(), operator-(), and operator/().