std Namespace Reference
Classes
class complex
Functions
template<typename _Real >
constexpr bool operator!= (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
bool operator!= (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr bool operator!= (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr bool operator!= (const __gnu_cxx::solution_t< _Real > &__x, const std::complex< _Real > &__y)
template<typename _Real >
constexpr bool operator!= (const std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator* (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator* (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator* (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator* (const __gnu_cxx::solution_t< _Real > &__x, std::complex< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator* (std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator+ (const __gnu_cxx::solution_t< _Real > &__x)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator+ (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator+ (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator+ (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator+ (const __gnu_cxx::solution_t< _Real > &__x, std::complex< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator+ (std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator- (const __gnu_cxx::solution_t< _Real > &__x)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator- (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator- (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator- (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator- (const __gnu_cxx::solution_t< _Real > &__x, std::complex< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator- (std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator/ (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator/ (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator/ (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator/ (const __gnu_cxx::solution_t< _Real > &__x, std::complex< _Real > &__y)
template<typename _Real >
constexpr __gnu_cxx::solution_t< _Real > operator/ (std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr bool operator< (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr bool operator< (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr bool operator< (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr bool operator< (const __gnu_cxx::solution_t< _Real > &__x, const std::complex< _Real > &__y)
template<typename _Real >
constexpr bool operator< (const std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr bool operator== (const __gnu_cxx::solution_t< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
bool operator== (const __gnu_cxx::solution_t< _Real > &__x, _Real __y)
template<typename _Real >
constexpr bool operator== (_Real __x, const __gnu_cxx::solution_t< _Real > &__y)
template<typename _Real >
constexpr bool operator== (const __gnu_cxx::solution_t< _Real > &__x, const std::complex< _Real > &__y)
template<typename _Real >
constexpr bool operator== (const std::complex< _Real > &__x, const __gnu_cxx::solution_t< _Real > &__y)
Function Documentation
operator!=() [1/5]
template<typename _Real >
constexpr bool std::operator!= (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 398 of file solution.h.
    { return !(__x == __y); }
operator!=() [2/5]
template<typename _Real >
bool std::operator!= (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 404 of file solution.h.
    { return !(__x == __y); }
operator!=() [3/5]
template<typename _Real >
constexpr bool std::operator!= (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 409 of file solution.h.
    { return !(__x == __y); }
operator!=() [4/5]
template<typename _Real >
constexpr bool std::operator!= (const __gnu_cxx::solution_t< _Real > & __x, const std::complex< _Real > & __y)
Definition at line 414 of file solution.h.
    { return !(__x == __y); }
operator!=() [5/5]
template<typename _Real >
constexpr bool std::operator!= (const std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 419 of file solution.h.
    { return !(__x == __y); }
operator*() [1/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator* (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Multiplication operators...
Definition at line 266 of file solution.h.
    {
      if (__x.index() == 0)
        return __x;
      if (__y.index() == 0)
        return __y;
      else if (__x.index() == 1)
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) * std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) * std::get<2>(
      __y));
        }
      else
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) * std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) * std::get<2>(
      __y));
        }
    }
operator*() [2/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator* (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 290 of file solution.h.
References __gnu_cxx::operator*().
    { return operator*(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator*() [3/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator* (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 295 of file solution.h.
References __gnu_cxx::operator*().
    { return operator*(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator*() [4/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator* (const __gnu_cxx::solution_t< _Real > & __x, std::complex< _Real > & __y)
Definition at line 300 of file solution.h.
References __gnu_cxx::operator*().
    { return operator*(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator*() [5/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator* (std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 305 of file solution.h.
References __gnu_cxx::operator*().
    { return operator*(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator+() [1/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator+ (const __gnu_cxx::solution_t< _Real > & __x)
Unary +-
Definition at line 152 of file solution.h.
    { return __x; }
operator+() [2/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator+ (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Addition operators...
Definition at line 172 of file solution.h.
    {
      if (__x.index() == 0)
        return __x;
      if (__y.index() == 0)
        return __y;
      else if (__x.index() == 1)
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) + std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) + std::get<2>(
      __y));
        }
      else
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) + std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) + std::get<2>(
      __y));
        }
    }
operator+() [3/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator+ (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 196 of file solution.h.
References __gnu_cxx::operator+().
    { return operator+(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator+() [4/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator+ (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 201 of file solution.h.
References __gnu_cxx::operator+().
    { return operator+(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator+() [5/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator+ (const __gnu_cxx::solution_t< _Real > & __x, std::complex< _Real > & __y)
Definition at line 206 of file solution.h.
References __gnu_cxx::operator+().
    { return operator+(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator+() [6/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator+ (std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 211 of file solution.h.
References __gnu_cxx::operator+().
    { return operator+(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator-() [1/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator- (const __gnu_cxx::solution_t< _Real > & __x)
Definition at line 157 of file solution.h.
    {
      if (__x.index() == 0)
        return __x;
      else if (__x.index() == 1)
        return __gnu_cxx::solution_t<_Real>(-std::get<1>(__x));
      else
        return __gnu_cxx::solution_t<_Real>(-std::get<2>(__x));
    }
operator-() [2/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator- (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Subtraction operators...
Definition at line 219 of file solution.h.
    {
      if (__x.index() == 0)
        return __x;
      if (__y.index() == 0)
        return __y;
      else if (__x.index() == 1)
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) - std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) - std::get<2>(
      __y));
        }
      else
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) - std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) - std::get<2>(
      __y));
        }
    }
operator-() [3/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator- (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 243 of file solution.h.
References __gnu_cxx::operator-().
    { return operator-(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator-() [4/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator- (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 248 of file solution.h.
References __gnu_cxx::operator-().
    { return operator-(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator-() [5/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator- (const __gnu_cxx::solution_t< _Real > & __x, std::complex< _Real > & __y)
Definition at line 253 of file solution.h.
References __gnu_cxx::operator-().
    { return operator-(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator-() [6/6]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator- (std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 258 of file solution.h.
References __gnu_cxx::operator-().
    { return operator-(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator/() [1/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator/ (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
division operators...
Definition at line 313 of file solution.h.
    {
      if (__x.index() == 0)
        return __x;
      if (__y.index() == 0)
        return __y;
      else if (__x.index() == 1)
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) / std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<1>(__x) / std::get<2>(
      __y));
        }
      else
        {
          if (__y.index() == 1)
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) / std::get<1>(
      __y));
          else
            return __gnu_cxx::solution_t<_Real>(std::get<2>(__x) / std::get<2>(
      __y));
        }
    }
operator/() [2/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator/ (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 337 of file solution.h.
References __gnu_cxx::operator/().
    { return operator/(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator/() [3/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator/ (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 342 of file solution.h.
References __gnu_cxx::operator/().
    { return operator/(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator/() [4/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator/ (const __gnu_cxx::solution_t< _Real > & __x, std::complex< _Real > & __y)
Definition at line 347 of file solution.h.
References __gnu_cxx::operator/().
    { return operator/(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator/() [5/5]
template<typename _Real >
constexpr __gnu_cxx::solution_t<_Real> std::operator/ (std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 352 of file solution.h.
References __gnu_cxx::operator/().
    { return operator/(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator<() [1/5]
template<typename _Real >
constexpr bool std::operator< (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Lexicographic order of solutions as complex numbers. Null solutions compare as less than except to another null solution.
A tribool might be a good thing for this when either of the solutions is null.
Definition at line 431 of file solution.h.
References __gnu_cxx::imag(), and __gnu_cxx::real().
    {
      if (__x.index() == 0 && __y.index() == 0)
        return false;
      else if (__x.index() == 0)
        return true;
      else if (__y.index() == 0)
        return false;
      else
        {
          const auto __rex = __gnu_cxx::real(__x);
          const auto __rey = __gnu_cxx::real(__y);
          if (__rex < __rey)
            return true;
          else if (__rex == __rey)
            return __gnu_cxx::imag(__x) < __gnu_cxx::imag(__y);
          else
            return false;
        }
    }
operator<() [2/5]
template<typename _Real >
constexpr bool std::operator< (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 454 of file solution.h.
    { return operator<(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator<() [3/5]
template<typename _Real >
constexpr bool std::operator< (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 459 of file solution.h.
    { return operator<(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator<() [4/5]
template<typename _Real >
constexpr bool std::operator< (const __gnu_cxx::solution_t< _Real > & __x, const std::complex< _Real > & __y)
Definition at line 464 of file solution.h.
    { return operator<(__x, __gnu_cxx::solution_t<_Real>(__y)); }
operator<() [5/5]
template<typename _Real >
constexpr bool std::operator< (const std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 469 of file solution.h.
    { return operator<(__gnu_cxx::solution_t<_Real>(__x), __y); }
operator==() [1/5]
template<typename _Real >
constexpr bool std::operator== (const __gnu_cxx::solution_t< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Test for equality and inequality.
Definition at line 360 of file solution.h.
Referenced by __gnu_cxx::_Polynomial< value_type >::crend().
    {
      if (__x.index() == 0 || __y.index() == 0)
        return false;
      else if (__x.index() == __y.index())
        {
          if (__x.index() == 1)
            return std::get<1>(__x) == std::get<1>(__y);
          else
            return std::get<2>(__x) == std::get<2>(__y);
        }
      else
        return false;
    }
operator==() [2/5]
template<typename _Real >
bool std::operator== (const __gnu_cxx::solution_t< _Real > & __x, _Real __y)
Definition at line 378 of file solution.h.
    { return __x == __gnu_cxx::solution_t<_Real>(__y); }
operator==() [3/5]
template<typename _Real >
constexpr bool std::operator== (_Real __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 383 of file solution.h.
    { return __gnu_cxx::solution_t<_Real>(__x) == __y; }
operator==() [4/5]
template<typename _Real >
constexpr bool std::operator== (const __gnu_cxx::solution_t< _Real > & __x, const std::complex< _Real > & __y)
Definition at line 388 of file solution.h.
    { return __x == __gnu_cxx::solution_t<_Real>(__y); }
operator==() [5/5]
template<typename _Real >
constexpr bool std::operator== (const std::complex< _Real > & __x, const __gnu_cxx::solution_t< _Real > & __y)
Definition at line 393 of file solution.h.
    { return __gnu_cxx::solution_t<_Real>(__x) == __y; }