emsr Namespace Reference
Classes
class BairstowSolver
struct divmod_t
struct frexp_t
struct has_imag_t
struct has_imag_t< Tp, std::void_t< decltype(std::declval< Tp & >().imag())> >
struct has_value_type_t
struct has_value_type_t< Tp, std::void_t< typename Tp::value_type > >
struct int_quot_t
class JenkinsTraubSolver
class JenkinsTraubSolver< std::complex< Real > >
class LaguerreSolver
struct lgamma_t
struct modf_t
class Polynomial
A dense polynomial class with a contiguous array of coefficients. The coefficients are lowest-order first:
class QuadraticSolver
class RationalPolynomial
struct real_type
struct real_type< Polynomial< Tp > >
struct real_type< std::complex< Tp > >
struct remquo_t
struct reperiod_t
struct sincos_t
struct sinhcosh_t
struct Solution
class StaticPolynomial
Typedefs
using intmaxquot_t = int_quot_t< std::intmax_t >
using llquot_t = int_quot_t< long long int >
using lquot_t = int_quot_t< long int >
using quot_t = int_quot_t< int >
template<typename Tp >
using real_type_t = typename real_type< Tp >::type
using squot_t = int_quot_t< short int >
Functions
template<typename Real >
constexpr Real abs (const Solution< Real > &x)
double acot (double x)
double acot (sincos_t< double > m)
double acot2 (double x, double y)
reperiod_t< double > acot2_pi (double y, double x)
reperiod_t< float > acot2_pif (float y, float x)
reperiod_t< long double > acot2_pil (long double y, long double x)
float acot2f (float x, float y)
long double acot2l (long double x, long double y)
reperiod_t< double > acot_pi (double m)
reperiod_t< double > acot_pi (sincos_t< double > m)
reperiod_t< float > acot_pif (float m)
reperiod_t< float > acot_pif (sincos_t< float > m)
reperiod_t< long double > acot_pil (long double m)
reperiod_t< long double > acot_pil (sincos_t< long double > m)
float acotf (float x)
float acotf (sincos_t< float > m)
double acoth (double x)
double acoth (sinhcosh_t< double > m)
float acothf (float x)
float acothf (sinhcosh_t< float > m)
long double acothl (long double x)
long double acothl (sinhcosh_t< long double > m)
long double acotl (long double x)
long double acotl (sincos_t< long double > m)
double acsc (double x)
float acscf (float x)
double acsch (double x)
float acschf (float x)
long double acschl (long double x)
long double acscl (long double x)
double asec (double x)
float asecf (float x)
double asech (double x)
float asechf (float x)
long double asechl (long double x)
long double asecl (long double x)
double atan (sincos_t< double > m)
reperiod_t< double > atan2_pi (double y, double x)
reperiod_t< float > atan2_pif (float y, float x)
reperiod_t< long double > atan2_pil (long double y, long double x)
reperiod_t< double > atan_pi (double m)
reperiod_t< double > atan_pi (sincos_t< double > m)
reperiod_t< float > atan_pif (float m)
reperiod_t< float > atan_pif (sincos_t< float > m)
reperiod_t< long double > atan_pil (long double m)
reperiod_t< long double > atan_pil (sincos_t< long double > m)
float atanf (sincos_t< float > m)
double atanh (sinhcosh_t< double > m)
float atanhf (sinhcosh_t< float > m)
long double atanhl (sinhcosh_t< long double > m)
long double atanl (sincos_t< long double > m)
double cos_pi (double x)
double cos_pi (reperiod_t< double > x)
float cos_pif (float x)
float cos_pif (reperiod_t< float > x)
long double cos_pil (long double x)
long double cos_pil (reperiod_t< long double > x)
double cot (double x)
double cot_pi (double x)
double cot_pi (reperiod_t< double > x)
float cot_pif (float x)
float cot_pif (reperiod_t< float > x)
long double cot_pil (long double x)
long double cot_pil (reperiod_t< long double > x)
float cotf (float x)
double coth (double x)
float cothf (float x)
long double cothl (long double x)
long double cotl (long double x)
double csc (double x)
double csc_pi (double x)
double csc_pi (reperiod_t< double > x)
float csc_pif (float x)
float csc_pif (reperiod_t< float > x)
long double csc_pil (long double x)
long double csc_pil (reperiod_t< long double > x)
float cscf (float x)
double csch (double x)
float cschf (float x)
long double cschl (long double x)
long double cscl (long double x)
template<typename Real , typename Iter >
std::array< Solution< Real >, 3 > cubic (const Iter &CC)
Finds the roots of a cubic equation of the form:
template<typename Real >
std::array< Solution< Real >, 3 > cubic (Real c0, Real c1, Real c2, Real c3)
template<typename Tp >
void divmod (const Polynomial< Tp > &num, const Polynomial< Tp > &den, Polynomial< Tp > &quo, Polynomial< Tp > &rem)
template<typename Tp , std::size_t SizeN, std::size_t SizeD>
constexpr divmod_t< Tp, SizeN, SizeD > divmod (StaticPolynomial< Tp, SizeN > num, StaticPolynomial< Tp, SizeD > den)
float exp10f (float x)
double exp10log (double x)
long double exp10logl (long double x)
template<typename Tp >
std::complex< Tp > expm1 (const std::complex< Tp > &z)
template<typename Tp >
std::complex< Tp > fma (const std::complex< Tp > &a, const std::complex< Tp > &z, const std::complex< Tp > &b)
constexpr frexp_t< double > frexp (double value)
constexpr frexp_t< float > frexp (float value)
constexpr frexp_t< long double > frexp (long double value)
constexpr frexp_t< float > frexpf (float value)
constexpr frexp_t< long double > frexpl (long double value)
template<typename Tp >
real_type_t< Polynomial< Tp > > get_scale (const Polynomial< Tp > &poly)
template<typename Tp >
decltype(std::abs(Tp())) get_scale (const Tp &x)
template<typename ArgT , typename Coef0 , typename... Coef>
constexpr std::conditional_t< std::is_integral< ArgT >::value, double, ArgT > horner (ArgT x, Coef0 c0, Coef... c)
template<typename ArgT , typename Coef0 >
constexpr std::conditional_t< std::is_integral< ArgT >::value, double, ArgT > horner (ArgT, Coef0 c0)
template<typename ArgT , typename Coef1 , typename Coef0 >
constexpr std::conditional_t< std::is_integral< ArgT >::value, double, ArgT > horner_big_end (ArgT x, Coef1 c1, Coef0 c0)
template<typename ArgT , typename CoefN , typename CoefNm1 , typename... Coef>
constexpr std::conditional_t< std::is_integral< ArgT >::value, double, ArgT > horner_big_end (ArgT x, CoefN cn, CoefNm1 cnm1, Coef... c)
template<typename ArgT , typename Coef0 >
constexpr std::conditional_t< std::is_integral< ArgT >::value, double, ArgT > horner_big_end (ArgT, Coef0 c0)
template<typename Real >
constexpr Real imag (const Solution< Real > &x)
constexpr intmaxquot_t intmaxquot (std::intmax_t x, std::intmax_t y)
template<typename Real >
constexpr bool is_valid (const Solution< Real > &x)
constexpr llquot_t llquot (long long int numer, long long int denom)
double log (double base, double x)
template<typename Tp >
std::complex< Tp > log1p (const std::complex< Tp > &z)
float logf (float base, float x)
long double logl (long double base, long double x)
constexpr lquot_t lquot (long int numer, long int denom)
constexpr modf_t< double > modf (double value)
constexpr modf_t< float > modf (float value)
constexpr modf_t< long double > modf (long double value)
constexpr modf_t< float > modff (float value)
constexpr modf_t< long double > modfl (long double value)
constexpr double nan ()
constexpr float nanf ()
constexpr long double nanl ()
template<typename Tp >
bool operator!= (const Polynomial< Tp > &pa, const Polynomial< Tp > &pb)
template<typename Real >
constexpr bool operator!= (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr bool operator!= (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
bool operator!= (const Solution< Real > &x, Real y)
template<typename Tp , std::size_t Size>
constexpr bool operator!= (const StaticPolynomial< Tp, Size > &pa, const StaticPolynomial< Tp, Size > &pb)
template<typename Tp , std::size_t SizeA, std::size_t SizeB>
constexpr bool operator!= (const StaticPolynomial< Tp, SizeA > &pa, const StaticPolynomial< Tp, SizeB > &pb)
template<typename Real >
constexpr bool operator!= (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr bool operator!= (Real x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()/Up())> operator% (const Polynomial< Tp > &pa, const Polynomial< Up > &pb)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()/Up())> operator% (const Polynomial< Tp > &poly, const Up &x)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()/Up())> operator% (const Tp &x, const Polynomial< Up > &poly)
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial< Tp, divmod_t< Tp, SizeP, SizeQ >::SizeRem > operator% (StaticPolynomial< Tp, SizeP > P, StaticPolynomial< Tp, SizeQ > Q)
template<typename Tp , typename Up >
Polynomial< decltype(Tp() *Up())> operator* (const Polynomial< Tp > &pa, const Polynomial< Up > &pb)
template<typename Tp , typename Up >
Polynomial< decltype(Tp() *Up())> operator* (const Polynomial< Tp > &poly, const Up &x)
template<typename Real >
constexpr Solution< Real > operator* (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr Solution< Real > operator* (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
constexpr Solution< Real > operator* (const Solution< Real > &x, Real y)
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial< Tp, Size > operator* (const StaticPolynomial< Tp, Size > &poly, const Tp &x)
template<typename Real >
constexpr Solution< Real > operator* (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp() *Up())> operator* (const Tp &x, const Polynomial< Up > &poly)
template<typename Tp , std::size_t Size>
StaticPolynomial< Tp, Size > operator* (const Tp &x, const StaticPolynomial< Tp, Size > &poly)
template<typename Real >
constexpr Solution< Real > operator* (Real x, const Solution< Real > &y)
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial< Tp, SizeP+SizeQ - 1 > operator* (StaticPolynomial< Tp, SizeP > P, StaticPolynomial< Tp, SizeQ > Q)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()+Up())> operator+ (const Polynomial< Tp > &pa, const Polynomial< Up > &pb)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()+Up())> operator+ (const Polynomial< Tp > &poly, const Up &x)
template<typename Real >
constexpr Solution< Real > operator+ (const Solution< Real > &x)
template<typename Real >
constexpr Solution< Real > operator+ (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr Solution< Real > operator+ (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
constexpr Solution< Real > operator+ (const Solution< Real > &x, Real y)
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial< Tp, Size > operator+ (const StaticPolynomial< Tp, Size > &poly, const Tp &x)
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial< Tp, std::max(SizeP, SizeQ)> operator+ (const StaticPolynomial< Tp, SizeP > &P, const StaticPolynomial< Tp, SizeQ > &Q)
template<typename Real >
constexpr Solution< Real > operator+ (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()+Up())> operator+ (const Tp &x, const Polynomial< Up > &poly)
template<typename Tp , std::size_t Size>
StaticPolynomial< Tp, Size > operator+ (const Tp &x, const StaticPolynomial< Tp, Size > &poly)
template<typename Real >
constexpr Solution< Real > operator+ (Real x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp() - Up())> operator- (const Polynomial< Tp > &pa, const Polynomial< Up > &pb)
template<typename Tp , typename Up >
Polynomial< decltype(Tp() - Up())> operator- (const Polynomial< Tp > &poly, const Up &x)
template<typename Real >
constexpr Solution< Real > operator- (const Solution< Real > &x)
template<typename Real >
constexpr Solution< Real > operator- (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr Solution< Real > operator- (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
constexpr Solution< Real > operator- (const Solution< Real > &x, Real y)
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial< Tp, Size > operator- (const StaticPolynomial< Tp, Size > &poly, const Tp &x)
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial< Tp, std::max(SizeP, SizeQ)> operator- (const StaticPolynomial< Tp, SizeP > &P, const StaticPolynomial< Tp, SizeQ > &Q)
template<typename Real >
constexpr Solution< Real > operator- (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp() - Up())> operator- (const Tp &x, const Polynomial< Up > &poly)
template<typename Tp , std::size_t Size>
StaticPolynomial< Tp, Size > operator- (const Tp &x, const StaticPolynomial< Tp, Size > &poly)
template<typename Real >
constexpr Solution< Real > operator- (Real x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()/Up())> operator/ (const Polynomial< Tp > &pa, const Polynomial< Up > &pb)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()/Up())> operator/ (const Polynomial< Tp > &poly, const Up &x)
template<typename Real >
constexpr Solution< Real > operator/ (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr Solution< Real > operator/ (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
constexpr Solution< Real > operator/ (const Solution< Real > &x, Real y)
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial< Tp, Size > operator/ (const StaticPolynomial< Tp, Size > &poly, const Tp &x)
template<typename Real >
constexpr Solution< Real > operator/ (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Tp , typename Up >
Polynomial< decltype(Tp()/Up())> operator/ (const Tp &x, const Polynomial< Up > &poly)
template<typename Real >
constexpr Solution< Real > operator/ (Real x, const Solution< Real > &y)
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial< Tp, divmod_t< Tp, SizeP, SizeQ >::SizeQuo > operator/ (StaticPolynomial< Tp, SizeP > P, StaticPolynomial< Tp, SizeQ > Q)
template<typename Real >
constexpr bool operator< (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr bool operator< (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
constexpr bool operator< (const Solution< Real > &x, Real y)
template<typename Real >
constexpr bool operator< (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr bool operator< (Real x, const Solution< Real > &y)
template<typename Char , typename Real >
std::basic_ostream< Char > & operator<< (std::basic_ostream< Char > &out, const emsr::Solution< Real > &sln)
template<typename CharT , typename Traits , typename Tp >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, const Polynomial< Tp > &poly)
template<typename CharT , typename Traits , typename Tp >
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, const RationalPolynomial< Tp > &poly)
template<typename CharT , typename Traits , typename Tp , std::size_t Size>
std::basic_ostream< CharT, Traits > & operator<< (std::basic_ostream< CharT, Traits > &os, const StaticPolynomial< Tp, Size > &poly)
template<typename Tp >
bool operator== (const Polynomial< Tp > &pa, const Polynomial< Tp > &pb)
template<typename Real >
constexpr bool operator== (const Solution< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr bool operator== (const Solution< Real > &x, const std::complex< Real > &y)
template<typename Real >
bool operator== (const Solution< Real > &x, Real y)
template<typename Tp , std::size_t Size>
constexpr bool operator== (const StaticPolynomial< Tp, Size > &pa, const StaticPolynomial< Tp, Size > &pb)
template<typename Tp , std::size_t SizeA, std::size_t SizeB>
constexpr bool operator== (const StaticPolynomial< Tp, SizeA > &, const StaticPolynomial< Tp, SizeB > &)
template<typename Real >
constexpr bool operator== (const std::complex< Real > &x, const Solution< Real > &y)
template<typename Real >
constexpr bool operator== (Real x, const Solution< Real > &y)
template<typename CharT , typename Traits , typename Tp >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &is, Polynomial< Tp > &poly)
template<typename CharT , typename Traits , typename Tp >
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &is, RationalPolynomial< Tp > &poly)
template<typename Real , typename _Iter >
std::array< Solution< Real >, 2 > quadratic (const _Iter &_CC)
Finds the roots of a quadratic equation of the form:
template<typename Real , typename Iter >
std::array< Solution< Real >, 2 > quadratic (const Iter &coef)
template<typename Real >
std::array< Solution< Real >, 2 > quadratic (Real c0, Real c1, Real c2)
template<typename Real , typename Iter >
std::array< Solution< Real >, 4 > quartic (const Iter &CC)
Finds the roots a quartic equation of the form:
template<typename Real >
std::array< Solution< Real >, 4 > quartic (Real c0, Real c1, Real c2, Real c3, Real c4)
constexpr quot_t quot (int numer, int denom)
constexpr lquot_t quot (long int numer, long int denom)
constexpr llquot_t quot (long long int numer, long long int denom)
constexpr squot_t quot (short int numer, short int denom)
constexpr intmaxquot_t quot (std::intmax_t x, std::intmax_t y)
template<typename Real >
constexpr Real real (const Solution< Real > &x)
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp refine_solution_halley (_NumTp z, const _Iter &_CC)
template<std::size_t Dim, typename Iter , typename NumTp >
NumTp refine_solution_halley (NumTp z, const Iter &CC)
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp refine_solution_newton (_NumTp z, const _Iter &_CC)
template<std::size_t Dim, typename Iter , typename NumTp >
NumTp refine_solution_newton (NumTp z, const Iter &CC)
template<std::size_t _Dim, typename _Iter , typename Real >
void refine_solutions (std::array< Solution< Real >, _Dim - 1 > &_ZZ, const _Iter &_CC)
constexpr remquo_t< double > remquo (double x, double y)
constexpr remquo_t< float > remquo (float x, float y)
constexpr remquo_t< long double > remquo (long double x, long double y)
constexpr remquo_t< float > remquof (float x, float y)
constexpr remquo_t< long double > remquol (long double x, long double y)
double sec (double x)
double sec_pi (double x)
double sec_pi (reperiod_t< double > x)
float sec_pif (float x)
float sec_pif (reperiod_t< float > x)
long double sec_pil (long double x)
long double sec_pil (reperiod_t< long double > x)
float secf (float x)
double sech (double x)
float sechf (float x)
long double sechl (long double x)
long double secl (long double x)
template<typename Tp >
Tp sign (Tp x)
template<typename Tp >
Tp signum (Tp x)
double sin_pi (double x)
double sin_pi (reperiod_t< double > x)
float sin_pif (float x)
float sin_pif (reperiod_t< float > x)
long double sin_pil (long double x)
long double sin_pil (reperiod_t< long double > x)
sincos_t< double > sincos (double x)
sincos_t< double > sincos_pi (double x)
sincos_t< double > sincos_pi (reperiod_t< double > x)
sincos_t< float > sincos_pif (float x)
sincos_t< float > sincos_pif (reperiod_t< float > x)
sincos_t< long double > sincos_pil (long double x)
sincos_t< long double > sincos_pil (reperiod_t< long double > x)
sincos_t< float > sincosf (float x)
sincos_t< long double > sincosl (long double x)
sinhcosh_t< double > sinhcosh (double x)
sinhcosh_t< float > sinhcoshf (float x)
sinhcosh_t< long double > sinhcoshl (long double x)
lgamma_t< double > slgamma (double x)
lgamma_t< float > slgammaf (float x)
lgamma_t< long double > slgammal (long double x)
constexpr squot_t squot (short int numer, short int denom)
template<typename Tp >
void swap (Polynomial< Tp > &pa, Polynomial< Tp > &pb) noexcept(noexcept(pa.swap(pb)))
double tan_pi (double x)
double tan_pi (reperiod_t< double > x)
float tan_pif (float x)
float tan_pif (reperiod_t< float > x)
long double tan_pil (long double x)
long double tan_pil (reperiod_t< long double > x)
template<typename Real >
constexpr Solution< Real > to_complex (const Solution< Real > &x)
Variables
template<typename Tp >
constexpr auto has_imag_v = has_imag_t<Tp>::value
template<typename Tp >
constexpr auto has_value_type_v = has_value_type_t<Tp>::value
template<typename Tp >
Tp pi_v = static_cast<Tp>(3.1415926536897932384626L)
Detailed Description
This class is a dense univariate polynomial.
This polynomial has a size of at least one - degree 0. The zero polynomial has a_0 = 0. There is no null polynomial. size == degree + 1
How to handle division? operator/ returns the quotient of two polynomials discarding the remainder. operator% returns the remainder of two polynomials discarding the quotient. The divmod functions computes both the quotient and the remainder. N. B. I could add the remquo function?
Largest coefficient: This class does not enforce the coefficient of largest power to be nonzero. The user concerned about this should use the deflate method with a tolerance for the minimim magnitude coefficient. This library provides another deflate method that divides out a polynomial that is expected to factor the polynomial within a tolerance on the minimim magnitude coefficient. If the remainder is non-zero then an exception is thrown.
Mixed-type evaluation: It is common to have integer coefficient polynomials that you wish to evaluate at floating opint or complex values, or real-valued coefficient polynomials evaluate at complex values. For this reason we need evaluation function templates in this library.
It would be promote_t<complex::value_type> for complex.
Typedef Documentation
intmaxquot_t
using emsr::intmaxquot_t = typedef int_quot_t<std::intmax_t>
Definition at line 83 of file notsospecfun.h.
llquot_t
using emsr::llquot_t = typedef int_quot_t<long long int>
Definition at line 82 of file notsospecfun.h.
lquot_t
using emsr::lquot_t = typedef int_quot_t<long int>
Definition at line 81 of file notsospecfun.h.
quot_t
using emsr::quot_t = typedef int_quot_t<int>
Definition at line 80 of file notsospecfun.h.
real_type_t
template<typename Tp >
using emsr::real_type_t = typedef typename real_type<Tp>::type
Definition at line 125 of file polynomial.h.
squot_t
using emsr::squot_t = typedef int_quot_t<short int>
Definition at line 79 of file notsospecfun.h.
Function Documentation
abs()
template<typename Real >
constexpr Real emsr::abs (const Solution< Real > & x) [constexpr]
Definition at line 97 of file solution.h.
    {
      if (x.index() == 0)
        return std::numeric_limits<Real>::quiet_NaN();
      else if (x.index() == 1)
        return std::abs(std::get<1>(x));
      else
        return std::abs(std::get<2>(x));
    }
Referenced by cubic(), emsr::Polynomial< Tp >::deflate(), get_scale(), norm_l1(), emsr::Polynomial< Tp >::operator()(), quadratic(), quartic(), and emsr::JenkinsTraubSolver< Real >::solve().
acot() [1/2]
double emsr::acot (double x)
acot() [2/2]
double emsr::acot (sincos_t< double > m)
acot2()
double emsr::acot2 (double x, double y)
acot2_pi()
reperiod_t<double> emsr::acot2_pi (double y, double x)
acot2_pif()
reperiod_t<float> emsr::acot2_pif (float y, float x)
acot2_pil()
reperiod_t<long double> emsr::acot2_pil (long double y, long double x)
acot2f()
float emsr::acot2f (float x, float y)
acot2l()
long double emsr::acot2l (long double x, long double y)
acot_pi() [1/2]
reperiod_t<double> emsr::acot_pi (double m)
acot_pi() [2/2]
reperiod_t<double> emsr::acot_pi (sincos_t< double > m)
acot_pif() [1/2]
reperiod_t<float> emsr::acot_pif (float m)
acot_pif() [2/2]
reperiod_t<float> emsr::acot_pif (sincos_t< float > m)
acot_pil() [1/2]
reperiod_t<long double> emsr::acot_pil (long double m)
acot_pil() [2/2]
reperiod_t<long double> emsr::acot_pil (sincos_t< long double > m)
acotf() [1/2]
float emsr::acotf (float x)
acotf() [2/2]
float emsr::acotf (sincos_t< float > m)
acoth() [1/2]
double emsr::acoth (double x)
acoth() [2/2]
double emsr::acoth (sinhcosh_t< double > m)
acothf() [1/2]
float emsr::acothf (float x)
acothf() [2/2]
float emsr::acothf (sinhcosh_t< float > m)
acothl() [1/2]
long double emsr::acothl (long double x)
acothl() [2/2]
long double emsr::acothl (sinhcosh_t< long double > m)
acotl() [1/2]
long double emsr::acotl (long double x)
acotl() [2/2]
long double emsr::acotl (sincos_t< long double > m)
acsc()
double emsr::acsc (double x)
acscf()
float emsr::acscf (float x)
acsch()
double emsr::acsch (double x)
acschf()
float emsr::acschf (float x)
acschl()
long double emsr::acschl (long double x)
acscl()
long double emsr::acscl (long double x)
asec()
double emsr::asec (double x)
asecf()
float emsr::asecf (float x)
asech()
double emsr::asech (double x)
asechf()
float emsr::asechf (float x)
asechl()
long double emsr::asechl (long double x)
asecl()
long double emsr::asecl (long double x)
atan()
double emsr::atan (sincos_t< double > m)
atan2_pi()
reperiod_t<double> emsr::atan2_pi (double y, double x)
atan2_pif()
reperiod_t<float> emsr::atan2_pif (float y, float x)
atan2_pil()
reperiod_t<long double> emsr::atan2_pil (long double y, long double x)
atan_pi() [1/2]
reperiod_t<double> emsr::atan_pi (double m)
atan_pi() [2/2]
reperiod_t<double> emsr::atan_pi (sincos_t< double > m)
atan_pif() [1/2]
reperiod_t<float> emsr::atan_pif (float m)
atan_pif() [2/2]
reperiod_t<float> emsr::atan_pif (sincos_t< float > m)
atan_pil() [1/2]
reperiod_t<long double> emsr::atan_pil (long double m)
atan_pil() [2/2]
reperiod_t<long double> emsr::atan_pil (sincos_t< long double > m)
atanf()
float emsr::atanf (sincos_t< float > m)
atanh()
double emsr::atanh (sinhcosh_t< double > m)
atanhf()
float emsr::atanhf (sinhcosh_t< float > m)
atanhl()
long double emsr::atanhl (sinhcosh_t< long double > m)
atanl()
long double emsr::atanl (sincos_t< long double > m)
cos_pi() [1/2]
double emsr::cos_pi (double x)
cos_pi() [2/2]
double emsr::cos_pi (reperiod_t< double > x)
cos_pif() [1/2]
float emsr::cos_pif (float x)
cos_pif() [2/2]
float emsr::cos_pif (reperiod_t< float > x)
cos_pil() [1/2]
long double emsr::cos_pil (long double x)
cos_pil() [2/2]
long double emsr::cos_pil (reperiod_t< long double > x)
cot()
double emsr::cot (double x)
cot_pi() [1/2]
double emsr::cot_pi (double x)
cot_pi() [2/2]
double emsr::cot_pi (reperiod_t< double > x)
cot_pif() [1/2]
float emsr::cot_pif (float x)
cot_pif() [2/2]
float emsr::cot_pif (reperiod_t< float > x)
cot_pil() [1/2]
long double emsr::cot_pil (long double x)
cot_pil() [2/2]
long double emsr::cot_pil (reperiod_t< long double > x)
cotf()
float emsr::cotf (float x)
coth()
double emsr::coth (double x)
cothf()
float emsr::cothf (float x)
cothl()
long double emsr::cothl (long double x)
cotl()
long double emsr::cotl (long double x)
csc()
double emsr::csc (double x)
csc_pi() [1/2]
double emsr::csc_pi (double x)
csc_pi() [2/2]
double emsr::csc_pi (reperiod_t< double > x)
csc_pif() [1/2]
float emsr::csc_pif (float x)
csc_pif() [2/2]
float emsr::csc_pif (reperiod_t< float > x)
csc_pil() [1/2]
long double emsr::csc_pil (long double x)
csc_pil() [2/2]
long double emsr::csc_pil (reperiod_t< long double > x)
cscf()
float emsr::cscf (float x)
csch()
double emsr::csch (double x)
cschf()
float emsr::cschf (float x)
cschl()
long double emsr::cschl (long double x)
cscl()
long double emsr::cscl (long double x)
cubic() [1/2]
template<typename Real , typename Iter >
std::array< Solution< Real >, 3 > emsr::cubic (const Iter & CC)
Finds the roots of a cubic equation of the form:
 a_3 x^3 + a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
In the non-degenerate case there are three roots:
All three roots are real
One root is real and the other two are a complex conjugate pair
If the cubic coefficient $ a_3 $ is zero (degenerate case) the problem is referred to the quadratic solver to return, at most, two valid roots.
Parameters
 in _CC Array that contains the four coefficients of the cubic equation
Definition at line 216 of file solver_low_degree.tcc.
    {
      std::array<Solution<Real>, 3> ZZ;
      if (CC[3] == Real{0})
        {
          // Last root is null, remaining equation is quadratic.
          const auto ZZ2 = quadratic<Real>(CC);
          ZZ[0] = ZZ2[0];
          ZZ[1] = ZZ2[1];
        }
      else if (CC[0] == Real{0})
        {
          // First root is zero, remaining equation is quadratic.
          ZZ[0] = Real{0};
          const auto ZZ2 = quadratic<Real>(CC[1], CC[2], CC[3]);
          ZZ[1] = ZZ2[0];
          ZZ[2] = ZZ2[1];
        }
      else
        {
          // Normalize cubic equation coefficients.
          std::array<Real, 4> AA3;
          AA3[3] = Real{1};
          AA3[2] = CC[2] / CC[3];
          AA3[1] = CC[1] / CC[3];
          AA3[0] = CC[0] / CC[3];
          const auto S_2pi
            = 2 * Real{3.1415'92653'58979'32384'62643'38327'95028'84195e+0L};
          const auto PP = AA3[2] / Real{3};
          const auto QQ = (AA3[2] * AA3[2] - Real{3} * AA3[1])
                         / Real{9};
          const auto QQp3 = QQ * QQ * QQ;
          const auto RR = (Real{2} * AA3[2] * AA3[2] * AA3[2]
                          - Real{9} * AA3[2] * AA3[1]
                          + Real{27} * AA3[0]) / Real{54};
          const auto RRp2 = RR * RR;
          if (QQp3 - RRp2 > Real{0})
            {
              // Calculate the three real roots.
              const auto phi = std::acos(RR / std::sqrt(QQp3));
              const auto fact = -Real{2} * std::sqrt(QQ);
              for (int i = 0; i < 3; ++i)
                ZZ[i] = fact * std::cos((phi + i * S_2pi) / Real{3}) - PP;
            }
          else
            {
              // Calculate the single real root.
              const auto fact = std::cbrt(std::abs(RR)
                                          + std::sqrt(RRp2 - QQp3));
              const auto BB = -std::copysign(fact + QQ / fact, RR);
              ZZ[0] = BB - PP;
              // Find the other two roots which are complex conjugates.
              std::array<Real, 3> AA2;
              AA2[2] = Real{1};
              AA2[1] = BB;
              AA2[0] = BB * BB - Real{3} * QQ;
              const auto ZZ2 = quadratic<Real>(AA2);
              ZZ[1] = std::get<2>(ZZ2[0]) - PP;
              ZZ[2] = std::get<2>(ZZ2[1]) - PP;
            }
        }
      return ZZ;
    }
References abs().
cubic() [2/2]
template<typename Real >
std::array<Solution<Real>, 3> emsr::cubic (Real c0, Real c1, Real c2, Real c3) [inline]
Definition at line 73 of file solver_low_degree.h.
    {
      return cubic<Real>(std::array<Real, 4>{c0, c1, c2, c3});
    }
divmod() [1/2]
template<typename Tp >
void emsr::divmod (const Polynomial< Tp > & num, const Polynomial< Tp > & den, Polynomial< Tp > & quo, Polynomial< Tp > & rem)
Divide two polynomials returning the quotient and remainder.
Definition at line 385 of file polynomial.tcc.
    {
      rem = num;
      quo = Polynomial<Tp>(Tp{}, num.degree());
      const std::size_t d_num = num.degree();
      const std::size_t d_den = den.degree();
      if (d_den <= d_num)
        {
          for (int k = d_num - d_den; k >= 0; --k)
            {
              quo.coefficient(k, rem.coefficient(d_den + k)
                                   / den.coefficient(d_den));
              for (int j = d_den + k - 1; j >= k; --j)
                rem.coefficient(j, rem.coefficient(j)
                                     - quo.coefficient(k)
                                     * den.coefficient(j - k));
            }
          quo.degree(d_num - d_den);
          rem.degree(d_den > 0 ? d_den - 1 : 0);
        }
      else
        quo.degree(0);
    }
References emsr::Polynomial< Tp >::coefficient(), and emsr::Polynomial< Tp >::degree().
Referenced by emsr::Polynomial< Tp >::deflate(), operator%(), emsr::Polynomial< Tp >::operator%=(), operator/(), and emsr::Polynomial< Tp >::operator/=().
divmod() [2/2]
template<typename Tp , std::size_t SizeN, std::size_t SizeD>
constexpr divmod_t< Tp, SizeN, SizeD > emsr::divmod (StaticPolynomial< Tp, SizeN > num, StaticPolynomial< Tp, SizeD > den) [constexpr]
Divide two polynomials returning the quotient and remainder.
Definition at line 65 of file static_polynomial.tcc.
    {
      constexpr auto DegN = num.degree();
      constexpr auto DegD = den.degree();
      auto rem = num;
      auto quo = StaticPolynomial<Tp, SizeN>{};
      if (DegD <= DegN)
        {
          for (std::ptrdiff_t k = DegN - DegD; k >= 0; --k)
            {
              quo.coefficient(k, rem.coefficient(DegD + k)
                                   / den.coefficient(DegD));
              for (int j = DegD + k - 1; j >= k; --j)
                rem.coefficient(j, rem.coefficient(j)
                                       - quo.coefficient(k)
                                       * den.coefficient(j - k));
            }
        }
      divmod_t<Tp, SizeN, SizeD> ret;
      for (std::size_t i = 0ULL; i < divmod_t<Tp, SizeN, SizeD>::SizeQuo; ++i)
        ret.quo[i] = quo[i];
      for (std::size_t i = 0ULL; i < divmod_t<Tp, SizeN, SizeD>::SizeRem; ++i)
        ret.rem[i] = rem[i];
      return ret;
    }
References emsr::StaticPolynomial< Tp, Size >::coefficient(), emsr::StaticPolynomial< Tp, Size >::degree(), emsr::divmod_t< Tp, SizeN, SizeD >::quo, and emsr::divmod_t< Tp, SizeN, SizeD >::rem.
exp10f()
float emsr::exp10f (float x)
exp10log()
double emsr::exp10log (double x)
exp10logl()
long double emsr::exp10logl (long double x)
expm1()
template<typename Tp >
std::complex<Tp> emsr::expm1 (const std::complex< Tp > & z) [inline]
Give complex expm1. This and log1p are inverses of each other.
Todo
Todo Do a better complex log1p implementation.
Definition at line 482 of file notsospecfun.h.
    {
      /// @todo Do a better complex log1p implementation.
      return std::exp(z) - Tp{1};
    }
fma()
template<typename Tp >
std::complex<Tp> emsr::fma (const std::complex< Tp > & a, const std::complex< Tp > & z, const std::complex< Tp > & b) [inline]
Give complex an fma.
Definition at line 454 of file notsospecfun.h.
    {
      const auto [ar, ai] = reinterpret_cast<const Tp(&)[2]>(a);
      const auto [zr, zi] = reinterpret_cast<const Tp(&)[2]>(z);
      const auto [br, bi] = reinterpret_cast<const Tp(&)[2]>(b);
      const auto wr = std::fma(ar, ai, -std::fma(ai, zi, -br));
      const auto wi = std::fma(ar, zi, std::fma(ai, zr, bi));
      return {wr, wi};
    }
Referenced by emsr::Polynomial< Tp >::eval(), emsr::Polynomial< Tp >::eval_even(), and emsr::Polynomial< Tp >::eval_odd().
frexp() [1/3]
constexpr frexp_t<double> emsr::frexp (double value) [constexpr]
frexp() [2/3]
constexpr frexp_t<float> emsr::frexp (float value) [constexpr]
frexp() [3/3]
constexpr frexp_t<long double> emsr::frexp (long double value) [constexpr]
frexpf()
constexpr frexp_t<float> emsr::frexpf (float value) [constexpr]
frexpl()
constexpr frexp_t<long double> emsr::frexpl (long double value) [constexpr]
get_scale() [1/2]
template<typename Tp >
real_type_t<Polynomial<Tp> > emsr::get_scale (const Polynomial< Tp > & poly)
Return the scale for a polynomial.
Definition at line 889 of file polynomial.h.
    { return poly.m_get_scale(); }
get_scale() [2/2]
template<typename Tp >
decltype(std::abs(Tp())) emsr::get_scale (const Tp & x)
Return the scale for a number.
Definition at line 897 of file polynomial.h.
    { return std::abs(x); }
References abs().
horner() [1/2]
template<typename ArgT , typename Coef0 , typename... Coef>
constexpr std::conditional_t<std::is_integral<ArgT>::value, double, ArgT> emsr::horner (ArgT x, Coef0 c0, Coef... c) [constexpr]
Perform compile-time evaluation of a constant polynomial. The polynomial coefficients are lowest-order first.
Definition at line 55 of file horner.h.
  {
    using arg_t = std::conditional_t<std::is_integral<ArgT>::value,
                                        double, ArgT>;
    return arg_t{c0} + x * horner(x, c...);
  }
References horner().
horner() [2/2]
template<typename ArgT , typename Coef0 >
constexpr std::conditional_t<std::is_integral<ArgT>::value, double, ArgT> emsr::horner (ArgT , Coef0 c0) [constexpr]
Perform compile-time evaluation of a constant zero-order polynomial.
Definition at line 42 of file horner.h.
  {
    using arg_t = std::conditional_t<std::is_integral<ArgT>::value,
                                        double, ArgT>;
    return arg_t{c0};
  }
Referenced by horner().
horner_big_end() [1/3]
template<typename ArgT , typename Coef1 , typename Coef0 >
constexpr std::conditional_t<std::is_integral<ArgT>::value, double, ArgT> emsr::horner_big_end (ArgT x, Coef1 c1, Coef0 c0) [constexpr]
Perform compile-time evaluation of a constant first-order polynomial. The polynomial coefficients are highest-order first.
Definition at line 82 of file horner.h.
  {
    using arg_t = std::conditional_t<std::is_integral<ArgT>::value,
                                        double, ArgT>;
    return horner_big_end(x, x * arg_t{c1} + arg_t{c0});
  }
References horner_big_end().
horner_big_end() [2/3]
template<typename ArgT , typename CoefN , typename CoefNm1 , typename... Coef>
constexpr std::conditional_t<std::is_integral<ArgT>::value, double, ArgT> emsr::horner_big_end (ArgT x, CoefN cn, CoefNm1 cnm1, Coef... c) [constexpr]
Perform compile-time evaluation of a constant polynomial. The polynomial coefficients are highest-order first.
Definition at line 95 of file horner.h.
  {
    using arg_t = std::conditional_t<std::is_integral<ArgT>::value,
                                        double, ArgT>;
    return horner_big_end(x, x * arg_t{cn} + arg_t{cnm1}, c...);
  }
References horner_big_end().
horner_big_end() [3/3]
template<typename ArgT , typename Coef0 >
constexpr std::conditional_t<std::is_integral<ArgT>::value, double, ArgT> emsr::horner_big_end (ArgT , Coef0 c0) [constexpr]
Perform compile-time evaluation of a constant zero-order polynomial. The polynomial coefficients are highest-order first.
Definition at line 69 of file horner.h.
  {
    using arg_t = std::conditional_t<std::is_integral<ArgT>::value,
                                        double, ArgT>;
    return arg_t{c0};
  }
Referenced by horner_big_end().
imag()
template<typename Real >
constexpr Real emsr::imag (const Solution< Real > & x) [constexpr]
Definition at line 85 of file solution.h.
    {
      if (x.index() == 0)
        return std::numeric_limits<Real>::quiet_NaN();
      else if (x.index() == 1)
        return Real{0};
      else
        return std::imag(std::get<2>(x));
    }
Referenced by norm_l1(), and operator<().
intmaxquot()
constexpr intmaxquot_t emsr::intmaxquot (std::intmax_t x, std::intmax_t y) [constexpr]
is_valid()
template<typename Real >
constexpr bool emsr::is_valid (const Solution< Real > & x) [constexpr]
Definition at line 68 of file solution.h.
    { return x.index() != 0; }
llquot()
constexpr llquot_t emsr::llquot (long long int numer, long long int denom) [constexpr]
log()
double emsr::log (double base, double x)
Referenced by log1p(), and emsr::JenkinsTraubSolver< Real >::solve().
log1p()
template<typename Tp >
std::complex<Tp> emsr::log1p (const std::complex< Tp > & z) [inline]
Give complex log1p.
Todo
Todo Do a better complex log1p implementation.
Definition at line 470 of file notsospecfun.h.
    {
      /// @todo Do a better complex log1p implementation.
      return std::log(Tp{1} + z);
    }
References log().
logf()
float emsr::logf (float base, float x)
logl()
long double emsr::logl (long double base, long double x)
lquot()
constexpr lquot_t emsr::lquot (long int numer, long int denom) [constexpr]
modf() [1/3]
constexpr modf_t<double> emsr::modf (double value) [constexpr]
modf() [2/3]
constexpr modf_t<float> emsr::modf (float value) [constexpr]
modf() [3/3]
constexpr modf_t<long double> emsr::modf (long double value) [constexpr]
modff()
constexpr modf_t<float> emsr::modff (float value) [constexpr]
modfl()
constexpr modf_t<long double> emsr::modfl (long double value) [constexpr]
nan()
constexpr double emsr::nan () [constexpr]
nanf()
constexpr float emsr::nanf () [constexpr]
nanl()
constexpr long double emsr::nanl () [constexpr]
operator!=() [1/8]
template<typename Tp >
bool emsr::operator!= (const Polynomial< Tp > & pa, const Polynomial< Tp > & pb) [inline]
Return false if two polynomials are equal.
Definition at line 1060 of file polynomial.h.
    { return !(pa == pb); }
operator!=() [2/8]
template<typename Real >
constexpr bool emsr::operator!= (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 372 of file solution.h.
    { return !(x == y); }
operator!=() [3/8]
template<typename Real >
constexpr bool emsr::operator!= (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 387 of file solution.h.
    { return !(x == y); }
operator!=() [4/8]
template<typename Real >
bool emsr::operator!= (const Solution< Real > & x, Real y)
Definition at line 377 of file solution.h.
    { return !(x == y); }
operator!=() [5/8]
template<typename Tp , std::size_t Size>
constexpr bool emsr::operator!= (const StaticPolynomial< Tp, Size > & pa, const StaticPolynomial< Tp, Size > & pb) [inline], [constexpr]
Return false if two polynomials are equal.
Definition at line 653 of file static_polynomial.h.
    { return !(pa == pb); }
operator!=() [6/8]
template<typename Tp , std::size_t SizeA, std::size_t SizeB>
constexpr bool emsr::operator!= (const StaticPolynomial< Tp, SizeA > & pa, const StaticPolynomial< Tp, SizeB > & pb) [inline], [constexpr]
Return false if two polynomials are equal.
Definition at line 644 of file static_polynomial.h.
    { return true; }
operator!=() [7/8]
template<typename Real >
constexpr bool emsr::operator!= (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 392 of file solution.h.
    { return !(x == y); }
operator!=() [8/8]
template<typename Real >
constexpr bool emsr::operator!= (Real x, const Solution< Real > & y) [constexpr]
Definition at line 382 of file solution.h.
    { return !(x == y); }
operator%() [1/4]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() / Up())> emsr::operator% (const Polynomial< Tp > & pa, const Polynomial< Up > & pb) [inline]
Return the modulus or remainder of one polynomial relative to another one.
Definition at line 1001 of file polynomial.h.
    { return Polynomial<decltype(Tp() / Up())>(pa) %= pb; }
operator%() [2/4]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() / Up())> emsr::operator% (const Polynomial< Tp > & poly, const Up & x) [inline]
Definition at line 961 of file polynomial.h.
    { return Polynomial<decltype(Tp() / Up())>(poly) %= x; }
operator%() [3/4]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() / Up())> emsr::operator% (const Tp & x, const Polynomial< Up > & poly) [inline]
Return the modulus or remainder of a scalar divided by a polynomial.
Definition at line 1017 of file polynomial.h.
    { return Polynomial<decltype(Tp() / Up())>(x) %= poly; }
operator%() [4/4]
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial<Tp, divmod_t<Tp, SizeP, SizeQ>::SizeRem> emsr::operator% (StaticPolynomial< Tp, SizeP > P, StaticPolynomial< Tp, SizeQ > Q) [inline], [constexpr]
Return the remainder of two polynomials.
Definition at line 803 of file static_polynomial.h.
    { return divmod(P, Q).rem; }
References divmod().
operator*() [1/11]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() * Up())> emsr::operator* (const Polynomial< Tp > & pa, const Polynomial< Up > & pb) [inline]
Return the product of two polynomials.
Definition at line 985 of file polynomial.h.
    { return Polynomial<decltype(Tp() * Up())>(pa) *= pb; }
operator*() [2/11]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() * Up())> emsr::operator* (const Polynomial< Tp > & poly, const Up & x) [inline]
Return the product of a polynomial with a scalar.
Definition at line 937 of file polynomial.h.
    { return Polynomial<decltype(Tp() * Up())>(poly) *= x; }
Referenced by operator*().
operator*() [3/11]
template<typename Real >
constexpr Solution<Real> emsr::operator* (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
Multiplication operators...
Definition at line 241 of file solution.h.
    {
      if (x.index() == 0)
        return x;
      if (y.index() == 0)
        return y;
      else if (x.index() == 1)
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<1>(x) * std::get<1>(y));
          else
            return Solution<Real>(std::get<1>(x) * std::get<2>(y));
        }
      else
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<2>(x) * std::get<1>(y));
          else
            return Solution<Real>(std::get<2>(x) * std::get<2>(y));
        }
    }
operator*() [4/11]
template<typename Real >
constexpr Solution<Real> emsr::operator* (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 275 of file solution.h.
    { return operator*(x, Solution<Real>(y)); }
References operator*().
operator*() [5/11]
template<typename Real >
constexpr Solution<Real> emsr::operator* (const Solution< Real > & x, Real y) [constexpr]
Definition at line 265 of file solution.h.
    { return operator*(x, Solution<Real>(y)); }
References operator*().
operator*() [6/11]
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial<Tp, Size> emsr::operator* (const StaticPolynomial< Tp, Size > & poly, const Tp & x) [inline], [constexpr]
Return the product of a polynomial with a scalar.
Definition at line 688 of file static_polynomial.h.
    { return StaticPolynomial<Tp, Size>(poly) *= x; }
operator*() [7/11]
template<typename Real >
constexpr Solution<Real> emsr::operator* (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 280 of file solution.h.
    { return operator*(Solution<Real>(x), y); }
References operator*().
operator*() [8/11]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() * Up())> emsr::operator* (const Tp & x, const Polynomial< Up > & poly) [inline]
Definition at line 945 of file polynomial.h.
    { return Polynomial<decltype(Tp() * Up())>(x) *= poly; }
operator*() [9/11]
template<typename Tp , std::size_t Size>
StaticPolynomial<Tp, Size> emsr::operator* (const Tp & x, const StaticPolynomial< Tp, Size > & poly) [inline]
Definition at line 693 of file static_polynomial.h.
    { return StaticPolynomial<Tp, Size>(poly) *= x; }
operator*() [10/11]
template<typename Real >
constexpr Solution<Real> emsr::operator* (Real x, const Solution< Real > & y) [constexpr]
Definition at line 270 of file solution.h.
    { return operator*(Solution<Real>(x), y); }
References operator*().
operator*() [11/11]
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial< Tp, SizeP+SizeQ - 1 > emsr::operator* (StaticPolynomial< Tp, SizeP > P, StaticPolynomial< Tp, SizeQ > Q) [inline], [constexpr]
Return the product of two polynomials.
Definition at line 746 of file static_polynomial.h.
    {
      StaticPolynomial<Tp, P.degree() + Q.degree() + 1> R;
      for (std::size_t i = 0; i <= P.degree(); ++i)
        for (std::size_t j = 0; j <= Q.degree(); ++j)
          R[i + j] = P[i] * Q[j];
      return R;
    }
References emsr::StaticPolynomial< Tp, Size >::degree().
operator+() [1/12]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() + Up())> emsr::operator+ (const Polynomial< Tp > & pa, const Polynomial< Up > & pb) [inline]
Return the sum of two polynomials.
Definition at line 969 of file polynomial.h.
    { return Polynomial<decltype(Tp() + Up())>(pa) += pb; }
operator+() [2/12]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() + Up())> emsr::operator+ (const Polynomial< Tp > & poly, const Up & x) [inline]
Return the sum of a polynomial with a scalar.
Definition at line 905 of file polynomial.h.
    { return Polynomial<decltype(Tp() + Up())>(poly) += x; }
Referenced by operator+().
operator+() [3/12]
template<typename Real >
constexpr Solution<Real> emsr::operator+ (const Solution< Real > & x) [constexpr]
Unary +/-
Definition at line 127 of file solution.h.
    { return x; }
operator+() [4/12]
template<typename Real >
constexpr Solution<Real> emsr::operator+ (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
Addition operators...
Definition at line 147 of file solution.h.
    {
      if (x.index() == 0)
        return x;
      if (y.index() == 0)
        return y;
      else if (x.index() == 1)
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<1>(x) + std::get<1>(y));
          else
            return Solution<Real>(std::get<1>(x) + std::get<2>(y));
        }
      else
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<2>(x) + std::get<1>(y));
          else
            return Solution<Real>(std::get<2>(x) + std::get<2>(y));
        }
    }
operator+() [5/12]
template<typename Real >
constexpr Solution<Real> emsr::operator+ (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 181 of file solution.h.
    { return operator+(x, Solution<Real>(y)); }
References operator+().
operator+() [6/12]
template<typename Real >
constexpr Solution<Real> emsr::operator+ (const Solution< Real > & x, Real y) [constexpr]
Definition at line 171 of file solution.h.
    { return operator+(x, Solution<Real>(y)); }
References operator+().
operator+() [7/12]
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial<Tp, Size> emsr::operator+ (const StaticPolynomial< Tp, Size > & poly, const Tp & x) [inline], [constexpr]
Return the sum of a polynomial with a scalar.
Definition at line 662 of file static_polynomial.h.
    { return StaticPolynomial<Tp, Size>(poly) += x; }
operator+() [8/12]
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial<Tp, std::max(SizeP, SizeQ)> emsr::operator+ (const StaticPolynomial< Tp, SizeP > & P, const StaticPolynomial< Tp, SizeQ > & Q) [inline], [constexpr]
Return the sum of two polynomials.
Definition at line 718 of file static_polynomial.h.
    {
      if constexpr (SizeP >= SizeQ)
        {
          StaticPolynomial<Tp, SizeP> R = P;
          for (std::size_t i = 0; i < SizeQ; ++i)
            R[i] += Q[i];
          return R;
        }
      else
        return Q + P;
    }
operator+() [9/12]
template<typename Real >
constexpr Solution<Real> emsr::operator+ (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 186 of file solution.h.
    { return operator+(Solution<Real>(x), y); }
References operator+().
operator+() [10/12]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() + Up())> emsr::operator+ (const Tp & x, const Polynomial< Up > & poly) [inline]
Definition at line 913 of file polynomial.h.
    { return Polynomial<decltype(Tp() + Up())>(x) += poly; }
operator+() [11/12]
template<typename Tp , std::size_t Size>
StaticPolynomial<Tp, Size> emsr::operator+ (const Tp & x, const StaticPolynomial< Tp, Size > & poly) [inline]
Definition at line 667 of file static_polynomial.h.
    { return StaticPolynomial<Tp, Size>(poly) += x; }
operator+() [12/12]
template<typename Real >
constexpr Solution<Real> emsr::operator+ (Real x, const Solution< Real > & y) [constexpr]
Definition at line 176 of file solution.h.
    { return operator+(Solution<Real>(x), y); }
References operator+().
operator-() [1/12]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() - Up())> emsr::operator- (const Polynomial< Tp > & pa, const Polynomial< Up > & pb) [inline]
Return the difference of two polynomials.
Definition at line 977 of file polynomial.h.
    { return Polynomial<decltype(Tp() - Up())>(pa) -= pb; }
operator-() [2/12]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() - Up())> emsr::operator- (const Polynomial< Tp > & poly, const Up & x) [inline]
Return the difference of a polynomial with a scalar.
Definition at line 921 of file polynomial.h.
    { return Polynomial<decltype(Tp() - Up())>(poly) -= x; }
Referenced by operator-().
operator-() [3/12]
template<typename Real >
constexpr Solution<Real> emsr::operator- (const Solution< Real > & x) [constexpr]
Definition at line 132 of file solution.h.
    {
      if (x.index() == 0)
        return x;
      else if (x.index() == 1)
        return Solution<Real>(-std::get<1>(x));
      else
        return Solution<Real>(-std::get<2>(x));
    }
operator-() [4/12]
template<typename Real >
constexpr Solution<Real> emsr::operator- (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
Subtraction operators...
Definition at line 194 of file solution.h.
    {
      if (x.index() == 0)
        return x;
      if (y.index() == 0)
        return y;
      else if (x.index() == 1)
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<1>(x) - std::get<1>(y));
          else
            return Solution<Real>(std::get<1>(x) - std::get<2>(y));
        }
      else
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<2>(x) - std::get<1>(y));
          else
            return Solution<Real>(std::get<2>(x) - std::get<2>(y));
        }
    }
operator-() [5/12]
template<typename Real >
constexpr Solution<Real> emsr::operator- (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 228 of file solution.h.
    { return operator-(x, Solution<Real>(y)); }
References operator-().
operator-() [6/12]
template<typename Real >
constexpr Solution<Real> emsr::operator- (const Solution< Real > & x, Real y) [constexpr]
Definition at line 218 of file solution.h.
    { return operator-(x, Solution<Real>(y)); }
References operator-().
operator-() [7/12]
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial<Tp, Size> emsr::operator- (const StaticPolynomial< Tp, Size > & poly, const Tp & x) [inline], [constexpr]
Return the difference of a polynomial with a scalar.
Definition at line 675 of file static_polynomial.h.
    { return StaticPolynomial<Tp, Size>(poly) -= x; }
operator-() [8/12]
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial<Tp, std::max(SizeP, SizeQ)> emsr::operator- (const StaticPolynomial< Tp, SizeP > & P, const StaticPolynomial< Tp, SizeQ > & Q) [inline], [constexpr]
Return the difference of two polynomials.
Definition at line 737 of file static_polynomial.h.
    { return P + -Q; }
operator-() [9/12]
template<typename Real >
constexpr Solution<Real> emsr::operator- (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 233 of file solution.h.
    { return operator-(Solution<Real>(x), y); }
References operator-().
operator-() [10/12]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() - Up())> emsr::operator- (const Tp & x, const Polynomial< Up > & poly) [inline]
Definition at line 929 of file polynomial.h.
    { return Polynomial<decltype(Tp() - Up())>(x) -= poly; }
operator-() [11/12]
template<typename Tp , std::size_t Size>
StaticPolynomial<Tp, Size> emsr::operator- (const Tp & x, const StaticPolynomial< Tp, Size > & poly) [inline]
Definition at line 680 of file static_polynomial.h.
    { return -StaticPolynomial<Tp, Size>(poly) += x; }
operator-() [12/12]
template<typename Real >
constexpr Solution<Real> emsr::operator- (Real x, const Solution< Real > & y) [constexpr]
Definition at line 223 of file solution.h.
    { return operator-(Solution<Real>(x), y); }
References operator-().
operator/() [1/10]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() / Up())> emsr::operator/ (const Polynomial< Tp > & pa, const Polynomial< Up > & pb) [inline]
Return the quotient of two polynomials.
Definition at line 993 of file polynomial.h.
    { return Polynomial<decltype(Tp() / Up())>(pa) /= pb; }
operator/() [2/10]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() / Up())> emsr::operator/ (const Polynomial< Tp > & poly, const Up & x) [inline]
Return the quotient of a polynomial with a scalar.
Definition at line 953 of file polynomial.h.
    { return Polynomial<decltype(Tp() / Up())>(poly) /= x; }
Referenced by operator/().
operator/() [3/10]
template<typename Real >
constexpr Solution<Real> emsr::operator/ (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
division operators...
Definition at line 288 of file solution.h.
    {
      if (x.index() == 0)
        return x;
      if (y.index() == 0)
        return y;
      else if (x.index() == 1)
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<1>(x) / std::get<1>(y));
          else
            return Solution<Real>(std::get<1>(x) / std::get<2>(y));
        }
      else
        {
          if (y.index() == 1)
            return Solution<Real>(std::get<2>(x) / std::get<1>(y));
          else
            return Solution<Real>(std::get<2>(x) / std::get<2>(y));
        }
    }
operator/() [4/10]
template<typename Real >
constexpr Solution<Real> emsr::operator/ (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 322 of file solution.h.
    { return operator/(x, Solution<Real>(y)); }
References operator/().
operator/() [5/10]
template<typename Real >
constexpr Solution<Real> emsr::operator/ (const Solution< Real > & x, Real y) [constexpr]
Definition at line 312 of file solution.h.
    { return operator/(x, Solution<Real>(y)); }
References operator/().
operator/() [6/10]
template<typename Tp , std::size_t Size>
constexpr StaticPolynomial<Tp, Size> emsr::operator/ (const StaticPolynomial< Tp, Size > & poly, const Tp & x) [inline], [constexpr]
Return the quotient of a polynomial with a scalar.
Definition at line 701 of file static_polynomial.h.
    { return StaticPolynomial<Tp, Size>(poly) /= x; }
operator/() [7/10]
template<typename Real >
constexpr Solution<Real> emsr::operator/ (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 327 of file solution.h.
    { return operator/(Solution<Real>(x), y); }
References operator/().
operator/() [8/10]
template<typename Tp , typename Up >
Polynomial<decltype(Tp() / Up())> emsr::operator/ (const Tp & x, const Polynomial< Up > & poly) [inline]
Return the quotient of a scalar and a polynomials.
Definition at line 1009 of file polynomial.h.
    { return Polynomial<decltype(Tp() / Up())>(x) /= poly; }
operator/() [9/10]
template<typename Real >
constexpr Solution<Real> emsr::operator/ (Real x, const Solution< Real > & y) [constexpr]
Definition at line 317 of file solution.h.
    { return operator/(Solution<Real>(x), y); }
References operator/().
operator/() [10/10]
template<typename Tp , std::size_t SizeP, std::size_t SizeQ>
constexpr StaticPolynomial<Tp, divmod_t<Tp, SizeP, SizeQ>::SizeQuo> emsr::operator/ (StaticPolynomial< Tp, SizeP > P, StaticPolynomial< Tp, SizeQ > Q) [inline], [constexpr]
Return the quotient of two polynomials.
Definition at line 793 of file static_polynomial.h.
    { return divmod(P, Q).quo; }
References divmod().
operator<() [1/5]
template<typename Real >
constexpr bool emsr::operator< (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
Lexicographic order of solutions as complex numbers. Null solutions compare as less than except to another null solution.
A tribool might be a good thing for this when either of the solutions is null.
Definition at line 403 of file solution.h.
    {
      if (x.index() == 0 && y.index() == 0)
        return false;
      else if (x.index() == 0)
        return true;
      else if (y.index() == 0)
        return false;
      else
        {
          const auto rex = emsr::real(x);
          const auto rey = emsr::real(y);
          if (rex < rey)
            return true;
          else if (rex == rey)
            return emsr::imag(x) < emsr::imag(y);
          else
            return false;
        }
    }
References imag(), and real().
operator<() [2/5]
template<typename Real >
constexpr bool emsr::operator< (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 436 of file solution.h.
    { return operator<(x, Solution<Real>(y)); }
operator<() [3/5]
template<typename Real >
constexpr bool emsr::operator< (const Solution< Real > & x, Real y) [constexpr]
Definition at line 426 of file solution.h.
    { return operator<(x, Solution<Real>(y)); }
operator<() [4/5]
template<typename Real >
constexpr bool emsr::operator< (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 441 of file solution.h.
    { return operator<(Solution<Real>(x), y); }
operator<() [5/5]
template<typename Real >
constexpr bool emsr::operator< (Real x, const Solution< Real > & y) [constexpr]
Definition at line 431 of file solution.h.
    { return operator<(Solution<Real>(x), y); }
operator<<() [1/4]
template<typename Char , typename Real >
std::basic_ostream<Char>& emsr::operator<< (std::basic_ostream< Char > & out, const emsr::Solution< Real > & sln)
Output a solution to a stream.
Definition at line 441 of file solution.h.
    {
      const auto idx = sln.index();
      if (idx == 0)
        out << "null";
      else if (idx == 1)
        out << std::get<1>(sln);
      else if (idx == 2)
        out << std::get<2>(sln);
      return out;
    }
operator<<() [2/4]
template<typename CharT , typename Traits , typename Tp >
std::basic_ostream< CharT, Traits > & emsr::operator<< (std::basic_ostream< CharT, Traits > & os, const Polynomial< Tp > & poly)
Write a polynomial to a stream. The format is a parenthesized comma-delimited list of coefficients.
Definition at line 385 of file polynomial.tcc.
    {
      int old_prec = os.precision(std::numeric_limits<Tp>::max_digits10);
      os << "(";
      for (size_t i = 0; i < poly.degree(); ++i)
        os << poly.coefficient(i) << ",";
      os << poly.coefficient(poly.degree());
      os << ")";
      os.precision(old_prec);
      return os;
    }
operator<<() [3/4]
template<typename CharT , typename Traits , typename Tp >
std::basic_ostream<CharT, Traits>& emsr::operator<< (std::basic_ostream< CharT, Traits > & os, const RationalPolynomial< Tp > & poly)
Write a polynomial to a stream. The format is a parenthesized comma-delimited list of coefficients.
Definition at line 1 of file rational_polynomial.h.
    {
      os << poly.numer() << "/" << poly.denom();
      return os;
    }
operator<<() [4/4]
template<typename CharT , typename Traits , typename Tp , std::size_t Size>
std::basic_ostream< CharT, Traits > & emsr::operator<< (std::basic_ostream< CharT, Traits > & os, const StaticPolynomial< Tp, Size > & poly)
Write a polynomial to a stream. The format is a parenthesized comma-delimited list of coefficients.
Definition at line 1 of file static_polynomial.tcc.
    {
      int old_prec = os.precision(std::numeric_limits<Tp>::max_digits10);
      os << "(";
      for (size_t i = 0; i < poly.degree(); ++i)
        os << poly.coefficient(i) << ",";
      os << poly.coefficient(poly.degree());
      os << ")";
      os.precision(old_prec);
      return os;
    }
operator==() [1/8]
template<typename Tp >
bool emsr::operator== (const Polynomial< Tp > & pa, const Polynomial< Tp > & pb) [inline]
Return true if two polynomials are equal.
Definition at line 1052 of file polynomial.h.
    { return pa.m_coeff == pb.m_coeff; }
operator==() [2/8]
template<typename Real >
constexpr bool emsr::operator== (const Solution< Real > & x, const Solution< Real > & y) [constexpr]
Test for equality and inequality.
Definition at line 335 of file solution.h.
    {
      if (x.index() == 0 || y.index() == 0)
        return false;
      else if (x.index() == y.index())
        {
          if (x.index() == 1)
            return std::get<1>(x) == std::get<1>(y);
          else
            return std::get<2>(x) == std::get<2>(y);
        }
      else
        return false;
    }
operator==() [3/8]
template<typename Real >
constexpr bool emsr::operator== (const Solution< Real > & x, const std::complex< Real > & y) [constexpr]
Definition at line 362 of file solution.h.
    { return x == Solution<Real>(y); }
operator==() [4/8]
template<typename Real >
bool emsr::operator== (const Solution< Real > & x, Real y)
Definition at line 352 of file solution.h.
    { return x == Solution<Real>(y); }
operator==() [5/8]
template<typename Tp , std::size_t Size>
constexpr bool emsr::operator== (const StaticPolynomial< Tp, Size > & pa, const StaticPolynomial< Tp, Size > & pb) [inline], [constexpr]
Definition at line 635 of file static_polynomial.h.
    { return pa.m_coeff == pb.m_coeff; }
operator==() [6/8]
template<typename Tp , std::size_t SizeA, std::size_t SizeB>
constexpr bool emsr::operator== (const StaticPolynomial< Tp, SizeA > & , const StaticPolynomial< Tp, SizeB > &) [inline], [constexpr]
Return true if two polynomials are equal.
Definition at line 629 of file static_polynomial.h.
    { return false; }
operator==() [7/8]
template<typename Real >
constexpr bool emsr::operator== (const std::complex< Real > & x, const Solution< Real > & y) [constexpr]
Definition at line 367 of file solution.h.
    { return Solution<Real>(x) == y; }
operator==() [8/8]
template<typename Real >
constexpr bool emsr::operator== (Real x, const Solution< Real > & y) [constexpr]
Definition at line 357 of file solution.h.
    { return Solution<Real>(x) == y; }
operator>>() [1/2]
template<typename CharT , typename Traits , typename Tp >
std::basic_istream< CharT, Traits > & emsr::operator>> (std::basic_istream< CharT, Traits > & is, Polynomial< Tp > & poly)
Read a polynomial from a stream. The input format can be a plain scalar (zero degree polynomial) or a parenthesized comma-delimited list of coefficients.
Definition at line 436 of file polynomial.tcc.
    {
      Tp x;
      CharT ch;
      is >> ch;
      if (ch == '(')
        {
          do
            {
              is >> x >> ch;
              poly.m_coeff.push_back(x);
            }
          while (ch == ',');
          if (ch != ')')
            is.setstate(std::ios_base::failbit);
        }
      else
        {
          is.putback(ch);
          is >> x;
          poly = x;
        }
      // No null polynomial.
      if (poly.size() == 0)
        poly.m_coeff.resize(1, Tp{});
      return is;
    }
References emsr::Polynomial< Tp >::size().
operator>>() [2/2]
template<typename CharT , typename Traits , typename Tp >
std::basic_istream<CharT, Traits>& emsr::operator>> (std::basic_istream< CharT, Traits > & is, RationalPolynomial< Tp > & poly)
Read a polynomial from a stream. The input format can be a plain scalar (zero degree polynomial) or a parenthesized comma-delimited list of coefficients.
Definition at line 216 of file rational_polynomial.h.
    {
      Polynomial<Tp> numer, denom;
      is >> numer;
      if (!is.fail())
        {
          CharT ch;
          is >> ch;
          if (ch != '/')
            is.setstate(std::ios_base::failbit);
          else
            {
              is >> denom;
              if (!is.fail())
                {
                  poly.numer() = numer;
                  poly.denom() = denom;
                }
            }
        }
      return is;
    }
References emsr::RationalPolynomial< Tp >::denom(), and emsr::RationalPolynomial< Tp >::numer().
quadratic() [1/3]
template<typename Real , typename _Iter >
std::array<Solution<Real>, 2> emsr::quadratic (const _Iter & _CC)
Finds the roots of a quadratic equation of the form:
 a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
For non-degenerate coefficients two roots are returned: Either the roots are real or the roots are a complex conjugate pair.
If the quadratic coefficient $ a_2 $ is zero (degenerate case) at most one valid root is returned. If the linear coefficient $ a_1 $ is also zero no valid root is returned.
Parameters
 in _CC Array that contains the three coefficients of the quadratic equation.
Definition at line 143 of file solver_low_degree.tcc.
    {
      std::array<Solution<Real>, 2> _ZZ;
      if (_CC[2] == Real{0})
        {
          // Equation is linear (or completely degenerate).
          if (_CC[1] == Real{0})
            return _ZZ;
          else
            {
              _ZZ[0] = -_CC[0] / _CC[1];
              return _ZZ;
            }
        }
      else if (_CC[0] == Real{0})
        {
          _ZZ[0] = Real{0};
          if (_CC[2] == Real{0})
            return _ZZ;
          else
            {
              _ZZ[1] = -_CC[1] / _CC[2];
              return _ZZ;
            }
        }
      else
        {
          // The discriminant of a quadratic equation
          const auto _QQ = _CC[1] * _CC[1] - Real{4} * _CC[2] * _CC[0];
          if (_QQ < Real{0})
            {
              // The roots are complex conjugates.
              const auto _ReZZ = -_CC[1] / (Real{2} * _CC[2]);
              const auto _ImZZ = std::sqrt(std::abs(_QQ)) / (Real{2} * _CC[2]);
              _ZZ[0] = std::complex<Real>(_ReZZ, -_ImZZ);
              _ZZ[1] = std::complex<Real>(_ReZZ, _ImZZ);
            }
          else
            {
              // The roots are real.
              Real temp = -(_CC[1]
                        + std::copysign(std::sqrt(_QQ), _CC[1])) / Real{2};
              _ZZ[0] = temp / _CC[2];
              _ZZ[1] = _CC[0] / temp;
            }
        }
      return _ZZ;
    }
References abs().
quadratic() [2/3]
template<typename Real , typename Iter >
std::array<Solution<Real>, 2> emsr::quadratic (const Iter & coef)
Referenced by emsr::JenkinsTraubSolver< Real >::solve().
quadratic() [3/3]
template<typename Real >
std::array<Solution<Real>, 2> emsr::quadratic (Real c0, Real c1, Real c2) [inline]
Definition at line 62 of file solver_low_degree.h.
    {
      return quadratic<Real>(std::array<Real, 3>{c0, c1, c2});
    }
quartic() [1/2]
template<typename Real , typename Iter >
std::array< Solution< Real >, 4 > emsr::quartic (const Iter & CC)
Finds the roots a quartic equation of the form:
 a_4 x^4 + a_3 x^3 + a_2 x^2 + a_1 x + a_0 = 0 
 for real coefficients $ a_k $.
In the non-degenerate case there are four roots:
All four roots are real
Two roots real and two complex roots are a complex conjugate pair
Four complex roots in two complex conjugate pairs
If the qartic coefficient $ a_4 $ is zero (degenerate case) the problem is referred to the cubic solver to return, at most, three valid roots.
Parameters
 in CC Array that contains the five(5) coefficients of the quartic equation.
Definition at line 307 of file solver_low_degree.tcc.
    {
      std::array<Solution<Real>, 4> ZZ;
      if (CC[4] == Real{0})
        {
          const auto ZZ3 = cubic<Real>(CC);
          ZZ[0] = ZZ3[0];
          ZZ[1] = ZZ3[1];
          ZZ[2] = ZZ3[2];
        }
      else if (CC[0] == Real{0})
        {
          ZZ[0] = Real{0};
          const auto ZZ3 = cubic<Real>(CC[1], CC[2], CC[3], CC[4]);
          ZZ[1] = ZZ3[0];
          ZZ[2] = ZZ3[1];
        }
      else if (CC[3] == Real{0} && CC[1] == Real{0})
        {
          // Solve the biquadratic equation.
          std::array<Real, 3> AA2{{CC[0], CC[2], CC[4]}};
          const auto ZZ2 = quadratic<Real>(AA2);
          auto sqrt = [](Solution<Real> z) -> Solution<Real>
                        {
                          const auto idx = z.index();
                          if (idx == 0)
                            return z;
                          else if (idx == 1)
                            {
                              auto zz = std::get<1>(z);
                              return zz < Real{0}
                                   ? Solution<Real>(std::sqrt(std::complex<Real>(zz)))
                                   : Solution<Real>(std::sqrt(zz));
                            }
                          else
                            return Solution<Real>(std::sqrt(std::get<2>(z)));
                        };
          ZZ[0] = sqrt(ZZ2[0]);
          ZZ[1] = sqrt(ZZ2[1]);
          ZZ[2] = -ZZ[0];
          ZZ[3] = -ZZ[1];
        }
      else
        {
          // Normalize quartic equation coefficients.
          std::array<Real, 5> AA4;
          AA4[4] = Real{1};
          AA4[3] = CC[3] / CC[4];
          AA4[2] = CC[2] / CC[4];
          AA4[1] = CC[1] / CC[4];
          AA4[0] = CC[0] / CC[4];
          // Calculate the coefficients of the resolvent cubic equation.
          std::array<Real, 4> AA3;
          AA3[3] = Real{1};
          AA3[2] = -AA4[2];
          AA3[1] = AA4[3] * AA4[1] - Real{4} * AA4[0];
          AA3[0] = AA4[0] * (Real{4} * AA4[2] - AA4[3] * AA4[3])
                  - AA4[1] * AA4[1];
          // Find the algebraically largest real root of the cubic equation
          // Note: A cubic equation has either three real roots or one
          // real root and two complex roots that are complex
          // conjugates. If there is only a single real root then
          // subroutine cubic always returns that single real root
          // (and therefore the algebraically largest real root of
          // the cubic equation) as root[0].
          Real Z3max;
          auto ZZ3 = cubic<Real>(AA3);
          if (ZZ3[1].index() == 1 && ZZ3[2].index() == 1)
            {
              // There is some horrible bug with swap and this variant.
              // They may need to hold the same type.
              if (ZZ3[0] < ZZ3[1])
                //std::swap(ZZ3[0], ZZ3[1]);
                {
                  const auto tmp = ZZ3[0];
                  ZZ3[0] = ZZ3[1];
                  ZZ3[1] = tmp;
                }
              if (ZZ3[0] < ZZ3[2])
                //std::swap(ZZ3[0], ZZ3[2]);
                {
                  const auto tmp = ZZ3[0];
                  ZZ3[0] = ZZ3[2];
                  ZZ3[2] = tmp;
                }
              Z3max = std::get<1>(ZZ3[0]);
            }
          else
            Z3max = std::get<1>(ZZ3[0]);
          // Calculate the coefficients for the two quadratic equations
          const auto capa = Real{0.5L} * AA4[3];
          const auto capb = Real{0.5L} * Z3max;
          const auto capc = std::sqrt(capa * capa - AA4[2] + Z3max);
          const auto capd = std::sqrt(capb * capb - AA4[0]);
          const auto cp = capa + capc;
          const auto cm = capa - capc;
          auto dp = capb + capd;
          auto dm = capb - capd;
          const auto t1 = cp * dm + cm * dp;
          const auto t2 = cp * dp + cm * dm;
          if (std::abs(t2 - AA4[1]) < std::abs(t1 - AA4[1]))
            std::swap(dp, dm);
          // Coefficients for the first quadratic equation and find the roots.
          std::array<Real, 3> AA2;
          AA2[2] = Real{1};
          AA2[1] = cp;
          AA2[0] = dp;
          const auto ZZ2p = quadratic<Real>(AA2);
          ZZ[0] = ZZ2p[0];
          ZZ[1] = ZZ2p[1];
          // Coefficients for the second quadratic equation and find the roots.
          AA2[2] = Real{1};
          AA2[1] = cm;
          AA2[0] = dm;
          const auto ZZ2m = quadratic<Real>(AA2);
          ZZ[2] = ZZ2m[0];
          ZZ[3] = ZZ2m[1];
        }
      return ZZ;
    }
References abs(), and swap().
quartic() [2/2]
template<typename Real >
std::array<Solution<Real>, 4> emsr::quartic (Real c0, Real c1, Real c2, Real c3, Real c4) [inline]
Definition at line 84 of file solver_low_degree.h.
    {
      return quartic<Real>(std::array<Real, 5>{c0, c1, c2, c3, c4});
    }
quot() [1/5]
constexpr quot_t emsr::quot (int numer, int denom) [constexpr]
quot() [2/5]
constexpr lquot_t emsr::quot (long int numer, long int denom) [constexpr]
quot() [3/5]
constexpr llquot_t emsr::quot (long long int numer, long long int denom) [constexpr]
quot() [4/5]
constexpr squot_t emsr::quot (short int numer, short int denom) [constexpr]
quot() [5/5]
constexpr intmaxquot_t emsr::quot (std::intmax_t x, std::intmax_t y) [constexpr]
real()
template<typename Real >
constexpr Real emsr::real (const Solution< Real > & x) [constexpr]
Definition at line 73 of file solution.h.
    {
      if (x.index() == 0)
        return std::numeric_limits<Real>::quiet_NaN();
      else if (x.index() == 1)
        return std::get<1>(x);
      else
        return std::real(std::get<2>(x));
    }
Referenced by norm_l1(), and operator<().
refine_solution_halley() [1/2]
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp emsr::refine_solution_halley (_NumTp z, const _Iter & _CC)
Refine a solution using the Halley method:
 x_{n+1} - x_n = -\frac{2 P(x_n) P\textnormal{\textquotesingle}(x_n)} {2 [P\textnormal{\textquotesingle}(x_n)]^2 - P(x_n) P\textnormal{\textquotesingle}\textnormal{\textquotesingle}(x_n)} 
 This form indicates the close relationship to the Newton method:
 x_{n+1} - x_n = -\frac{P\textnormal{\textquotesingle}(x_n)} {P\textnormal{\textquotesingle}(x_n) - [P(x_n) P\textnormal{\textquotesingle}\textnormal{\textquotesingle}(x_n)]/[2P\textnormal{\textquotesingle}(x_n)]} 
Definition at line 84 of file solver_low_degree.tcc.
    {
      for (int i = 0; i < 3; ++i)
        {
          auto f = _NumTp(_CC[_Dim - 1]);
          for (std::size_t j = _Dim - 1; j > 0; --j)
            f = _NumTp(_CC[j - 1]) + z * f;
          auto df = _NumTp((_Dim - 1) * _CC[_Dim - 1]);
          for (std::size_t j = _Dim - 1; j > 1; --j)
            df = _NumTp((j - 1) * _CC[j - 1]) + z * df;
          auto d2f = _NumTp((_Dim - 2) * (_Dim - 1) * _CC[_Dim - 1]);
          for (std::size_t j = _Dim - 1; j > 2; --j)
            d2f = _NumTp((j - 2) * (j - 1) * _CC[j - 1]) + z * d2f;
          const auto del = _NumTp{2} * f * df
                           / (_NumTp{2} * df * df - f * d2f);
          z -= del;
        }
      return z;
    }
refine_solution_halley() [2/2]
template<std::size_t Dim, typename Iter , typename NumTp >
NumTp emsr::refine_solution_halley (NumTp z, const Iter & CC)
refine_solution_newton() [1/2]
template<std::size_t _Dim, typename _Iter , typename _NumTp >
_NumTp emsr::refine_solution_newton (_NumTp z, const _Iter & _CC)
Refine a solution using the Newton method:
 x_{n+1} - x_n = -\frac{P(x_n)}{P\textnormal{\textquotesingle}(x_n)} 
Definition at line 52 of file solver_low_degree.tcc.
    {
      for (int i = 0; i < 3; ++i)
        {
          auto f = _NumTp(_CC[_Dim - 1]);
          for (std::size_t j = _Dim - 1; j > 0; --j)
            f = _NumTp(_CC[j - 1]) + z * f;
          auto df = _NumTp((_Dim - 1) * _CC[_Dim - 1]);
          for (std::size_t j = _Dim - 1; j > 1; --j)
            df = _NumTp((j - 1) * _CC[j - 1]) + z * df;
          const auto del = f / df;
          z -= del;
        }
      return z;
    }
refine_solution_newton() [2/2]
template<std::size_t Dim, typename Iter , typename NumTp >
NumTp emsr::refine_solution_newton (NumTp z, const Iter & CC)
refine_solutions()
template<std::size_t _Dim, typename _Iter , typename Real >
void emsr::refine_solutions (std::array< Solution< Real >, _Dim - 1 > & _ZZ, const _Iter & _CC)
Definition at line 110 of file solver_low_degree.tcc.
    {
      for (std::size_t i = 0; i < _Dim - 1; ++i)
        {
          if (_ZZ[i].index() == 0)
            continue;
          else if (_ZZ[i].index() == 1)
            _ZZ[i] = refine_solution_newton<_Dim>(std::get<1>(_ZZ[i]), _CC);
          else if (_ZZ[i].index() == 2)
            _ZZ[i] = refine_solution_newton<_Dim>(std::get<2>(_ZZ[i]), _CC);
        }
    }
remquo() [1/3]
constexpr remquo_t<double> emsr::remquo (double x, double y) [constexpr]
remquo() [2/3]
constexpr remquo_t<float> emsr::remquo (float x, float y) [constexpr]
remquo() [3/3]
constexpr remquo_t<long double> emsr::remquo (long double x, long double y) [constexpr]
remquof()
constexpr remquo_t<float> emsr::remquof (float x, float y) [constexpr]
remquol()
constexpr remquo_t<long double> emsr::remquol (long double x, long double y) [constexpr]
sec()
double emsr::sec (double x)
sec_pi() [1/2]
double emsr::sec_pi (double x)
sec_pi() [2/2]
double emsr::sec_pi (reperiod_t< double > x)
sec_pif() [1/2]
float emsr::sec_pif (float x)
sec_pif() [2/2]
float emsr::sec_pif (reperiod_t< float > x)
sec_pil() [1/2]
long double emsr::sec_pil (long double x)
sec_pil() [2/2]
long double emsr::sec_pil (reperiod_t< long double > x)
secf()
float emsr::secf (float x)
sech()
double emsr::sech (double x)
sechf()
float emsr::sechf (float x)
sechl()
long double emsr::sechl (long double x)
secl()
long double emsr::secl (long double x)
sign()
template<typename Tp >
Tp emsr::sign (Tp x) [inline]
Definition at line 430 of file notsospecfun.h.
    { return Tp(x < 0 ? -1 : -1); }
signum()
template<typename Tp >
Tp emsr::signum (Tp x) [inline]
Definition at line 436 of file notsospecfun.h.
    { return Tp(x == 0 ? 0 : x < 0 ? -1 : -1); }
sin_pi() [1/2]
double emsr::sin_pi (double x)
sin_pi() [2/2]
double emsr::sin_pi (reperiod_t< double > x)
sin_pif() [1/2]
float emsr::sin_pif (float x)
sin_pif() [2/2]
float emsr::sin_pif (reperiod_t< float > x)
sin_pil() [1/2]
long double emsr::sin_pil (long double x)
sin_pil() [2/2]
long double emsr::sin_pil (reperiod_t< long double > x)
sincos()
sincos_t<double> emsr::sincos (double x)
sincos_pi() [1/2]
sincos_t<double> emsr::sincos_pi (double x)
sincos_pi() [2/2]
sincos_t<double> emsr::sincos_pi (reperiod_t< double > x)
sincos_pif() [1/2]
sincos_t<float> emsr::sincos_pif (float x)
sincos_pif() [2/2]
sincos_t<float> emsr::sincos_pif (reperiod_t< float > x)
sincos_pil() [1/2]
sincos_t<long double> emsr::sincos_pil (long double x)
sincos_pil() [2/2]
sincos_t<long double> emsr::sincos_pil (reperiod_t< long double > x)
sincosf()
sincos_t<float> emsr::sincosf (float x)
sincosl()
sincos_t<long double> emsr::sincosl (long double x)
sinhcosh()
sinhcosh_t<double> emsr::sinhcosh (double x)
sinhcoshf()
sinhcosh_t<float> emsr::sinhcoshf (float x)
sinhcoshl()
sinhcosh_t<long double> emsr::sinhcoshl (long double x)
slgamma()
lgamma_t<double> emsr::slgamma (double x)
slgammaf()
lgamma_t<float> emsr::slgammaf (float x)
slgammal()
lgamma_t<long double> emsr::slgammal (long double x)
squot()
constexpr squot_t emsr::squot (short int numer, short int denom) [constexpr]
swap()
template<typename Tp >
void emsr::swap (Polynomial< Tp > & pa, Polynomial< Tp > & pb) [inline], [noexcept]
See Polynomial::swap().
Definition at line 1068 of file polynomial.h.
    { pa.swap(pb); }
Referenced by quartic().
tan_pi() [1/2]
double emsr::tan_pi (double x)
tan_pi() [2/2]
double emsr::tan_pi (reperiod_t< double > x)
tan_pif() [1/2]
float emsr::tan_pif (float x)
tan_pif() [2/2]
float emsr::tan_pif (reperiod_t< float > x)
tan_pil() [1/2]
long double emsr::tan_pil (long double x)
tan_pil() [2/2]
long double emsr::tan_pil (reperiod_t< long double > x)
to_complex()
template<typename Real >
constexpr Solution<Real> emsr::to_complex (const Solution< Real > & x) [constexpr]
Return the solution as a complex number or NaN.
Definition at line 112 of file solution.h.
    {
      if (x.index() == 0)
        return Solution<Real>();
      else if (x.index() == 1)
        return Solution<Real>(std::complex<Real>(std::get<1>(x)));
      else
        return x;
    }
Variable Documentation
has_imag_v
template<typename Tp >
constexpr auto emsr::has_imag_v = has_imag_t<Tp>::value [constexpr]
Definition at line 93 of file polynomial.h.
has_value_type_v
template<typename Tp >
constexpr auto emsr::has_value_type_v = has_value_type_t<Tp>::value [constexpr]
Definition at line 107 of file polynomial.h.
pi_v
template<typename Tp >
Tp emsr::pi_v = static_cast<Tp>(3.1415926536897932384626L)
Definition at line 184 of file notsospecfun.h.